In [ ]:
!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Collecting datasets
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.5.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 15.9 MB/s eta 0:00:00
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 17.4 MB/s eta 0:00:00
Installing collected packages: fsspec, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.6.0 fsspec-2025.3.0

In [ ]:
# from datasets import load_dataset

# dataset = load_dataset("ai4bharat/sangraha", data_dir="verified/ben_Beng")

In [ ]:
from datasets import load_dataset

dataset = load_dataset("ai4bharat/Pralekha", data_dir="dev")

README.md: 0.00B [00:00, ?B/s]

eng_ben-00000-of-00001.parquet:   0%|          | 0.00/4.28M [00:00<?, ?B/s]

eng_guj-00000-of-00001.parquet:   0%|          | 0.00/4.48M [00:00<?, ?B/s]

eng_hin-00000-of-00001.parquet:   0%|          | 0.00/4.33M [00:00<?, ?B/s]

eng_kan-00000-of-00001.parquet:   0%|          | 0.00/4.55M [00:00<?, ?B/s]

eng_mal-00000-of-00001.parquet:   0%|          | 0.00/4.55M [00:00<?, ?B/s]

eng_mar-00000-of-00001.parquet:   0%|          | 0.00/4.57M [00:00<?, ?B/s]

eng_ori-00000-of-00001.parquet:   0%|          | 0.00/4.45M [00:00<?, ?B/s]

eng_pan-00000-of-00001.parquet:   0%|          | 0.00/4.39M [00:00<?, ?B/s]

eng_tam-00000-of-00001.parquet:   0%|          | 0.00/3.95M [00:00<?, ?B/s]

eng_tel-00000-of-00001.parquet:   0%|          | 0.00/4.68M [00:00<?, ?B/s]

eng_urd-00000-of-00001.parquet:   0%|          | 0.00/3.97M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['src_lang', 'tgt_lang', 'src_txt', 'tgt_txt'],
        num_rows: 11000
    })
})

In [ ]:
import pandas as pd

In [ ]:
df = dataset.data['train'].to_pandas()

In [ ]:
df.shape

(11000, 4)

In [ ]:
df.head()

,src_lang,tgt_lang,src_txt,tgt_txt
0,eng,ben,My dear countrymen. Namaskar. ‘Mann Ki Baat’ m...,"আমার প্রিয় দেশবাসী, নমস্কার। ‘মন কি বাত’ অর্থা..."
1,eng,ben,"My dear countrymen, Namaskar. I am feeling ver...","আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯..."
2,eng,ben,"My dear countrymen, Namaskar.\nOnce again, a v...","নতুনদিল্লি, ২৮শে মে, ২০২৩\nআমার প্রিয় দেশবাসী,..."
3,eng,ben,"My dear countrymen, Namaskar. Today, the entir...","আমার প্রিয় দেশবাসী, নমস্কার! আজ সমগ্র দেশ রাখী..."
4,eng,ben,My dearest countrymen namaskar. Before each ep...,"আমার প্রিয় দেশবাসী, নমস্কার!\nপ্রতিটি ‘মন কি ব..."

In [ ]:
# df = df[df['lang'] == 'ben']

In [ ]:
df = df[df['tgt_lang'] == 'ben']

In [ ]:
df.shape

(1000, 4)

In [ ]:
df

,src_lang,tgt_lang,src_txt,tgt_txt
0,eng,ben,My dear countrymen. Namaskar. ‘Mann Ki Baat’ m...,"আমার প্রিয় দেশবাসী, নমস্কার। ‘মন কি বাত’ অর্থা..."
1,eng,ben,"My dear countrymen, Namaskar. I am feeling ver...","আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯..."
2,eng,ben,"My dear countrymen, Namaskar.\nOnce again, a v...","নতুনদিল্লি, ২৮শে মে, ২০২৩\nআমার প্রিয় দেশবাসী,..."
3,eng,ben,"My dear countrymen, Namaskar. Today, the entir...","আমার প্রিয় দেশবাসী, নমস্কার! আজ সমগ্র দেশ রাখী..."
4,eng,ben,My dearest countrymen namaskar. Before each ep...,"আমার প্রিয় দেশবাসী, নমস্কার!\nপ্রতিটি ‘মন কি ব..."
...,...,...,...,...
995,eng,ben,Prime Minister's Office\nPM condoles demise of...,প্রধানমন্ত্রীরদপ্তর\nশ্রী এম জি বৈদ্যজির প্রয়া...
996,eng,ben,Prime Minister's Office\nPM asks people for Or...,প্রধানমন্ত্রীরদপ্তর\nজনগণকে বাড়িতে জৈব চাষ করত...
997,eng,ben,Prime Minister's Office\nPM expresses delight ...,প্রধানমন্ত্রীরদপ্তর\nমেঘালয়ে এই প্রথমবার পৌঁছে...
998,eng,ben,Prime Minister's Office\nPM condoles deaths in...,প্ৰধানমন্ত্ৰীৰ কাৰ্যালয়\nনন্দুৰবাৰত সংঘটিত প্ৰ...
999,eng,ben,Prime Minister's Office\nCredit Guarantee Sche...,প্রধানমন্ত্রীরদপ্তর\nঋণ নিশ্চয়তা প্রকল্পকে শক্...

In [ ]:
!pip install bnlp-toolkit transformers google-cloud-translate pandas tqdm

Requirement already satisfied: bnlp-toolkit in /usr/local/lib/python3.11/dist-packages (4.0.3)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: google-cloud-translate in /usr/local/lib/python3.11/dist-packages (3.20.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.66.3)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (0.2.0)
Requirement already satisfied: gensim==4.3.2 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (4.3.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.26.4)
Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.10.1)
Requirement already satisfied: sklearn-crfsuite==0.3.6 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (0.3.6)
Requirement already satisfied: ftfy==6.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (6.2.0)
Requirement already satisfied: emoji==1.7.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.7.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (2.32.3)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/lib/python3.11/dist-packages (from ftfy==6.2.0->bnlp-toolkit) (0.2.13)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.2->bnlp-toolkit) (7.1.0)
Requirement already satisfied: python-crfsuite>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (0.9.11)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (0.9.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-translate) (2.25.1)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-translate) (2.38.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.4 in /usr/local/lib/python3.11/dist-packages (from google-cloud-translate) (2.4.3)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-cloud-translate) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-translate) (5.29.5)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-translate) (0.14.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-translate) (1.70.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-translate) (1.73.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-translate) (1.71.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-translate) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-translate) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-translate) (4.9.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp-toolkit) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp-toolkit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp-toolkit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp-toolkit) (2025.6.15)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp-toolkit) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp-toolkit) (1.5.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-translate) (0.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.2->bnlp-toolkit) (1.17.2)

In [ ]:
from bnlp import POS
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from google.cloud import translate_v2 as translate
import pandas as pd
import json
import os
from tqdm import tqdm
import time

ImportError: cannot import name 'POS' from 'bnlp' (/usr/local/lib/python3.11/dist-packages/bnlp/__init__.py)

In [ ]:
# %% [markdown]
"""
# Bengali-English Code Mixing Pipeline
**Features:**
1. POS-guided lexical replacement (Bengali → English)
2. Dynamic translation using Google Cloud API (for OOV words)
3. Fluency correction with BanglaT5
4. Caching for cost efficiency
"""

# %% [markdown]
"""
## Step 1: Install Dependencies
"""

# %%
# %% [markdown]
"""
## Step 2: Initialize Models
"""

# %%

# Initialize Bengali POS tagger
bn_pos = POS()

# Load BanglaT5 for fluency correction
tokenizer = AutoTokenizer.from_pretrained("csebuetnlp/banglat5_base")
model = AutoModelForSeq2SeqLM.from_pretrained("csebuetnlp/banglat5_base")

# %% [markdown]
"""
## Step 3: Google Cloud Setup (Run only once)
"""

# %%
# Upload your Google Cloud service account key (JSON)
from google.colab import files
uploaded = files.upload()
key_file = list(uploaded.keys())[0]
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = key_file

# Initialize Google Translate client
translate_client = translate.Client()

# %% [markdown]
"""
## Step 4: Core Functions
"""

# %%
# Load/save translation cache
def load_lexicon_cache(cache_path="lexicon_cache.json"):
    try:
        with open(cache_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_lexicon_cache(cache, cache_path="lexicon_cache.json"):
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

LEXICON = load_lexicon_cache()

# Google Translate with rate limiting
def translate_word(bn_word, target_lang="en", max_retries=3):
    if bn_word in LEXICON:
        return LEXICON[bn_word]

    for _ in range(max_retries):
        try:
            result = translate_client.translate(bn_word, target_lang=target_lang)
            time.sleep(0.1)  # Rate limiting
            translated = result["translatedText"].lower()
            LEXICON[bn_word] = translated  # Cache result
            return translated
        except Exception as e:
            print(f"Retrying '{bn_word}': {e}")
            time.sleep(1)
    return None

# POS-guided code mixing
def pos_guided_code_mix(sentence, use_google=False):
    tagged = bn_pos.tag(sentence)
    mixed_words = []
    for word, pos in tagged:
        if pos in ["NN", "NNP", "JJ"]:  # Nouns/adjectives only
            if word in LEXICON:
                mixed_words.append(LEXICON[word])
            elif use_google:
                translated = translate_word(word)
                mixed_words.append(translated if translated else word)
            else:
                mixed_words.append(word)
        else:
            mixed_words.append(word)
    return " ".join(mixed_words)

# Fluency correction with BanglaT5
def refine_with_lm(text):
    input_ids = tokenizer.encode("Fix grammar: " + text, return_tensors="pt")
    outputs = model.generate(input_ids, max_length=50)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# %% [markdown]
"""
## Step 5: Process Your DataFrame
"""

# %%
# Assuming your DataFrame is named `df` with a column 'text'
def process_batch(df, text_column="text", use_google=True, save_path="output.csv"):
    tqdm.pandas(desc="Code-mixing progress")

    # Step 1: POS + Google Translate
    df["code_mixed"] = df[text_column].progress_apply(
        lambda x: pos_guided_code_mix(x, use_google=use_google)
    )

    # Step 2: Fluency correction (sample 20% to save time)
    sample_size = min(1000, len(df))  # Adjust based on your needs
    sample = df.sample(sample_size)
    sample["refined"] = sample["code_mixed"].progress_apply(refine_with_lm)

    # Save cache and results
    save_lexicon_cache(LEXICON)
    df.to_csv(save_path, index=False)
    return df

# Example usage:
# df_processed = process_batch(df, text_column="your_text_column")

# %% [markdown]
"""
## Step 6: Run Pipeline (Customize for Your DF)
"""

# %%
# Replace this with your actual DataFrame loading code
# Example dummy data
df = pd.DataFrame({
    "text": [
        "আমার বইটি টেবিলে আছে",
        "সে স্কুলে যায়",
        "এই অপ্রচলিত শব্দটি অনুবাদ করুন"
    ]
})

# Process all rows
df_processed = process_batch(df, text_column="text", use_google=True)

# Show results
print(df_processed.head())

# %% [markdown]
"""
## Optional: Pre-cache Frequent Words
"""

# %%
def pre_cache_words(texts, top_n=500):
    words = []
    for text in texts:
        tagged = bn_pos.tag(text)
        words.extend([word for word, pos in tagged if pos in ["NN", "NNP", "JJ"]])

    common_words = pd.Series(words).value_counts().head(top_n).index.tolist()
    for word in tqdm(common_words, desc="Pre-caching translations"):
        if word not in LEXICON:
            translate_word(word)
    save_lexicon_cache(LEXICON)

# Run on your dataset
# pre_cache_words(df["text"].tolist())

In [ ]:
# Step 1: Install required packages
!pip install bnlp-toolkit transformers google-cloud-translate pandas tqdm

# Step 2: Import libraries
from bnlp import BengaliPOS  # Updated import for POS tagging
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from google.cloud import translate_v2 as translate
import pandas as pd
import json
import os
from tqdm import tqdm
import time

# Initialize Bengali POS tagger (updated initialization)
bn_pos = BengaliPOS()

# Load BanglaT5 for fluency correction
tokenizer = AutoTokenizer.from_pretrained("csebuetnlp/banglat5_small")
model = AutoModelForSeq2SeqLM.from_pretrained("csebuetnlp/banglat5_small")

# Step 3: Google Cloud Setup (Run only once)
from google.colab import files
uploaded = files.upload()
key_file = list(uploaded.keys())[0]
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = key_file

# Initialize Google Translate client
translate_client = translate.Client()

# Step 4: Core Functions
def load_lexicon_cache(cache_path="lexicon_cache.json"):
    try:
        with open(cache_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_lexicon_cache(cache, cache_path="lexicon_cache.json"):
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

LEXICON = load_lexicon_cache()

def translate_word(bn_word, target_lang="en", max_retries=3):
    if bn_word in LEXICON:
        return LEXICON[bn_word]

    for _ in range(max_retries):
        try:
            result = translate_client.translate(bn_word, target_lang=target_lang)
            time.sleep(0.1)  # Rate limiting
            translated = result["translatedText"].lower()
            LEXICON[bn_word] = translated  # Cache result
            return translated
        except Exception as e:
            print(f"Retrying '{bn_word}': {e}")
            time.sleep(1)
    return None

def pos_guided_code_mix(sentence, use_google=False):
    # Updated POS tagging call
    tagged = bn_pos.tag(sentence)
    mixed_words = []
    for token in tagged:
        word, pos = token["word"], token["pos"]
        if pos in ["NN", "NNP", "JJ"]:  # Nouns/adjectives only
            if word in LEXICON:
                mixed_words.append(LEXICON[word])
            elif use_google:
                translated = translate_word(word)
                mixed_words.append(translated if translated else word)
            else:
                mixed_words.append(word)
        else:
            mixed_words.append(word)
    return " ".join(mixed_words)

def refine_with_lm(text):
    input_ids = tokenizer.encode("Fix grammar: " + text, return_tensors="pt")
    outputs = model.generate(input_ids, max_length=50)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Step 5: Process Your DataFrame
def process_batch(df, text_column="text", use_google=True, save_path="output.csv"):
    tqdm.pandas(desc="Code-mixing progress")

    # Step 1: POS + Google Translate
    df["code_mixed"] = df[text_column].progress_apply(
        lambda x: pos_guided_code_mix(x, use_google=use_google)
    )

    # Step 2: Fluency correction (sample 20% to save time)
    sample_size = min(1000, len(df))  # Adjust based on your needs
    sample = df.sample(sample_size)
    sample["refined"] = sample["code_mixed"].progress_apply(refine_with_lm)

    # Save cache and results
    save_lexicon_cache(LEXICON)
    df.to_csv(save_path, index=False)
    return df

# Example usage with dummy data
df = pd.DataFrame({
    "text": [
        "আমার বইটি টেবিলে আছে",
        "সে স্কুলে যায়",
        "এই অপ্রচলিত শব্দটি অনুবাদ করুন"
    ]
})

# Process all rows
df_processed = process_batch(df, text_column="text", use_google=True)

# Show results
print(df_processed.head())

Requirement already satisfied: bnlp-toolkit in /usr/local/lib/python3.11/dist-packages (4.0.3)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.66.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (0.2.0)
Requirement already satisfied: gensim==4.3.2 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (4.3.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.26.4)
Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.10.1)
Requirement already satisfied: sklearn-crfsuite==0.3.6 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (0.3.6)
Requirement already satisfied: ftfy==6.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (6.2.0)
Requirement already satisfied: emoji==1.7.0 in /usr/local/lib/python3.11/dist-packages (from bnlp-toolkit) (1.7.0)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/lib/python3.11/dist-packages (from ftfy==6.2.0->bnlp-toolkit) (0.2.13)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.2->bnlp-toolkit) (7.1.0)
Requirement already satisfied: python-crfsuite>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (0.9.11)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp-toolkit) (0.9.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.6.15)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp-toolkit) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp-toolkit) (1.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.2->bnlp-toolkit) (1.17.2)

NameError: name 'load_lexicon_cache' is not defined

In [ ]:
# -*- coding: utf-8 -*-
"""Bengali-English Code Mixing with Local Translation Fallback.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yb4G3E5J9Y8Q7Q9Q9Q9Q9Q9Q9Q9Q9Q9
"""

# Step 1: Install all required packages
!pip install -q bnlp-toolkit transformers pandas tqdm requests torch sentencepiece

# Step 2: Import all necessary libraries
from bnlp import BengaliPOS
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
import pandas as pd
import json
import requests
from tqdm.auto import tqdm
import torch
import time
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

# Initialize Bengali POS tagger
print("Loading Bengali POS tagger...")
bn_pos = BengaliPOS()

# Load local translation model (NLLB-200 Distilled 600M)
print("Loading translation models...")
device = 0 if torch.cuda.is_available() else -1
local_translator = pipeline(
    "translation",
    model="facebook/nllb-200-distilled-600M",
    tokenizer="facebook/nllb-200-distilled-600M",
    src_lang="ben_Beng",
    tgt_lang="eng_Latn",
    device=device
)

# Load BanglaT5 for fluency correction
banglat5_tokenizer = AutoTokenizer.from_pretrained("csebuetnlp/banglat5_small")
banglat5_model = AutoModelForSeq2SeqLM.from_pretrained("csebuetnlp/banglat5_small")

# Initialize translation cache
translation_cache = defaultdict(dict)
CACHE_FILE = "translation_cache.json"

def load_cache():
    try:
        with open(CACHE_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return defaultdict(dict)

def save_cache():
    with open(CACHE_FILE, 'w', encoding='utf-8') as f:
        json.dump(translation_cache, f, ensure_ascii=False, indent=2)

translation_cache = load_cache()

def translate_with_libretranslate(text, source="bn", target="en"):
    """Translate using LibreTranslate API"""
    try:
        response = requests.post(
            "https://libretranslate.de/translate",
            data={
                "q": text,
                "source": source,
                "target": target,
                "format": "text"
            },
            timeout=5
        )
        if response.status_code == 200:
            return response.json()["translatedText"]
    except Exception as e:
        print(f"LibreTranslate error: {str(e)}")
    return None

def translate_with_local(text, source_lang="ben_Beng", target_lang="eng_Latn"):
    """Translate using local NLLB model"""
    try:
        result = local_translator(text, max_length=100)
        return result[0]['translation_text']
    except Exception as e:
        print(f"Local translation error: {str(e)}")
    return None

def translate_word(word, source_lang="bn", target_lang="en"):
    """Smart translation with caching and fallback"""
    # Check cache first
    if word in translation_cache.get(source_lang, {}):
        return translation_cache[source_lang][word]

    # Try LibreTranslate first
    translated = translate_with_libretranslate(word, source_lang, target_lang)

    # Fallback to local model if API fails
    if not translated:
        translated = translate_with_local(word, f"{source_lang}_Beng", f"{target_lang}_Latn")

    # If we got a translation, clean and cache it
    if translated:
        translated = translated.lower().strip()
        translation_cache[source_lang][word] = translated
        save_cache()
        return translated

    return None

def pos_guided_code_mix(sentence, use_translator=True, replace_nouns=True, replace_adjectives=True):
    """Generate code-mixed sentence using POS tagging"""
    tagged = bn_pos.tag(sentence)
    mixed_words = []

    for token in tagged:
        word, pos = token["word"], token["pos"]

        # Determine if we should translate this word
        should_translate = (
            (replace_nouns and pos in ["NN", "NNP"]) or
            (replace_adjectives and pos == "JJ")
        )

        if should_translate and use_translator:
            translated = translate_word(word)
            mixed_words.append(translated if translated else word)
        else:
            mixed_words.append(word)

    return " ".join(mixed_words)

def refine_with_banglat5(text):
    """Improve fluency of code-mixed text"""
    input_text = f"Improve this Bengali-English code-mixed sentence: {text}"
    input_ids = banglat5_tokenizer.encode(input_text, return_tensors="pt")

    if device != -1:
        input_ids = input_ids.to(device)

    outputs = banglat5_model.generate(input_ids, max_length=100)
    return banglat5_tokenizer.decode(outputs[0], skip_special_tokens=True)

def process_batch(df, text_column="text", batch_size=100, use_translator=True):
    """Process a DataFrame in batches"""
    results = []

    for i in tqdm(range(0, len(df), batch_size), desc="Processing batches"):
        batch = df.iloc[i:i+batch_size]

        # Process each sentence in the batch
        batch_results = []
        for sentence in batch[text_column]:
            try:
                # Generate code-mixed version
                mixed = pos_guided_code_mix(sentence, use_translator=use_translator)

                # Refine a subset for quality checking
                if i % 5 == 0:  # Refine every 5th sentence
                    refined = refine_with_banglat5(mixed)
                    batch_results.append((sentence, mixed, refined))
                else:
                    batch_results.append((sentence, mixed, None))
            except Exception as e:
                print(f"Error processing sentence: {str(e)}")
                batch_results.append((sentence, sentence, None))

        results.extend(batch_results)
        time.sleep(1)  # Rate limiting

    # Create result DataFrame
    result_df = pd.DataFrame(results, columns=["original", "code_mixed", "refined"])
    return result_df

# Example usage
if __name__ == "__main__":
    # Sample data
    sample_data = [
        "আমার বইটি টেবিলে আছে",
        "সে স্কুলে যায়",
        "এই অপ্রচলিত শব্দটি অনুবাদ করুন",
        "আমার কম্পিউটারটি নতুন",
        "তিনি ডাক্তার হিসাবে কাজ করেন"
    ]

    df = pd.DataFrame({"text": sample_data})

    print("\nStarting code mixing process...")
    result_df = process_batch(df, text_column="text", batch_size=2)

    print("\nResults:")
    print(result_df)

    # Save final cache
    save_cache()
    print("\nTranslation cache saved.")

    # Save results to CSV
    result_df.to_csv("code_mixed_results.csv", index=False)
    print("Results saved to 'code_mixed_results.csv'")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 119.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 24.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 56.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 100.5 MB/s eta 0:00:00
Loading Bengali POS tagger...
Loading translation models...

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

Starting code mixing process...

Processing batches:   0%|          | 0/3 [00:00<?, ?it/s]

Error processing sentence: tuple indices must be integers or slices, not str
Error processing sentence: tuple indices must be integers or slices, not str
Error processing sentence: tuple indices must be integers or slices, not str
Error processing sentence: tuple indices must be integers or slices, not str
Error processing sentence: tuple indices must be integers or slices, not str

Results:
                         original                      code_mixed refined
0            আমার বইটি টেবিলে আছে            আমার বইটি টেবিলে আছে    None
1                  সে স্কুলে যায়                  সে স্কুলে যায়    None
2  এই অপ্রচলিত শব্দটি অনুবাদ করুন  এই অপ্রচলিত শব্দটি অনুবাদ করুন    None
3           আমার কম্পিউটারটি নতুন           আমার কম্পিউটারটি নতুন    None
4    তিনি ডাক্তার হিসাবে কাজ করেন    তিনি ডাক্তার হিসাবে কাজ করেন    None

Translation cache saved.
Results saved to 'code_mixed_results.csv'