In [ ]:
!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Collecting datasets
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.33.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 25.2 MB/s eta 0:00:00
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 14.6 MB/s eta 0:00:00
Installing collected packages: fsspec, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.6.0 fsspec-2025.3.0

In [ ]:
from datasets import load_dataset
dataset = load_dataset("ai4bharat/sangraha", data_dir="verified/ben_Beng")

In [ ]:
# from datasets import load_dataset
# dataset = load_dataset("ai4bharat/Pralekha", data_dir="dev")

README.md: 0.00B [00:00, ?B/s]

eng_ben-00000-of-00001.parquet:   0%|          | 0.00/4.28M [00:00<?, ?B/s]

eng_guj-00000-of-00001.parquet:   0%|          | 0.00/4.48M [00:00<?, ?B/s]

eng_hin-00000-of-00001.parquet:   0%|          | 0.00/4.33M [00:00<?, ?B/s]

eng_kan-00000-of-00001.parquet:   0%|          | 0.00/4.55M [00:00<?, ?B/s]

eng_mal-00000-of-00001.parquet:   0%|          | 0.00/4.55M [00:00<?, ?B/s]

eng_mar-00000-of-00001.parquet:   0%|          | 0.00/4.57M [00:00<?, ?B/s]

eng_ori-00000-of-00001.parquet:   0%|          | 0.00/4.45M [00:00<?, ?B/s]

eng_pan-00000-of-00001.parquet:   0%|          | 0.00/4.39M [00:00<?, ?B/s]

eng_tam-00000-of-00001.parquet:   0%|          | 0.00/3.95M [00:00<?, ?B/s]

eng_tel-00000-of-00001.parquet:   0%|          | 0.00/4.68M [00:00<?, ?B/s]

eng_urd-00000-of-00001.parquet:   0%|          | 0.00/3.97M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['src_lang', 'tgt_lang', 'src_txt', 'tgt_txt'],
        num_rows: 11000
    })
})

In [ ]:
import pandas as pd

In [ ]:
df = dataset.data['train'].to_pandas()

In [ ]:
df.shape

(11000, 4)

In [ ]:
df.head()

,src_lang,tgt_lang,src_txt,tgt_txt
0,eng,ben,My dear countrymen. Namaskar. ‘Mann Ki Baat’ m...,"আমার প্রিয় দেশবাসী, নমস্কার। ‘মন কি বাত’ অর্থা..."
1,eng,ben,"My dear countrymen, Namaskar. I am feeling ver...","আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯..."
2,eng,ben,"My dear countrymen, Namaskar.\nOnce again, a v...","নতুনদিল্লি, ২৮শে মে, ২০২৩\nআমার প্রিয় দেশবাসী,..."
3,eng,ben,"My dear countrymen, Namaskar. Today, the entir...","আমার প্রিয় দেশবাসী, নমস্কার! আজ সমগ্র দেশ রাখী..."
4,eng,ben,My dearest countrymen namaskar. Before each ep...,"আমার প্রিয় দেশবাসী, নমস্কার!\nপ্রতিটি ‘মন কি ব..."

In [ ]:
# df = df[df['lang'] == 'ben']

In [ ]:
df = df[df['tgt_lang'] == 'ben']

In [ ]:
df.shape

(1000, 4)

In [ ]:
df

,src_lang,tgt_lang,src_txt,tgt_txt
0,eng,ben,My dear countrymen. Namaskar. ‘Mann Ki Baat’ m...,"আমার প্রিয় দেশবাসী, নমস্কার। ‘মন কি বাত’ অর্থা..."
1,eng,ben,"My dear countrymen, Namaskar. I am feeling ver...","আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯..."
2,eng,ben,"My dear countrymen, Namaskar.\nOnce again, a v...","নতুনদিল্লি, ২৮শে মে, ২০২৩\nআমার প্রিয় দেশবাসী,..."
3,eng,ben,"My dear countrymen, Namaskar. Today, the entir...","আমার প্রিয় দেশবাসী, নমস্কার! আজ সমগ্র দেশ রাখী..."
4,eng,ben,My dearest countrymen namaskar. Before each ep...,"আমার প্রিয় দেশবাসী, নমস্কার!\nপ্রতিটি ‘মন কি ব..."
...,...,...,...,...
995,eng,ben,Prime Minister's Office\nPM condoles demise of...,প্রধানমন্ত্রীরদপ্তর\nশ্রী এম জি বৈদ্যজির প্রয়া...
996,eng,ben,Prime Minister's Office\nPM asks people for Or...,প্রধানমন্ত্রীরদপ্তর\nজনগণকে বাড়িতে জৈব চাষ করত...
997,eng,ben,Prime Minister's Office\nPM expresses delight ...,প্রধানমন্ত্রীরদপ্তর\nমেঘালয়ে এই প্রথমবার পৌঁছে...
998,eng,ben,Prime Minister's Office\nPM condoles deaths in...,প্ৰধানমন্ত্ৰীৰ কাৰ্যালয়\nনন্দুৰবাৰত সংঘটিত প্ৰ...
999,eng,ben,Prime Minister's Office\nCredit Guarantee Sche...,প্রধানমন্ত্রীরদপ্তর\nঋণ নিশ্চয়তা প্রকল্পকে শক্...

In [ ]:
!pip install transformers sentencepiece pandas tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.6.15)

In [ ]:
!pip install langchain langchain_community langchain_huggingface torch

Requirement already satisfied: langchain in /usr/local/lib/python3.11/dist-packages (0.3.26)
Requirement already satisfied: langchain_community in /usr/local/lib/python3.11/dist-packages (0.3.26)
Requirement already satisfied: langchain_huggingface in /usr/local/lib/python3.11/dist-packages (0.3.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.66 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.67)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.8)
Requirement already satisfied: langsmith>=0.1.17 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.4.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.11.7)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.0.41)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (3.11.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (8.5.0)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.10.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: tokenizers>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (0.21.2)
Requirement already satisfied: huggingface-hub>=0.30.2 in /usr/local/lib/python3.11/dist-packages (from langchain_huggingface) (0.33.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.20.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (0.9.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (24.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.30.2->langchain_huggingface) (1.1.5)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.66->langchain) (1.33)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain_community) (1.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2025.6.15)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.66->langchain) (3.0.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community) (1.1.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.3.1)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 5.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 55.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 22.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.5 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 482.8 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 581.4 kB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 836.4 kB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 497.8 kB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 34.0 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
df['tgt_txt'][0]

'আমার প্রিয় দেশবাসী, নমস্কার। ‘মন কি বাত’ অর্থাৎ আপনাদের সঙ্গে মিলিত হওয়ার এক শুভ সুযোগ। আর যখন নিজের পরিবারের মানুষদের সঙ্গে মিলিত হই, তখন সেটা কত আনন্দের, কত তৃপ্তির। ‘মন কি বাত’এর মাধ্যমে আপনাদের সঙ্গে মিলিত হয়ে আমার এমনই অনুভব হয়, আর আজ তো আমাদের একসঙ্গে পথ চলার এক’শো আটতম পর্ব। আমাদের এখানে ১০৮ সংখ্যাটির গুরুত্ব, এর পবিত্রতা, এক গভীর অধ্যয়নের বিষয়। মালায় একশো আটটি পুঁতি, ১০৮ বার জপ, ১০৮টি পুণ্য ক্ষেত্র, মন্দিরে ১০৮টি সিঁড়ির ধাপ, ১০৮টি ঘন্টা, ১০৮ এই অঙ্কটি অসীম আস্থার সঙ্গে যুক্ত। এই কারণে ‘মন কি বাত’এর একশো আটতম পর্ব আমার জন্য আরও বিশিষ্ট হয়ে উঠেছে। এই একশো আটটি পর্বে জনগণের অংশগ্রহণের কত উদাহরণ প্রত্যক্ষ করেছি আমি, সেখান থেকে প্রেরণা পেয়েছি। এখন এই পর্যায়ে পৌঁছনোর পর আমাদের নতুন এক শুভারম্ভ করতে হবে, নতুন উদ্যমের সঙ্গে এবং দ্রুততার সঙ্গে এগিয়ে যাওয়ার সঙ্কল্প গ্রহণ করতে হবে। আর এটা কত সুখকর সংযোগ যে আগামীকালের সূর্যোদয়, ২০২৪-এর প্রথম সূর্যোদয় হবে – ২০২৪ সালে প্রবেশ ঘটে যাবে আমাদের। আপনাদের সবাইকে ২০২৪ সালের অনেক অনেক শুভেচ্ছা।\nবন্ধুরা, ‘মন কি বাত’ শুনে অনেক মানুষ আমাকে চিঠি লিখে নিজেদের স্মরণীয় মুহূর্ত ভাগ করে নিয়েছেন। এটা এক’শো চল্লিশ কোটি ভারতীয়দের শক্তি, যে এই বছর আমাদের দেশ, বিশেষ তাৎপর্যপূর্ণ অনেক সাফল্য অর্জন করেছে। এই বছরে ‘নারী শক্তি বন্দন অধিনিয়ম’ পাশ হয়েছে যার প্রতীক্ষা ছিল বহু বছর ধরে। ভারত পঞ্চম সর্ববৃহৎ অর্থনৈতিক শক্তিতে পরিণত হওয়ায় অনেক মানুষ চিঠি লিখে আনন্দ প্রকাশ করেছেন। অনেক মানুষ আমাকে জি-টুয়েন্টি সামিটের সাফল্য মনে করিয়ে দিয়েছেন। বন্ধুরা, আজ ভারতের প্রত্যেকটি কোণ বিকশিত ভারতের চিন্তায়, আত্মনির্ভতার ভাবনায় আত্মবিশ্বাসে ভরপুর রয়েছেন, আবিষ্ট রয়েছেন। ২০২৪-এ আমাদের এই চিন্তা আর অভিঘাত বজায় রাখতে হবে। দীপাবলীতে রেকর্ড বিপণন এটা প্রমাণ করে দিয়েছে যে প্রত্যেক ভারতীয় ‘ভোকাল ফর লোকাল’ মন্ত্রকে গুরুত্ব দিচ্ছে।\nবন্ধুরা, আজও বহু মানুষ চন্দ্রযান-থ্রি-এর সাফল্য নিয়ে বার্তা পাঠিয়ে চলেছেন আমাকে। আমার বিশ্বাস যে আমার মত আপনারাও আমাদের বৈজ্ঞানিক, বিশেষ করে মহিলা বৈজ্ঞানিকদের নিয়ে গর্ব অনুভব করেন।\nবন্ধুরা, এবার নাটু-নাটু অস্কার পাওয়ায় গোটা দেশ খুশিতে নেচে উঠেছে। ‘দ্য এলিফ্যান্ট হুইসপারারস’-এর সাফল্যের কথা শুনে কে খুশি হয়নি! এর মাধ্যমে সারা বিশ্ব ভারতের সৃষ্টিশীলতাকে প্রত্যক্ষ করেছে আর প্রকৃতির সঙ্গে আমাদের গভীর যোগকে বুঝেছে। এই বছর খেলাধুলোতেও আমাদের অ্যাথলীটরা দুরন্ত প্রদর্শন করেছে। এশীয়ান গেমসে আমাদের খেলোয়াড়রা এক’শো সাতটি আর এশিয়ান প্যারা-গেমসে এক’শো এগারোটি পদক জিতেছে। ক্রিকেট বিশ্বকাপে ভারতীয় খেলোয়াড়রা নিজেদের প্রদর্শনের মাধ্যমে সবার হৃদয় জয় করে নিয়েছে। অনূর্ধ্ব উনিশ T-20 ক্রিকেট বিশ্বকাপে আমাদের মহিলা ক্রিকেট দলের জয় অত্যন্ত প্রেরণাদায়ক। অনেক খেলায় খেলোয়াড়দের সাফল্য দেশের নাম উজ্জ্বল করেছে। এবার ২০২৪ সালে প্যারিস অলিম্পিক অনুষ্ঠিত হবে যার জন্য গোটা দেশ আমাদের খেলোয়াড়দের উৎসাহ বাড়াচ্ছে।\nবন্ধুরা, যখনই আমরা মিলেমিশে প্রচেষ্টা করেছি, আমাদের দেশের বিকাশ যাত্রায় তা যথেষ্ট ইতিবাচক প্রভাব ফেলেছে। আমরা ‘আজাদি কা অমৃত মহোৎসব’ এবং ‘মেরি মাটি মেরা দেশ’-এর মতো সফল অভিযানের অভিজ্ঞতা লাভ করেছি। এতে কোটি কোটি মানুষের অংশগ্রহণের সাক্ষী আমরা সবাই। ৭০ হাজার অমৃত সরোবর নির্মাণও আমাদের সম্মিলিত উপলব্ধী।\nবন্ধুরা, আমি সবসময় বিশ্বাস করে এসেছি, যে দেশ Innovation-কে গুরুত্ব দেয় না তার উন্নয়ন থেমে যায়। ভারতের Innovation Hub-এ পরিণত হওয়া এই সত্যের প্রতীক যে আমরা থামতে রাজি নই। ২০১৫ সালে আমরা গ্লোবাল ইনোভেশন ইনডেক্সে ৮১তম স্থানে ছিলাম – আজ আমাদের র\u200d্যাঙ্ক ৪০। এই বছর, ভারতে দায়ের করা পেটেন্টের সংখ্যা বেশি ছিল, যার মধ্যে প্রায় ৬০% Domestic Funds থেকে ছিল। এবার কিউএস এশিয়া ইউনিভার্সিটি র\u200c্যাঙ্কিংয়ে ভারতের সর্বোচ্চ সংখ্যক বিশ্ববিদ্যালয় স্থান পেয়েছে। আপনি যদি এই উপলব্ধিগুলির একটি তালিকা তৈরি করতে শুরু করেন তবে এটি কখনই সম্পূর্ণ হবে না। ভারতের সম্ভাবনা যে কতটা প্রভাবশালী এটা তার একটা আভাস মাত্র – দেশের এই সাফল্যগুলি থেকে, দেশের মানুষের এই উপলব্ধিগুলি থেকে অনুপ্রেরণা নিতে হবে, গর্ব করতে হবে, নতুন সংকল্প নিতে হবে। আবারও, আমি আপনাদের সবাইকে ২০২৪ সালের শুভেচ্ছা জানাই।\nআমার পরিবারবর্গ, আমরা এই মুহূর্তে ভারত সম্পর্কে সর্বত্র যে আশা এবং উদ্দীপনা নিয়ে আলোচনা করলাম – এই আশা এবং প্রত্যাশাটি খুবই ভাল। ভারত যখন বিকশিত হবে, তখন সবচেয়ে বেশি উপকৃত হবে যুবসমাজ। তবে যুবসমাজ এর থেকে তখনই লাভবান হবে যখন তারা ফিট হবে। আজকাল আমরা দেখছি যে লাইফস্টাইল সম্পর্কিত রোগগুলি সম্পর্কে কতটা আলোচনা হয়, এটি আমাদের সকলের জন্য বিশেষ করে যুবসমাজের জন্য যথেষ্ট উদ্বেগের বিষয়। এই ‘মন-কি বাত’-এর জন্য আমি আপনাদের সকলকে ফিট ইন্ডিয়া সম্পর্কিত ইনপুট পাঠাতে অনুরোধ করেছিলাম। আপনারা যে প্রতিক্রিয়া দিয়েছেন তা আমাকে খুবই উৎসাহিত করেছে। অনেক সংখ্যক স্টার্টআপও আমাকে “নমো অ্যাপে” তাদের পরামর্শ পাঠিয়েছে, তারা তাদের বিভিন্ন অনন্য প্রচেষ্টা নিয়ে আলোচনা করেছে।\nবন্ধুরা, ভারতের প্রচেষ্টার কারণে, ২০২৩ সালকে International Year of Millets হিসাবে পালন করা সম্ভব হয়েছিল। এর ফলে এই ক্ষেত্রে কাজ করা স্টার্টআপগুলি বেশ কিছু সুযোগ পেয়েছে, এর মধ্যে রয়েছে লখনউ থেকে শুরু হওয়া ‘কিরোজ ফুডস’, প্রয়াগরাজের ‘গ্র্যান্ড-মা মিলেটস’ এবং ‘নিউট্রাসিউটিক্যাল রিচ অর্গানিক ইন্ডিয়া’-এর মতো অনেক স্টার্ট-আপ। Alpino Health Foods, Arboreal এবং Keeros Food-এর সঙ্গে যুক্ত যুবসমাজ স্বাস্থ্যকর খাবারের বিকল্প সম্পর্কে নতুন নতুন উদ্ভাবন করছে। বেঙ্গালুরুর আন-বক্স হেলথের সঙ্গে যুক্ত যুবসমাজ এটাও জানিয়েছে যে কিভাবে তারা মানুষকে তাদের পছন্দের Diet বেছে নিতে সাহায্য করছে। Physical Health-এর প্রতি আগ্রহ যেভাবে বাড়ছে, তার ফলে এই ক্ষেত্রের সঙ্গে যুক্ত কোচ ও প্রশিক্ষকের চাহিদাও বাড়ছে। “JOGO টেকনোলজিস” এর মতো স্টার্টআপগুলি এই চাহিদা মেটাতে সাহায্য করছে৷\nবন্ধুরা, আজ শারীরিক স্বাস্থ্য এবং ভালো থাকা নিয়ে অনেক আলোচনা হচ্ছে, তবে এর সঙ্গেই সম্পর্কিত আরেকটি গুরুত্বপূর্ণ দিক হল মানসিক স্বাস্থ্য। আমি জেনে খুবই আনন্দিত যে মুম্বাই-ভিত্তিক স্টার্টআপ যেমন Infi Heal এবং Your Dost, মানসিক স্বাস্থ্য এবং well being-এর উন্নতির জন্য কাজ করছে। শুধু তাই নয়, আজ Artificial Intelligence-এর মতো Technology-এর জন্য ব্যবহার করা হচ্ছে। বন্ধুরা, আমি এখানে শুধুমাত্র কয়েকটি স্টার্টআপেরই নাম নিতে পারি কারণ তালিকাটি অনেক দীর্ঘ। আমি আপনাদের সকলকে অনুরোধ করব ফিট ইন্ডিয়ার স্বপ্ন বাস্তবায়নের জন্য innovative Health care Startups সম্পর্কে আমাকে অবশ্যই লিখতে থাকুন। আমি আপনার সঙ্গে শারীরিক স্বাস্থ্য এবং মানসিক স্বাস্থ্য সম্পর্কে বিশিষ্ট ব্যক্তিদের অভিজ্ঞতাও শেয়ার করতে চাই ।\nএই প্রথম message-টি সদগুরু জগ্গি বাসুদেবজীর।\nতিনি fitness, বিশেষত, fitness of the mind, অর্থাৎ মানসিক স্বাস্থ্য সম্পর্কে নিজের মতামত ব্যক্ত করেছেন।\n** অডিও **\n“মন কি বাতের” এই পর্বে মানসিক স্বাস্থ্য নিয়ে কথা বলতে পারাটা আমার সৌভাগ্য। মানসিক রোগ এবং আমাদের স্নায়ুতন্ত্র সরাসরি সম্পর্কিত। আমদের স্নায়ুতন্ত্র কতটা সজাগ, সচল এবং ঝামেলা মুক্ত থাকবে তা নির্ধারণ করে আমরা নিজেদের ভেতরে কতটা আনন্দ অনুভব করছি তার ওপর। আমরা যাকে বলি শান্তি, প্রেম, আনন্দ, যন্ত্রণা, বিষণ্নতা, উচ্ছ্বাস সবগুলোরই একটি Chemical Neurological ভিত্তি রয়েছে। ফার্মাকোলজি মূলত বাইরে থেকে chemicals যোগ করে শরীরের মধ্যে Chemical imbalance ঠিক করার চেষ্টা করে। মানসিক রোগগুলি এইভাবেই সামাল দেওয়া হয়। কিন্তু আমাদের অবশ্যই উপলব্ধি করতে হবে যে বাইরে থেকে ক্যামিক্যাল গ্রহণ করা প্রয়োজন তখনই যখন কেউ গুরুতর পরিস্থিতিতে রয়েছে। শরীরের অভ্যন্তরে মনের স্বাস্থ্য রক্ষার জন্য বা সুষম রাসায়নিক ব্যবস্থার জন্য, শান্তি, আনন্দ, সুখের উপযোগী রাসায়নিক ব্যবস্থার জন্য কাজ করা, প্রত্যেকের জীবনের, একটা সমাজের সাংস্কৃতিক চর্যার, বিশ্বজুড়ে প্রতিটি দেশের এবং সামগ্রিকভাবে মানবতার অঙ্গ করে তুলতে হবে। এটা খুব গুরুত্বপূর্ণ যে আমরা বুঝি যে আমাদের মানসিক স্বাস্থ্য, আমাদের মনের ভারসাম্য একটি Fragile Privilege – এগুলোকে রক্ষা করতে হবে, লালন করতে হবে আমাদের। এই লক্ষ্যে যোগ পদ্ধতিতে নানা স্তরের ক্রিয়ার সংস্থান আছে। আত্তীকরণ করার  এমন পদ্ধতি আছে, যা নিজেদের রসায়নে ভারসাম্য আনতে, এবং নিজেদের স্নায়ুব্যবস্থায় বিশেষ একটা প্রশান্তি আনতে, সাধারণ ক্রিয়া হিসাবে অভ্যাস করতে পারে মানুষ। অন্তরের সুস্থতা আনার প্রযুক্তি যোগবিজ্ঞান হিসাবে পরিচিত। আসুন এটার চর্চা করি।\nসাধারণত সদগুরুজি এরকম উত্তম উপায়ে নিজের কথাকে সামনে রাখার জন্যই পরিচিত।\nআসুন, এবার আমরা জনপ্রিয় ক্রিকেট খেলোয়াড় হরমনপ্রীত কৌর জির কথা শুনি।\n** অডিও **\nনমস্কার। আমি আমার দেশবাসীকে “মন কি বাত” এর মাধ্যমে কিছু বলতে চাই। মাননীয় প্রধানমন্ত্রী শ্রী নরেন্দ্র মোদী জির ফিট ইন্ডিয়ার প্রয়াস, আমায় নিজের fitness মন্ত্র আপনাদের সকলের সঙ্গে share করার জন্য উৎসাহিত করেছে। আপনাদের সবাইকে আমার প্রথম suggestion এটাই যে ‘one cannot out-train a bad diet’ . অর্থাৎ আপনারা কি খান আর কখন খান এই ব্যাপারে আপনাদের অনেক সাবধানতা অবলম্বন করতে হবে। সম্প্রতি মাননীয় প্রধানমন্ত্রী মোদী জি সবাইকে খাবার জন্য encourage করেছেন। যা immunity বাড়ায় আর টেকসই কৃষিতে সাহায্য করবে এবং বাজরা হজম করাও সহজ। Regular exercise এবং ৭ঘণ্টার সম্পূর্ণ ঘুম শরীরের জন্য খুবই প্রয়োজনীয় আর ফিট থাকতেও সাহায্য করে। এর জন্য অনেক discipline এবং consistency-এরও দরকার। যখন আপনি এর ফল লাভ করতে শুরু করবেন তখন আপনি নিজেই প্রত্যেকদিন এক্সারসাইজ করা শুরু করে দেবেন। আমায় আপনাদের সবার সঙ্গে কথা বলার এবং নিজের ফিটনেস মন্ত্র share করার সুযোগ করে দেওয়ার জন্য মাননীয় প্রধানমন্ত্রীজিকে অনেক ধন্যবাদ।\nহরমনপ্রীতজির মতো প্রতিভাবান খেলোয়াড়ের কথা, নিশ্চিতরূপে আপনাদের সবাইকে অনুপ্রাণিত করবে।\nআসুন, গ্র্যান্ডমাস্টার Viswanathan Anand জির কথা শুনি। আমরা সবাই জানি যে ওঁর খেলা ‘ দাবা ‘ এর জন্য মেন্টাল ফিটনেস কতটা গুরুত্বপূর্ণ।\n** অডিও **\nনমস্কার। আমি Viswanathan Anand। আপনারা আমায় chess খেলতে দেখেছেন এবং প্রায়ই আমায় জিজ্ঞেস করা হয় আমার ফিটনেস রুটিন সম্বন্ধে। এখন দাবায় প্রচুর পরিমাণে একাগ্রতা ও ধৈর্যের দরকার, তাই আমি নিজেকে ফিট এবং কর্মতৎপর রাখার জন্য এগুলি করি। আমি যোগাভ্যাস করি সপ্তাহে দু’বার, cardio করি সপ্তাহে দু’বার। আমি flexibility, stretching, weight training এর উপর focus করি এবং প্রত্যেক সপ্তাহে অন্তত একদিন ছুটি নেবার চেষ্টা করি।\nএই সব কিছুই দাবার জন্য অত্যন্ত গুরুত্বপূর্ণ। ছয়-সাত ঘন্টা তীব্র মানসিক পরিশ্রম করার মত স্ট্যামিনা আপনার থাকতে হবে। পাশাপাশি আরামদায়কভাবে বসার মত নমনীয়তা থাকা প্রয়োজন। দাবা খেলা মানে কোন একটি সমস্যায় মনঃসংযোগ করা, সে ক্ষেত্রে নিঃশ্বাস প্রশ্বাস নিয়ন্ত্রণ করার ক্ষমতা, শান্ত, স্থির থাকতে সাহায্য করে। “মন কি বাত”-এর সকল শ্রোতার প্রতি আমার ফিটনেস টিপস্\u200c হল, প্রশান্ত থাকা এবং সামনে যে কাজ রয়েছে তাতে শান্ত ভাবে মনঃসংযোগ করা। আমার কাছে সবচেয়ে গুরুত্বপূর্ণ ও সর্বোত্তম ফিটনেস টিপ হচ্ছে রাতে ভালো করে ঘুমনো। রাতে চার-পাঁচ ঘণ্টা ঘুমনোর অভ্যাস করবেন না। আমার মতে ন্যূনতম সাত বা আট ঘন্টার ঘুম আবশ্যক। কাজেই আমাদের যথাসম্ভব চেষ্টা করতে হবে রাতের ভালো ঘুমের জন্য, কারণ তখনই পরের দিনটা আপনারা প্রশান্ত মনে কাটাতে পারবেন, আবেগ প্রবণ হয়ে কোন হঠকারী সিদ্ধান্ত নেবেন না এবং আপনাদের আবেগকে আপনারা নিয়ন্ত্রণ করতে পারবেন। তাই আমার কাছে ঘুমই হল সবচেয়ে গুরুত্বপূর্ণ ফিটনেস টিপ।\n \nআসুন এবার অক্ষয় কুমার জির কথা শুনি।\n** অডিও **\nনমস্কার, আমি অক্ষয় কুমার। সবার প্রথমে আমি আমাদের প্রিয় প্রধানমন্ত্রীজিকে অনেক ধন্যবাদ জানাই যে তাঁর “মন কি বাতে” আমিও আমার মনের কথা আপনাদের শোনানোর একটা ছোট্ট সুযোগ পেলাম। আপনারা তো জানেন যে আমি ফিটনেস্\u200c-এর জন্য যতটা প্যাশনেট তার থেকেও অনেক বেশি প্যাশনেট প্রাকৃতিক পদ্ধতি অবলম্বন করে ফিট থাকার ব্যাপারে। ফ্যান্সি জিমের থেকেও আমি বেশি পছন্দ করি বাইরে সাঁতার কাটা, ব্যাডমিন্টন খেলা, সিঁড়ি দিয়ে ওঠা, মুগুরের সাহায্যে ব্যায়াম করা, স্বাস্থ্যকর খাওয়া দাওয়া করা। যেমন আমার মনে হয় শুদ্ধ ঘি যদি সঠিক মাত্রায় খাওয়া যায় তাহলে তা আমাদের জন্য উপকারী। কিন্তু আমি দেখি অনেক ইয়াং ছেলে মেয়ে মোটা হয়ে যাবেন এই আশঙ্কায় ঘি খান না। আমাদের ফিটনেসের জন্য কোনটা ভালো আর কোনটা খারাপ সেটা বুঝে নেওয়া অত্যন্ত জরুরি। আপনারা ডাক্তারদের পরামর্শ নিয়ে নিজেদের লাইফস্টাইল বদলান, কোন ফিল্মস্টারের বডি দেখে নয়। অভিনেতাদের স্ক্রিনে যেমন দেখতে লাগে, তেমনটা তারা বাস্তবে অনেক সময়ই হন না। অনেক ধরনের ফিল্টার, স্পেশাল এফেক্ট ব্যবহার করা হয়, আর আমরা সেগুলি দেখে নিজেদের শরীরে বদল আনার জন্য ভুল শর্টকাট ব্যবহার করা শুরু করে দিই। আজকাল এত এত মানুষ স্টেরয়েড নিয়ে সিক্স প্যাক, এইট প্যাকের জন্য ছুটছেন। এই ধরনের শর্টকাটে শরীর ওপর ওপর ফুলে যায় কিন্তু ভেতরে ফাঁপা, অপুষ্টই রয়ে যায়। আপনারা মনে রাখবেন যে শর্টকাট ক্যান কাট ইয়োর লাইফ শর্ট, অর্থাৎ শর্টকাট আপনাদের আয়ু কমিয়ে দিতে পারে। আপনাদের শর্টকাট নয়, প্রয়োজন লং লাস্টিং ফিটনেস।\nবন্ধুরা fitness একরকমের সাধনা। Instant coffee বা দু’মিনিটের noodles নয়। নতুন বছরে নিজের কাছে শপথ নাও, no chemicals, no shortcut; শরীর চর্চা, যোগাভ্যাস, ভালো খাবার, ঠিক সময় ঘুমানো, সামান্য meditation আর তার সঙ্গে সবচেয়ে জরুরি, তোমায় যেমন’ই দেখতে হোক সেটাই আনন্দের সঙ্গে accept করো। আজকে থেকে filter ওয়ালা লাইফ নয়, fitter life নিয়ে বাঁচো। Take care! জয় মহাকাল।\nএই সেক্টরে আরো অনেক Start-ups আছে, এজন্য আমি ভাবলাম একজন যুব Start-up founder-এর সঙ্গেও আলোচনা করা যাক, যিনি এই জায়গায় খুব ভালো কাজ করছেন।\n** অডিও **\nনমস্কার, আমার নাম রিশভ মালহোত্রা, আমি বেঙ্গালুরুতে থাকি। “মন-কি-বাতে” ফিটনেস নিয়ে আলোচনা হচ্ছে জেনে আমার খুব আনন্দ হচ্ছে। আমি নিজে fitness-এর জগতে belong করি, আর বেঙ্গালুরুতে আমাদের একটা Start-up আছে, যার নাম ‘তাগড়া রহো’। আমাদের এই Start-up তৈরি করা হয়েছে ভারতের ঐতিহ্যময় ব্যায়ামকে সামনে আনার জন্যে। ভারতের পরম্পরাগত শরীর চর্চায় একটা ভারি অদ্ভুত কসরত আছে যার নাম ‘গদা-ব্যায়াম’; আর আমাদের পুরো focus থাকে গদা এবং মুগুর’এর ব্যায়ামের ওপর। লোকে জেনে অবাক হয় যে গদা নিয়ে সমস্ত training আপনি কি করে করেন! আমি এটুকুই বলতে চাইবো যে গদা ব্যায়াম হাজার হাজার বছরের পুরনো কসরত, আর এটা হাজার হাজার বছর ধরেই ভারতে চলে আসছে। আপনারা এটা ছোট বড় নানা আখড়ায় নিশ্চই দেখেছেন, আর আমাদের start-up এর মাধ্যমে আমরা এটাকে আধুনিক form-এ ফিরিয়ে এনেছি। সারা দেশ থেকে আমরা অনেক ভালোবাসা পেয়েছি, খুব ভালো response পেয়েছি। “মন কি বাতের” মধ্যে দিয়ে আমি এটুকু বলতে চাই যে এটা ছাড়াও ভারতে এমন অনেক পুরনো শরীর চর্চার কৌশল রয়েছে, Health আর fitness এর সঙ্গে যুক্ত নিয়মকানুন আছে, যা আমাদের আপন করে নেয়া উচিত, এবং সারা দুনিয়ায় সেটা শেখানো উচিত। আমি fitness জগতের লোক, তাই আপনাদের একটা personal tip দিতে চাই। গদা ব্যায়ামের মধ্যে দিয়ে আপনি আপনার শক্তি, শারীরিক ক্ষমতা, posture এবং breathing’কে ঠিক করে নিতে পারবেন, তাই গদা ব্যায়ামকে জীবনের অঙ্গ করে নিন ও একে এগিয়ে নিয়ে যান। জয় হিন্দ।\n \nবন্ধুরা, প্রত্যেকে নিজের মতামত তুলে ধরেছেন কিন্তু সবার একটাই মন্ত্র — Healthy থাকুন, fit থাকুন। ২০২৪-এর শুরুর মূহুর্তে আপনার কাছে নিজের fitness-এর চেয়ে বড় সংকল্প আর কি হতে পারে!\nআমার পরিবারবর্গ, কিছুদিন আগে কাশীতে একটা এক্সপেরিমেন্ট হয়েছিল যার কথা আমি “মন কী বাতের” শ্রোতাদের অবশ্যই বলতে চাই। আপনারা জানেন যে কাশী তামিল সঙ্গমম্\u200c-এ অংশগ্রহণ করতে তামিলনাড়ু থেকে হাজার-হাজার মানুষ কাশী পৌঁছেছিলেন। ওঁদের সঙ্গে কথা বলার জন্যে আমি আর্টিফিশিয়াল ইন্টেলিজেন্স এ. আই. টুল ভাষিণীর সর্বসমক্ষে প্রথম ব্যবহার করি। আমি মঞ্চ থেকে হিন্দিতে সম্বোধন করছিলাম কিন্তু এ. আই. টুল ভাষিণীর জন্য ওখানে উপস্থিত তামিলনাড়ুর ব্যক্তিরা সেই সম্বোধনই ঠিক সেই সময়েই তামিল ভাষায় শুনতে পাচ্ছিলেন।\nকাশী তামিল সঙ্গমম্\u200c-এ উপস্থিত মানুষজনকে প্রযুক্তির এই ব্যবহারের পরে বেশ উৎসাহিত লাগছিল। ওই দিন দূর নেই যেদিন কোন একটি ভাষায় সম্বোধন করা হবে এবং জনতা real time-এ সেই ভাষণ নিজের ভাষায় শুনতে পাবে। এটা ফিল্মের ক্ষেত্রেও দেখা যাবে যখন সাধারণ মানুষ সিনেমা হলে এ আই-এর সাহায্যে real time translation শুনতে পাবে। আপনারা আন্দাজ করতে পারছেন যে যখন এই technology আমাদের স্কুলে, আমাদের হাসপাতালে, আমাদের আদালতে ব্যাপক রুপে ব্যবহৃত হবে তখন কী বিশাল পরিবর্তন আসবে। আমি আজকের যুব প্রজন্মের কাছে অনুরোধ করব যে real time translation-এর সঙ্গে যুক্ত AI tools-গুলিকে তারা যেন আরও explore করে এবং ১০০% full proof বানায়।\nবন্ধুরা, এই পরিবর্তনশীল সময়ে আমাদের নিজেদের ভাষাগুলিকে বাঁচাতেও হবে এবং তাদের বৃদ্ধিসাধনও করতে হবে। এখন আমি আপনাদের ঝাড়খন্ডের একটি আদিবাসী গ্রামের কথা বলতে চাই। এই গ্রাম তাদের বাচ্চাদের নিজেদের মাতৃভাষায় শিক্ষা দেওয়ার লক্ষ্যে একটি অভিনব পদক্ষেপ নিয়েছে। গড়বা জেলার মংলো গ্রামে বাচ্চাদের কুড়ুখ ভাষায় শিক্ষা দেওয়া হচ্ছে। এই স্কুলের নাম কার্তিক ওরাঁও আদিবাসী কুড়ুখ স্কুল। এই স্কুলে ৩০০ আদিবাসী বাচ্চা পড়ে। কুড়ূখ ভাষা, ওরাঁও আদিবাসী জনজাতির মাতৃভাষা। কুড়ুখ ভাষার নিজস্ব লিপিও আছে যা তোলং সিকি নামে পরিচিত। এই ভাষাটি ধীরে ধীরে বিলুপ্ত হয়ে যাচ্ছিল যাকে বাঁচানোর জন্য এই জনজাতি নিজেদের ভাষায় বাচ্চাদের শিক্ষা দেওয়ার সিদ্ধান্ত নেয়। এই স্কুলটির প্রতিষ্ঠাতা অরবিন্দ ওরাঁও বলেন যে আদিবাসী বাচ্চাদের ইংরেজি ভাষা নিয়ে সমস্যা হত, তাই তিনি গ্রামের বাচ্চাদের নিজেদের মাতৃভাষায় পড়ানো শুরু করেন। ওঁর এই প্রচেষ্টায় আরও ভাল ফল পাওয়া শুরু হওয়ার পর বাকি গ্রামবাসীরাও ওঁর সঙ্গে যুক্ত হয়ে যান। নিজেদের ভাষায় পড়াশোনা করার কারণে বাচ্চাদের শেখার গতিও বেড়ে যায়। আমাদের দেশে বহু বাচ্চা ভাষাগত সমস্যার জন্য পড়াশোনা মাঝপথে ছেড়ে দিত। এই ধরণের অসুবিধেগুলি দূর করতে নতুন রাষ্ট্রীয় শিক্ষা নীতি থেকেও সাহায্য পাওয়া যাচ্ছে। আমাদের প্রচেষ্টা এই যে, ভাষা – কোন বাচ্চার শিক্ষা ও অগ্রগতির ক্ষেত্রে যেন না বাধা হয়ে দাঁড়ায়।\nবন্ধুরা, যুগে যুগে আমাদের ভারতভূমিকে ভারতের গুণী কন্যারা গৌরবান্বিত করেছে। সাবিত্রী বাঈ ফুলেজী এবং রানী বেলু নাচিয়ারজী দেশের এমনই দুই মহান কন্যা। তাঁদের ব্যক্তিত্ব এমনই প্রকাশ স্তম্ভের মত, যে সর্ব যুগে নারী শক্তিদের এগিয়ে চলার রাস্তা দেখায়। আজ থেকে আর কয়েকদিন পরেই, তেসরা জানুয়ারি আমরা এঁদের জন্মজয়ন্তী পালন করবো। সাবিত্রীবাঈ ফুলেজীর নাম স্মরণে আসতেই শিক্ষা এবং সমাজ সংস্কারের ক্ষেত্রে তাঁর যোগদানের কথাই মনে আসে। তিনি বরাবর মহিলা এবং বঞ্চিতদের শিক্ষার জন্যে সোচ্চার ছিলেন। তিনি সমসময়ের থেকে অনেকটাই এগিয়ে ছিলেন এবং সেই সময়ের ভুল প্রথার বিরুদ্ধে মুখর ছিলেন। শিক্ষার মাধ্যমেই সমাজের সশক্তিকরণ সম্ভব, এই ছিল তাঁর দৃঢ় বিশ্বাস। মহাত্মা ফুলেজীর সঙ্গে তিনি মেয়েদের জন্যে বেশ কয়েকটি স্কুল নির্মাণ করেছিলেন। তাঁর কবিতাগুলি মানুষকে সচেতনতার এবং আত্মবিশ্বাসে ভরিয়ে তুলতো। মানুষ একে অপরকে সাহায্য করবে এবং প্রকৃতির প্রতিও দায়িত্বশীল হবে, এমনটাই আশা করতেন তিনি মানুষের কাছে। তিনি কতটা দয়ালু ছিলেন, তা শব্দের মাধ্যমে প্রকাশ করা অসম্ভব। মহারাষ্ট্রে যখন আকাল এসেছিল, তখন সাবিত্রী বাঈ এবং মহাত্মাফুলেজী তাঁদের দরজা সাহায্যপ্রার্থীদের জন্যে খুলে দিয়েছিলেন। সামাজিক ন্যায়ের ক্ষেত্রে এমন উদাহরণ কমই দেখতে পাওয়া যায়। যখন সেখানে প্লেগের ভয় দেখা দিল, সেসময়ে তাঁরা মানুষের সেবায় নিজেদের নিয়োজিত করলেন। এর ফলে তাঁরা নিজেরাও প্লেগে আক্রান্ত হয়েছিলেন। মানবতার প্রতি উতসর্গীকৃৎ তাঁদের জীবন আমাদের আজও প্রাণিত করে।\nবন্ধুরা, বিদেশি শাসনের বিরুদ্ধে লড়াই করেছেন যাঁরা, সেই মহান ব্যক্তিত্বদের মধ্যে রানী বেলু নাচিয়ার-ও একটি নাম। আমার তামিলনাড়ুর ভাই বোনেরা আজও তাঁকে বীরা মঙ্গাই অর্থাৎ বীর নারী নামেই স্মরণ করে। ইংরেজদের বিরুদ্ধে সাহসীকতার সঙ্গে লড়াই করে রানী বেলু নাচিয়ারজী যে পরাক্রম দেখিয়েছেন, তা আমাদের প্রেরণা যোগায়। ইংরেজরা শিবগঙ্গা সাম্রাজ্যে হামলা করে সেখানকার রাজা, তাঁর স্বামীকে হত্যা করে। রানীজী এবং তাঁর কন্যা কোনক্রমে সেখান থেকে পলায়ন করেন। তিনি সংগঠন গড়ে তুলতে এবং মুরুদু ব্রাদার্স অর্থাৎ নিজের কমান্ডারদের সঙ্গে সেনাবাহিনী তৈরি করতে কয়েক বছর অতিবাহিত করেন। তিনি সম্পূর্ন প্রস্তুতির সঙ্গে ইংরেজদের বিরুদ্ধে যুদ্ধ শুরু করেন এবং সাহসিকতা ও সংকল্প শক্তির সঙ্গে লড়াই করেন। রানী বেলু নাচিয়ারের নাম তাঁদের মধ্যে আসে, যাঁরা সম্পূর্ন মহিলাদের নিয়ে সেনাদের গ্রুপ তৈরী করেছিলেন। আমি এই দুই বীরাঙ্গনার প্রতি শ্রদ্ধা জানাই।\nআমার পরিবারবর্গ, গুজরাটে ডায়রার একটা রীতি আছে। সারারাত হাজারো মানুষ ডায়রাতে জড়ো হয়ে বিনোদনের মধ্যে দিয়ে জ্ঞান অর্জন করে। এই ডায়রাতে লোকসংগীত, লোকসাহিত্য এবং হাস্যরসের ত্রিসঙ্গম সবার মনকে আনন্দে ভরিয়ে দেয়। এই ডায়রার একজন প্রসিদ্ধ শিল্পী হলেন ভাই জগদীশ ত্রিবেদীজী। ভাই জগদীশ ত্রিবেদীজী প্রায় ৩০ বছরেরও বেশি সময় ধরে কৌতুক শিল্পী হিসাবে তাঁর প্রভাব প্রতিষ্ঠা করেছেন। সম্প্রতি আমি ভাই জগদীশ ত্রিবেদীজীর কাছ থেকে একটি চিঠি পেয়েছি এবং এঁর সঙ্গে তিনি তাঁর একটি বইও পাঠিয়েছেন। বইটির নাম হল – Social Audit of Social Service । এই বইটি খুবই অনন্য। এই বইটিতে হিসেব নিকেষ রয়েছে, এই বইটি একধরণের Balance Sheet। গত ৬ বছরে ভাই জগদীশ ত্রিবেদীজী কোন কোন অনুষ্ঠান থেকে কত আয় করেছেন এবং কোথায় কোথায় খরচা করেছেন তার সম্পূর্ণ লিখিত হিসাব বইটিতে রয়েছে। এই Balance Sheet, এই জন্য অনন্য কারণ উনি ওঁর সম্পূর্ণ আয়, এক এক টাকা সমাজের জন্য, School, Hospital, Library, বিশেষ ভাবে সক্ষম মানুষদের সঙ্গে যুক্ত সংস্থায়, সমাজসেবার কাজে খরচ করেছেন – এই পুরো ৬ বছরের হিসাব রয়েছে। যেমন বইটির এক জায়গায় লেখা আছে, ২০২২ সালে তিনি তাঁর অনুষ্ঠান থেকে প্রাপ্ত ২ কোটি পঁয়ত্রিশ লক্ষ ঊনআশি হাজার ছয়শ চুয়াত্তর টাকা আয় করেছেন। আর এই ২ কোটি পঁয়ত্রিশ লাখ ঊনআশি হাজার ছয়শ চুয়াত্তর টাকা তিনি খরচ করেছেন School, Hospital, Library তে। এক পয়সাও নিজের কাছে রাখেননি। আসলে এর পিছনেও একটা মজার ঘটনা আছে। এমনটা হয়েছিল যে একবার ভাই জগদীশ ত্রিবেদীজী বলেছিলেন যে তিনি ২০১৭ সালে যখন তাঁর ৫০ বছর বয়স হবে, তারপরে তিনি তাঁর অনুষ্ঠান থেকে অর্জিত আয় ঘরে নেবেন না, বরং সমাজে ব্যয় করবেন। ২০১৭ সালের পর থেকে এখনও পর্যন্ত, তিনি প্রায় পৌনে ন’কোটি টাকা আলাদা আলাদা সামাজিক ক্ষেত্রে ব্যয় করেছেন। একজন হাস্য কৌতুক শিল্পী, তাঁর কথা দিয়ে, সবাইকে হাসতে বাধ্য করেন। কিন্তু তিনি যে নিজের ভিতর কতটা সংবেদনশীলতাকে বাঁচিয়ে রেখেছেন, তা ভাই জগদীশ ত্রিবেদীজীর জীবন থেকে স্পষ্ট। জানলে অবাক হবেন যে তাঁর PHD-র তিনটি ডিগ্রিও রয়েছে। তিনি ৭৫টি বই লিখেছেন, যার মধ্যে অনেকগুলি বই যথাযথ সম্মানও পেয়েছে। তিনি তাঁর সামাজিক কাজের জন্য অনেক পুরস্কারেও ভূষিত হয়েছেন। আমি ভাই জগদীশ ত্রিবেদীজীকে তাঁর সামাজিক কাজের জন্য অনেক শুভকামনা জানাই।\nআমার পরিবারবর্গ, অযোধ্যায় রামমন্দিরকে কেন্দ্র করে সারা দেশে উৎসাহ ও উত্তেজনার সঞ্চার হয়েছে। দেশবাসী নিজেদের ভাবনা বিভিন্ন ভাবে ব্যক্ত করছেন। আপনারা দেখে থাকবেন বিগত কিছুদিন ধরে শ্রীরাম ও অযোধ্যাকে কেন্দ্র করে বিভিন্ন গান ও ভজনের রচনা করা হয়েছে।                                                                                                                                                                               

In [ ]:
!pip install langchain langchain_community langchain-core langchain-huggingface transformers huggingface-hub numpy scikit-learn

Collecting langchain
  Downloading langchain-0.3.26-py3-none-any.whl.metadata (7.8 kB)
Collecting langchain_community
  Downloading langchain_community-0.3.27-py3-none-any.whl.metadata (2.9 kB)
Collecting langchain-core
  Downloading langchain_core-0.3.67-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain-huggingface
  Downloading langchain_huggingface-0.3.0-py3-none-any.whl.metadata (996 bytes)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.0)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.11/dist-packages (0.33.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Collecting langchain-text-splitters<1.0.0,>=0.3.8 (from langchain)
  Downloading langchain_text_splitters-0.3.8-py3-none-any.whl.metadata (1.9 kB)
Collecting langsmith>=0.1.17 (from langchain)
  Downloading langsmith-0.4.4-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.11.7)
Collecting SQLAlchemy<3,>=1.4 (from langchain)
  Downloading sqlalchemy-2.0.41-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (3.11.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain_community) (8.5.0)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain_community)
  Downloading pydantic_settings-2.10.1-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.1-py3-none-any.whl.metadata (9.4 kB)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting packaging<25,>=23.2 (from langchain-core)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core) (4.14.0)
Requirement already satisfied: tokenizers>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from langchain-huggingface) (0.21.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub) (1.1.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.20.1)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith>=0.1.17->langchain)
  Downloading orjson-3.10.18-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 2.8 MB/s eta 0:00:00
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from langsmith>=0.1.17->langchain)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting zstandard<0.24.0,>=0.23.0 (from langsmith>=0.1.17->langchain)
  Downloading zstandard-0.23.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain_community)
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (2025.6.15)
Collecting greenlet>=1 (from SQLAlchemy<3,>=1.4->langchain)
  Downloading greenlet-3.2.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.16.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.3.1)
Downloading langchain-0.3.26-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 15.0 MB/s eta 0:00:00
Downloading langchain_community-0.3.27-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 21.1 MB/s eta 0:00:00
Downloading langchain_core-0.3.67-py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.2/440.2 kB 10.4 MB/s eta 0:00:00
Downloading langchain_huggingface-0.3.0-py3-none-any.whl (27 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.1-py3-none-any.whl (8.1 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langchain_text_splitters-0.3.8-py3-none-any.whl (32 kB)
Downloading langsmith-0.4.4-py3-none-any.whl (367 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 367.7/367.7 kB 22.1 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 1.3 MB/s eta 0:00:00
Downloading pydantic_settings-2.10.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 2.3 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.41-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 63.7 MB/s eta 0:00:00
Downloading greenlet-3.2.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (585 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.5/585.5 kB 34.7 MB/s eta 0:00:00
Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.5 MB/s eta 0:00:00
Downloading orjson-3.10.18-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 9.9 MB/s eta 0:00:00
Downloading python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 4.1 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading zstandard-0.23.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 72.4 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: zstandard, python-dotenv, packaging, orjson, mypy-extensions, jsonpointer, httpx-sse, greenlet, typing-inspect, SQLAlchemy, requests-toolbelt, marshmallow, jsonpatch, pydantic-settings, langsmith, dataclasses-json, langchain-core, langchain-text-splitters, langchain-huggingface, langchain, langchain_community
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
Successfully installed SQLAlchemy-2.0.41 dataclasses-json-0.6.7 greenlet-3.2.3 httpx-sse-0.4.1 jsonpatch-1.33 jsonpointer-3.0.0 langchain-0.3.26 langchain-core-0.3.67 langchain-huggingface-0.3.0 langchain-text-splitters-0.3.8 langchain_community-0.3.27 langsmith-0.4.4 marshmallow-3.26.1 mypy-extensions-1.1.0 orjson-3.10.18 packaging-24.2 pydantic-settings-2.10.1 python-dotenv-1.1.1 requests-toolbelt-1.0.0 typing-inspect-0.9.0 zstandard-0.23.0

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

llm = HuggingFacePipeline.from_model_id(
    model_id='google/gemma-3-4b-it',
    task='text-generation',
    pipeline_kwargs=dict(
        temperature=0.5,
        max_new_tokens=3000
    )
)

model = ChatHuggingFace(llm=llm)

prompt = PromptTemplate(
    input_variables=["input_text"],
    template="""
You are a language expert skilled in Bengali-English code-mixing (Benglish). Your task is to rewrite the given Bengali sentence by naturally blending 20% to 40% English words into it, while keeping the sentence grammatically correct and semantically equivalent to the original. Follow these rules strictly:

1. The meaning and overall structure (syntax) of the original Bengali sentence must remain unchanged.
2. Replace or insert English words that are **commonly used or acceptable** in informal spoken or written BenEnglish (e.g., school, problem, plan, idea, smart, important, etc.).
3. Ensure the resulting sentence feels **natural, fluent, and idiomatic** to a bilingual Bengali speaker who frequently switches between Bengali and English in daily conversation.
4. Do **not** translate the entire sentence to English. The code-mixed version should still primarily be in Bengali (60%–80%) with the remaining 20%–40% in English.
5. Avoid awkward or forced insertions; prefer English words for abstract nouns, tech terms, academic terms, modern expressions, etc.

Example Input:
আমি আগামীকাল একটি গুরুত্বপূর্ণ মিটিংয়ে অংশগ্রহণ করব।

Example Output:
আমি কাল একটা important মিটিং attend করব।

Now, code-mix this Bengali sentence as per the instructions:
{input_text}
"""
)

parser = StrOutputParser()

chain = prompt | model | parser

result = chain.invoke({'input_text': """
বইমেলায় অনেক মানুষ এসেছে। নতুন নতুন বই দেখা যাচ্ছে। কিছু লেখকের সঙ্গে পরিচয়ও হলো। আমি কয়েকটি গল্পের বই কিনলাম। বন্ধুদের সঙ্গে দেখা করে আমরা একসঙ্গে খেতে গেলাম।
"""})

print(result)

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.64G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Device set to use cpu

<bos><start_of_turn>user
You are a language expert skilled in Bengali-English code-mixing (Benglish). Your task is to rewrite the given Bengali sentence by naturally blending 20% to 40% English words into it, while keeping the sentence grammatically correct and semantically equivalent to the original. Follow these rules strictly:

1. The meaning and overall structure (syntax) of the original Bengali sentence must remain unchanged.
2. Replace or insert English words that are **commonly used or acceptable** in informal spoken or written BenEnglish (e.g., school, problem, plan, idea, smart, important, etc.).
3. Ensure the resulting sentence feels **natural, fluent, and idiomatic** to a bilingual Bengali speaker who frequently switches between Bengali and English in daily conversation.
4. Do **not** translate the entire sentence to English. The code-mixed version should still primarily be in Bengali (60%–80%) with the remaining 20%–40% in English.
5. Avoid awkward or forced insertions; prefer English words for abstract nouns, tech terms, academic terms, modern expressions, etc.

Example Input:
আমি আগামীকাল একটি গুরুত্বপূর্ণ মিটিংয়ে অংশগ্রহণ করব।

Example Output:
আমি কাল একটা important মিটিং attend করব।

Now, code-mix this Bengali sentence as per the instructions:

বইমেলায় অনেক মানুষ এসেছে। নতুন নতুন বই দেখা যাচ্ছে। কিছু লেখকের সঙ্গে পরিচয়ও হলো। আমি কয়েকটি গল্পের বই কিনলাম। বন্ধুদের সঙ্গে দেখা করে আমরা একসঙ্গে খেতে গেলাম।<end_of_turn>
<start_of_turn>model
বইমেলায় অনেক মানুষ এসেছে। নতুন নতুন বই দেখা যাচ্ছে, এটা really amazing! কিছু লেখকের সঙ্গে পরিচয়ও হলো, তাদের সাথে conversation খুবই interesting ছিল। আমি কয়েকটি গল্পের বই কিনলাম, এগুলো আমার জন্য quite useful হবে। বন্ধুদের সঙ্গে দেখা করে আমরা একসঙ্গে খেতে গেলাম, একটা plan করিছিলাম।

In [ ]:
from langchain_huggingface import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
import torch
import os
import pandas as pd # Import pandas
from tqdm import tqdm # Import tqdm

# ⚙️ Config
MODEL_NAME = "google/mt5-base"
OUTPUT_CSV = "dataset_code_mixed_langchain.csv"
CHECKPOINT = "checkpoint_langchain.txt"
BATCH_SIZE = 1  # LangChain typically processes sequentially
MAX_NEW_TOKENS = 100 # Reduced max tokens

# 🔥 Load model with memory optimizations
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load model with 8-bit quantization
try:
    llm = HuggingFacePipeline.from_model_id(
        model_id=MODEL_NAME,
        task='text2text-generation',
        pipeline_kwargs=dict(
            temperature=0.5,
            max_new_tokens=MAX_NEW_TOKENS
        ),
        model_kwargs={"load_in_8bit": True} # Apply 8-bit quantization
    )
    print("Model loaded with 8-bit quantization.")
except Exception as e:
    print(f"8-bit loading failed: {e}")
    # Fallback to regular loading if 8-bit fails
    llm = HuggingFacePipeline.from_model_id(
        model_id=MODEL_NAME,
        task='text2text-generation',
        pipeline_kwargs=dict(
            temperature=0.5,
            max_new_tokens=MAX_NEW_TOKENS
        )
    )
    print("Model loaded without 8-bit quantization.")


model = llm # Use llm directly

# Define prompt template
prompt = PromptTemplate(
    input_variables=["input_text"],
    template="Code-mix this Bengali sentence naturally with English, preserving meaning: {input_text}"
)

# Create chain
code_mix_chain = prompt | model

# 📄 Load dataset
# Ensure df is loaded before this cell
if 'df' not in locals():
    print("DataFrame 'df' not found. Please load the dataset first.")
    # Exit or handle the case where df is not loaded
    # For now, assuming df is loaded in a previous cell

df["code_mixed"] = ""  # Initialize column
n = len(df)

# ➡️ Resume from checkpoint if exists
start_idx = 0
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT, 'r') as f:
        start_idx = int(f.read().strip())
    print(f"Resuming from row {start_idx}...")

    # Load existing output file if resuming
    if os.path.exists(OUTPUT_CSV):
        try:
            existing_df = pd.read_csv(OUTPUT_CSV)
            if len(existing_df) >= start_idx:
                df.iloc[:start_idx] = existing_df.iloc[:start_idx]
        except pd.errors.EmptyDataError:
             print(f"Checkpoint file {CHECKPOINT} found, but {OUTPUT_CSV} is empty. Starting from the beginning.")
             start_idx = 0


# ⏰ Sequential processing (LangChain typically works sequentially)
for i in tqdm(range(start_idx, n)):
    input_text = df['tgt_txt'].iloc[i]

    try:
        # Run the chain
        result = code_mix_chain.invoke({"input_text":input_text})
        df.at[i, "code_mixed"] = result
        # print(f"Row {i}: {result.content}") # Optional: print output for debugging

        # 💾 Save progress incrementally
        # Write headers only for the first row being written
        header = (i == 0 and start_idx == 0)
        # Append only the current row to the CSV
        df.iloc[i:i+1].to_csv(OUTPUT_CSV, mode='a', header=header, index=False)

        # Update checkpoint
        with open(CHECKPOINT, 'w') as f:
            f.write(str(i + 1))  # Next row to process

        # Clear cache after each iteration
        torch.cuda.empty_cache()


    except Exception as e:
        print(f"Error processing row {i}: {str(e)}")
        # Save progress up to this point in case of error
        # Append only the current row to the CSV with an error marker
        df.at[i, "code_mixed"] = f"[ERROR: {str(e)}]"
        header = (i == 0 and start_idx == 0)
        df.iloc[i:i+1].to_csv(OUTPUT_CSV, mode='a', header=header, index=False)

        # Update checkpoint
        with open(CHECKPOINT, 'w') as f:
            f.write(str(i + 1)) # Mark this row as attempted (with error)

        continue # Continue to the next row


# Clean up checkpoint after completion
if os.path.exists(CHECKPOINT):
    os.remove(CHECKPOINT)

print("✅ Code mixing completed using LangChain!")

/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Error processing row 0: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
✅ Code mixing completed using LangChain!

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch, pandas as pd
import os

# ⚙️ Config
MODEL_NAME = "google/mt5-base"
OUTPUT_CSV = "dataset_code_mixed.csv"
CHECKPOINT = "checkpoint.txt"
BATCH_SIZE = 1  # Reduced from 16 to prevent OOM

# 🔥 Load model with memory optimizations
device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(device)
model = model.half()  # Use FP16 to reduce memory
model.gradient_checkpointing_enable()  # Reduce memory during training
torch.cuda.empty_cache()  # Clear unused memory

# 📄 Load dataset
df["code_mixed"] = ""  # Initialize column
n = len(df)

# ➡️ Resume from checkpoint if exists
start_idx = 0
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT, 'r') as f:
        start_idx = int(f.read().strip())
    print(f"Resuming from row {start_idx}...")

    # Load existing output file if resuming
    if os.path.exists(OUTPUT_CSV):
        existing_df = pd.read_csv(OUTPUT_CSV)
        if len(existing_df) >= start_idx:
            df.iloc[:start_idx] = existing_df.iloc[:start_idx]

# ⏰ Batch processing
for i in range(start_idx, n, BATCH_SIZE):
    batch = df['tgt_txt'].iloc[i:i+BATCH_SIZE].tolist()
    prompts = [f"Code-mix this Bengali sentence naturally with English, preserving meaning: {s}" for s in batch]

    # Tokenize with length limits
    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(device)

    # Generate with memory optimizations
    with torch.cuda.amp.autocast():  # Mixed precision
        outputs = model.generate(
            **inputs,
            do_sample=True,
            temperature=0.9,
            use_cache=True  # Disable cache to save memory
        )

    decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    print(decoded)

    # Update only the current batch in the DataFrame
    df.loc[i:i+len(decoded)-1, "code_mixed"] = decoded

    # 💾 Save progress incrementally
    # Write headers only for the first batch
    header = (i == 0)
    # Append only the current batch to the CSV
    df.iloc[i:i+len(decoded)].to_csv(OUTPUT_CSV, mode='a', header=header, index=False)

    # Update checkpoint
    with open(CHECKPOINT, 'w') as f:
        f.write(str(min(i + BATCH_SIZE, n)))  # Don't overshoot total rows

# Clean up checkpoint after completion
if os.path.exists(CHECKPOINT):
    os.remove(CHECKPOINT)

print("✅ Code mixing completed!")

tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/702 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0>  <extra_id_1>- - 17 “-“”/” thoughts ” ss']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0>  <extra_id_1>, e ss s s s s s ']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0>  <extra_id_1> প্রায়  <extra_id_2> ক্ষে র ল  <extra_id_3> র র ']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0> অক্ষ ই e g ue- a- a-t']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0> মৌখ <extra_id_1> আমাদের র র <extra_id_2> াঁ এ <extra_id_3> অথবা ']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0>  <extra_id_1>ের আঞ্চ র! বেশি য়ি আঞ্চ  োৱ']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

['<extra_id_0>  <extra_id_1> সেই র র! i o! i - 24']

/tmp/ipython-input-14-2669553173.py:50: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast():  # Mixed precision

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.91 GiB. GPU 0 has a total capacity of 14.74 GiB of which 1.27 GiB is free. Process 8103 has 13.47 GiB memory in use. Of the allocated memory 9.01 GiB is allocated by PyTorch, and 4.34 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch, pandas as pd
from tqdm import tqdm
import os

# ⚙️ Config
MODEL_NAME = "google/mt5-small"  # Using smaller model to save memory
OUTPUT_CSV = "dataset_code_mixed.csv"
CHECKPOINT = "checkpoint.txt"
BATCH_SIZE = 1  # Keep batch size at 1 for memory constraints

# 🔥 Load model with aggressive memory optimizations
device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Load model with low_cpu_mem_usage and quantization
model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True
).to(device)

# Additional memory savings
model.eval()  # Disable dropout
torch.cuda.empty_cache()

# 📄 Load dataset in chunks if large
df["code_mixed"] = ""  # Initialize column
n = len(df)

# ➡️ Resume from checkpoint if exists
start_idx = 0
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT, 'r') as f:
        start_idx = int(f.read().strip())
    print(f"Resuming from row {start_idx}...")

    # Load existing output file if resuming
    if os.path.exists(OUTPUT_CSV):
        existing_df = pd.read_csv(OUTPUT_CSV)
        if len(existing_df) >= start_idx:
            df.iloc[:start_idx] = existing_df.iloc[:start_idx]

# ⏰ Process one item at a time with memory cleanup
with torch.no_grad():  # Disable gradient calculation
    for i in tqdm(range(start_idx, n)):
        try:
            text = df["text"].iloc[i]
            prompt = f"Code-mix this Bengali sentence naturally with English, preserving meaning: {text}"

            # Tokenize with strict length limits
            inputs = tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                padding="max_length"
            ).to(device)

            # Generate with memory optimizations
            with torch.cuda.amp.autocast():
                output = model.generate(
                    **inputs,
                    max_new_tokens=MAX_TOKENS,
                    do_sample=True,
                    temperature=0.9,
                    num_beams=1,  # Disable beam search to save memory
                    use_cache=False
                )

            decoded = tokenizer.decode(output[0], skip_special_tokens=True)
            df.at[i, "code_mixed"] = decoded
            print(decoded)

            # 💾 Append to CSV immediately
            df.iloc[[i]].to_csv(OUTPUT_CSV, mode='a', header=not os.path.exists(OUTPUT_CSV), index=False)

            # Update checkpoint
            with open(CHECKPOINT, 'w') as f:
                f.write(str(i + 1))

            # Clear memory
            del inputs, output, decoded
            torch.cuda.empty_cache()

        except Exception as e:
            print(f"Error processing row {i}: {str(e)}")
            # Save progress even if error occurs
            df.iloc[[i]].to_csv(OUTPUT_CSV, mode='a', header=not os.path.exists(OUTPUT_CSV), index=False)
            with open(CHECKPOINT, 'w') as f:
                f.write(str(i + 1))
            continue

# Clean up checkpoint after completion
if os.path.exists(CHECKPOINT):
    os.remove(CHECKPOINT)

print("✅ Code mixing completed!")

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch, pandas as pd
from tqdm import tqdm
import os
import gc
import psutil

# ⚙️ Config
MODEL_NAME = "google/mt5-small"  # Using smallest available model
OUTPUT_CSV = "dataset_code_mixed.csv"
CHECKPOINT = "checkpoint.txt"
MAX_TOKENS = 60
MAX_INPUT_TOKENS = 64  # Reduced from 128
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# 🧹 Memory monitoring
def print_memory_usage():
    process = psutil.Process(os.getpid())
    print(f"Memory usage: {process.memory_info().rss / 1024 / 1024:.2f} MB")
    if torch.cuda.is_available():
        print(f"GPU memory: {torch.cuda.memory_allocated() / 1024 / 1024:.2f} MB / {torch.cuda.max_memory_allocated() / 1024 / 1024:.2f} MB")

# 🔥 Load model with 8-bit quantization
try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForSeq2SeqLM.from_pretrained(
        MODEL_NAME,
        device_map="auto",
        load_in_8bit=True,  # 8-bit quantization
        torch_dtype=torch.float16
    )
    print("Model loaded in 8-bit precision")
except Exception as e:
    print(f"8-bit loading failed: {e}")
    # Fallback to regular loading
    model = AutoModelForSeq2SeqLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16
    ).to(DEVICE)
    print("Model loaded in 16-bit precision")

model.eval()  # Disable dropout

# 📄 Load dataset
# Ensure df is loaded and filtered before this cell
if 'df' in locals():
    # Reset index after filtering to ensure a simple 0-based index
    df = df.reset_index(drop=True)
    df["code_mixed"] = ""  # Initialize column
    n = len(df)
else:
    print("DataFrame 'df' not found. Please load and filter the dataset first.")
    n = 0 # Set n to 0 to prevent loop from running

# ➡️ Resume from checkpoint
start_idx = 0
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT, 'r') as f:
        start_idx = int(f.read().strip())
    print(f"Resuming from row {start_idx}...")

    if os.path.exists(OUTPUT_CSV):
        try:
            existing_df = pd.read_csv(OUTPUT_CSV)
            if len(existing_df) >= start_idx:
                # Ensure existing_df also has a simple index or align by content if necessary
                # For simplicity, assuming the checkpoint and output CSV correspond to the reset index
                # A more robust approach would align based on unique identifiers if available
                 df.iloc[:start_idx] = existing_df.iloc[:start_idx]
        except pd.errors.EmptyDataError:
             print(f"Checkpoint file {CHECKPOINT} found, but {OUTPUT_CSV} is empty. Starting from the beginning.")
             start_idx = 0


# ⏰ Process with aggressive memory management
with torch.no_grad():
    for i in tqdm(range(start_idx, n)):
        try:
            # Clear memory aggressively
            torch.cuda.empty_cache()
            gc.collect()

            # Access row by integer position after resetting index
            text = df.loc[i, "tgt_txt"]
            prompt = f"Code-mix this Bengali sentence naturally with English, preserving meaning: {text}"

            # Tokenize with strict length limits
            inputs = tokenizer(
                prompt,
                return_tensors="pt",
                max_length=MAX_INPUT_TOKENS,
                truncation=True,
                padding="max_length"
            )

            # Move to device (with fallback to CPU if needed)
            try:
                inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
            except RuntimeError as e:
                print(f"Moving to GPU failed, falling back to CPU: {e}")
                DEVICE = "cpu"
                model = model.to(DEVICE)
                inputs = {k: v.to(DEVICE) for k, v in inputs.items()}

            # Generate with memory optimizations
            try:
                output = model.generate(
                    **inputs,
                    max_new_tokens=MAX_TOKENS,
                    do_sample=True,
                    temperature=0.9,
                    num_beams=1,  # Disable beam search
                    use_cache=False,
                    early_stopping=True
                )

                decoded = tokenizer.decode(output[0], skip_special_tokens=True)
                print(f"Row {i}: {decoded}") # Print row number and output
                # Set value using integer position after resetting index
                df.loc[i, "code_mixed"] = decoded

            except RuntimeError as e:
                print(f"Generation failed for row {i}: {e}")
                df.loc[i, "code_mixed"] = f"[ERROR: GENERATION FAILED: {e}]"

            # Save progress after each row
            # Ensure header is written only once
            header = not os.path.exists(OUTPUT_CSV)
            df.iloc[[i]].to_csv(OUTPUT_CSV, mode='a', header=header, index=False)

            # Update checkpoint
            with open(CHECKPOINT, 'w') as f:
                f.write(str(i + 1))

            # Clear variables
            del inputs, output, decoded
            torch.cuda.empty_cache()
            gc.collect()

        except Exception as e:
            print(f"Error processing row {i}: {str(e)}")
            df.loc[i, "code_mixed"] = f"[ERROR: {str(e)}]"
            header = not os.path.exists(OUTPUT_CSV)
            df.iloc[[i]].to_csv(OUTPUT_CSV, mode='a', header=header, index=False)
            with open(CHECKPOINT, 'w') as f:
                f.write(str(i + 1))
            continue

# Clean up
if os.path.exists(CHECKPOINT):
    os.remove(CHECKPOINT)

print("✅ Code mixing completed!")
print_memory_usage()

tokenizer_config.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.11/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

8-bit loading failed: Using `bitsandbytes` 8-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`

pytorch_model.bin:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

KeyboardInterrupt:

In [ ]:
!pip install transformers sentencepiece torch

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.6.15)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 39.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 26.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 27.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 16.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 9.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.3 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 35.0 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# Load the model
model_name = "facebook/mbart-large-50-many-to-many-mmt"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

pipe = pipeline("text2text-generation", model=model, tokenizer=tokenizer)

# Example Bengali sentence
bengali_sentence = """
नमस्कार !
‘मन की बात’ के माध्यम से फिर एक बार आप सबसे रूबरू होने का अवसर मिला है। आप लोगों को भलीभांति याद होगा नौ-सेना की 6 महिला कमांडरों, ये एक दल पिछले कई महीनों से समुद्र की यात्रा पर था। ‘नाविका सागर परिक्रमा’ – जी मैं उनके विषय में कुछ बात करना चाहता हूँ। भारत की इन 6 बेटियों ने, उनकी इस team ने Two Hundred And Fifty Four Days- 250 से भी ज़्यादा दिनसमुद्र के माध्यम से INSV तारिणी में पूरी दुनिया की सैर कर 21 मई को भारत वापस लौटी हैं और पूरे देश ने उनका काफी गर्मजोशी से स्वागत किया। उन्होंने विभिन्न महासागरों और कई समुद्रों में यात्रा करते हुए लगभग बाईस हज़ार nautical miles की दूरी तय की। यह विश्व में अपने आप में एक पहली घटना थी। गत बुधवार को मुझे इन सभी बेटियों से मिलने का, उनके अनुभव सुनने का अवसर मिला। मैं एक बार फिर इन बेटियों कोउनके adventure को, Navy की प्रतिष्ठा को बढ़ाने के लिए, भारत का मान-सम्मान बढ़ाने के लिये और विशेषकर दुनिया को भी लगे कि भारत की बेटियाँ कम नहीं हैं – ये सन्देश पहुँचाने के लिए बहुत-बहुत बधाई देता हूँ। Sense of adventure कौन नहीं जानता है। अगर हम मानव जाति की विकास यात्रा देखें तो किसी-न-किसी adventure की कोख में ही प्रगति पैदा हुई है। विकास adventure की गोद में ही तो जन्म लेता है। कुछ कर गुजरने का इरादा, कुछ लीक से हटकर के करने का मायना, कुछ extra ordinary करने की बात, मैं भी कुछ कर सकता हूँ – ये भाव,करने वाले भले कम हों, लेकिन युगों तक, कोटि-कोटि लोगों को प्रेरणा मिलती रहती है। पिछले दिनों आपने देखा होगा Mount Everest पर चढ़ने वालों के विषय में कई नयी-नयी बातें ध्यान में आयी हैं और सदियों से Everest मानव जाति को ललकारता रहा और बहादुर लोग उस चुनौती को स्वीकारते भी रहे हैं ।
16 मई को महाराष्ट्र के चंद्रपुर के एक आश्रम-स्कूल के 5 आदिवासी बच्चों ने tribal students – मनीषा धुर्वे, प्रमेश आले, उमाकान्त मडवी, कविदास कातमोड़े, विकास सोयाम – इन हमारे आदिवासी बच्चों के एक दल ने दुनिया की सबसे ऊँची चोटी पर चढ़ाई की। आश्रम-स्कूल के इन छात्रों ने अगस्त 2017 में training शुरू की थी। वर्धा, हैदराबाद, दार्जिलिंग, लेह, लद्दाख – इनकी training हुई। इन युवाओं को ‘मिशन शौर्य’ के तहत चुना गया थाऔर नाम के ही अनुरूप Everest फतह कर उन्होंने पूरे देश को गौरवान्वित किया है। मैं चंद्रपुर के स्कूल के लोगों को, इन मेरे नन्हे-मुन्हे साथियों को, ह्रदय से बहुत-बहुत बधाई देता हूँ। हाल ही में 16 वर्षीय शिवांगी पाठक, नेपाल की ओर से Everest फ़तह करने वाली सबसे कम उम्र की भारतीय महिला बनी। बेटी शिवांगी को बहुत-बहुत बधाई।
अजीत बजाज और उनकी बेटी दीयाEverest की चढ़ाई करने वाली पहली भारतीय पिता-पुत्री की जोड़ी बन गयी। ऐसा ही नहीं कि केवल युवा ही Everest की चढ़ाई कर रहे हैं। संगीता बहल ने 19 मई को Everest की चढ़ाई की और संगीता बहल की आयु 50 से भी अधिक है। Everest पर चढ़ाई करने वाले कुछ ऐसे भी हैं, जिन्होंने दिखाया कि उनके पास न केवल skill है बल्कि वे sensitive भी हैं। अभी पिछले दिनों ‘स्वच्छ गंगा अभियान’ के तहत BSF के एक group ने Everest की चढ़ाई की,पर पूरी team Everest से ढ़ेर सारा कूड़ा अपने साथ नीचे उतार कर लायी। यह कार्य प्रशंसनीय तो है ही, साथ-ही-साथ यह स्वच्छता के प्रति, पर्यावरण के प्रति उनकी प्रतिबद्धता को भी दर्शाता है। वर्षों से लोग Everest की चढ़ाई करते रहे हैं और ऐसे कई लोग हैं, जिन्होंने सफलतापूर्वक इसे पूरा किया है। मैं इन सभी साहसी वीरों को, ख़ासकर के बेटियों को ह्रदय से बहुत-बहुत बधाई देता हूँ।
मेरे प्यारे देशवासियो और ख़ासकर के मेरे नौजवान दोस्तो ! अभी दो महीने पहले जब मैंने fit India की बात की थी तो मैंने नहीं सोचा था कि इस पर इतना अच्छा response आएगा। इतनी भारी संख्या में हर क्षेत्र से लोग इसके support में आगे आएँगे। जब में fit India की बात करता हूँ तो मैं मानता हूँ कि जितना हम खेलेंगे, उतना ही देश खेलेगा। social media पर लोग Fitness Challenge की videos share कर रहे हैं, उसमें एक-दूसरे को tag कर उन्हें challenge कर रहे हैं। Fit India के इस अभियान से आज हर कोई जुड़ रहा है। चाहे फिल्म से जुड़े लोग हों, sports से जुड़े लोग हों या देश के आम-जन, सेना के जवान हों, स्कूल की टीचर हों, चारों तरफ़ से एक ही गूँज सुनाई दे रही है – ‘हम fit तो India fit’। मेरे लिए खुशी की बात है कि मुझे भी भारतीय क्रिकेट टीम के कप्तान विराट कोहली जी ने challenge किया है और मैंने भी उनके challenge को स्वीकार किया है। मैं मानता हूँ कि ये बहुत अच्छी चीज है और इस तरह का challenge हमें fit रखने और दूसरों को भी fit रहने के लिए प्रोत्साहित करेगा ।
मेरे प्यारे देशवासियो! ‘मन की बात’ में कई बार खेल के संबंध में, खिलाडियों के संबंध में, कुछ-न-कुछ बातें आपने मेरे से सुनी ही हैं और पिछली बार तो Commonwealth Games के हमारे नायक, अपनी मन की बातें, इस कार्यक्रम के माध्यम से हमें बता रहे थे –
“नमस्कार सर ! मैं छवि यादव नोएडा से बोल रही हूँ, मैं आपकी ‘मन की बात’ की regular listener हूँ और आज आपसे अपनी मन की बात करना चाहती हूँ. आजकल गर्मी की छुट्टियाँ शुरू हो गयी हैं और एक माँ होने के नाते मैं देख रही हूँ कि बच्चे ज़्यादातर समय इंटरनेट games खेलते हुए बिताते हैं, जब कि जब हम छोटे थे तो हम Traditional Games जो कि ज़्यादातर Outdoor gamesहोते थे, वो खेलते थे, जैसा कि एक game था जिसमें 7 पत्थर के टुकड़े एक के ऊपर एक रखके उसे ball से मारते थे और ऊँच-नीच होता था, खो-खो, ये सब gameजो आजकल खो से गए हैं। मेरा ये निवेदन है कि आप आजकल की generation को कुछ traditional games के बारे में बताएं, जिससे उनकी भी रूचि इस तरफ़ बढ़े, धन्यवाद । ”
छवि यादव जी, आपके phone call के लिए आपका बहुत धन्यवाद। ये बात सही है कि जो खेल कभी गली-गली, हर बच्चे के जीवन का हिस्सा होते थे, वे आज कम होते जा रहे हैं। ये खेल ख़ासकर गर्मी की छुट्टियों का विशेष हिस्सा होते थे। कभी भरी दोपहरी में, तो कभी रात में खाने के बाद बिना किसी चिंता के, बिल्कुल बेफिक्र होकर के बच्चे घंटो-घंटो तक खेला करते थे और कुछ खेल तो ऐसे भी हैं,जो पूरा परिवार साथ में खेला करता था – पिट्ठू हो या कंचे हो, खो-खो हो,लट्टू हो या गिल्ली-डंडा हो, न जाने…..अनगिनत खेल कश्मीर से कन्याकुमारी, कच्छ से कामरूप तक हर किसी के बचपन का हिस्सा हुआ करते थे। हाँ, यह हो सकता है कि अलग-अलग जगह वो अलग-अलग नामों से जाने जाते थे, जैसे अब पिट्ठू ही यह खेल कई नामों से जाना जाता है। कोई उसे लागोरी, सातोलिया, सात पत्थर, डिकोरी, सतोदिया न जाने कितने नाम हैं एक ही खेल के। परंपरागत खेलों में दोनों तरह के खेल हैं। out door भी हैं, indoor भी हैं। हमारे देश कीविविधताके पीछे छिपी एकता इन खेलों में भी देखी जा सकती है। एक ही खेल अलग-अलग जगह, अलग-अलग नामों से जाना जाता है। मैं गुजरात से हूँ मुझे पता है गुजरात में एक खेल है, जिसे चोमल-इस्तो कहते हैं। ये कोड़ियों या इमली के बीज या dice के साथ और 8×8 के square board के साथ खेला जाता है। यह खेल लगभग हर राज्य में खेला जाता था। कर्नाटक में इसे चौकाबारा कहते थे, मध्यप्रदेश में अत्तू। केरल में पकीड़ाकाली तो महाराष्ट्र में चम्पल, तो तमिलनाडु में दायाम और थायाम, तो कहीं राजस्थान में चंगापो न जाने कितने नाम थे लेकिन खेलने के बाद पता चलता है, हर राज्य वाले को भाषा भले न जानता हो – अरे वाह! ये खेल तो हम भी करते थे। हम में से कौन होगा, जिसने बचपन में गिल्ली-डंडा न खेला हो। गिल्ली-डंडा तो गाँव से लेकर शहरों तक में खेले जाने वाला खेल है। देश के अलग-अलग भागों में इसे अलग-अलग नामों से जाना जाता है। आंध्रप्रदेश में इसे गोटिबिल्ला या कर्राबिल्ला के नाम से जानते हैं। उड़ीसा में उसे गुलिबाड़ी कहते हैं तो महाराष्ट्र में इसे वित्तिडालू कहते हैं। कुछ खेलों काअपना एक season होता है। जैसे पतंग उड़ाने का भी एक season होता है। जब हर कोई पतंग उड़ाता है जब हम खेलते हैं, हम में जो unique qualities होती हैं, हम उन्हें freely express कर पाते हैं। आपने देखा होगा कई बच्चे, जो शर्मीले स्वभाव के होते हैं लेकिन खेलते समय बहुत ही चंचल हो जाते हैं। ख़ुद को express करते हैं, बड़े जो गंभीर से दिखते हैं, खेलते समय उनमें जो एक बच्चा छिपा होता है, वो बाहर आता है। पारंपरिक खेल कुछ इस तरह से बने हैं कि शारीरिक क्षमता के साथ-साथ वो हमारी logical thinking, एकाग्रता, सजगता, स्फूर्ति को भी बढ़ावा देते हैं। और खेल सिर्फ खेल नहीं होते हैं, वह जीवन के मूल्यों को सिखाते हैं। लक्ष्य तय करना, दृढ़ता कैसे हासिल करना!, team spirit कैसे पैदा होना, परस्पर सहयोग कैसे करना। पिछले दिनों मैं देख रहा था कि Business Management से जुड़े हुए training programmes में भी overall personality development और interpersonal skills के improvement के लिए भी हमारे जो परंपरागत खेल थे, उसका आजकल उपयोग हो रहा है और बड़ी आसानी से overall development में हमारे खेल काम आ रहे हैं और फिर इन खेलों को खेलने की कोई उम्र तो है ही नहीं। बच्चों से ले करके दादा-दादी, नाना-नानी जब सब खेलते हैं तो यह जो कहते हैं न generation gap,अरे वो भी छू-मंतर हो जाता है। साथ-ही-साथ हम अपनी संस्कृति और परम्पराओं को भी जानते हैं। कई खेल हमें समाज, पर्यावरण आदि के बारे में भी जागरूक करते हैं। कभी-कभी चिंता होती है कि कहीं हमारे यह खेल खो न जाएँ और वह सिर्फ खेल ही नहीं खो जाएगा, कहीं बचपन ही खो जाएगा और फिर उस कविताओं को हम सुनते रहेंगे –
यह दौलत भी ले लो
यह शौहरत भी ले लो
भले छीन लो मुझसे मेरी जवानी
मगर मुझको लौटा दो बचपन का सावन
वो कागज की कश्ती, वो बारिश का पानी

यही गीत हम सुनते रह जाएँगे और इसीलिए यह पारंपरिक खेल, इसको खोना नहीं हैआज आवश्यकता है कि स्कूल, मौहल्ले,युवा-मंडल आगे आकर इन खेलों को बढ़ावा दें। crowd sourcing के द्वारा हम अपने पारंपरिक खेलों का एक बहुत बड़ा archive बना सकते हैं। इन खेलों के videos बनाए जा सकते हैं, जिनमें खेलों के नियम, खेलने के तरीके के बारे में दिखाया जा सकता है। Animation फ़िल्में भी बनाई जा सकती हैं ताकि हमारी जो नई पीढ़ी है, जिनके लिए यह गलियों में खेले जाने वाले खेल कभी-कभी अज़ूबा होता है – वह देखेंगे, खेलेंगे, खिलेंगे।
मेरे प्यारे देशवासियो ! आने वाले 5 जून को हमारा देश भारत आधिकारिक तौर पर World Environment Day Celebration विश्व पर्यावरण दिवस को भारत host करेगा। यह भारत के लिए एक बहुत महत्वपूर्ण उपलब्धि है और यह जलवायु परिवर्तन को कम करने की दिशा में विश्व में भारत के बढ़ते नेतृत्व को भी स्वीकृति मिल रही है – इसका परिचायक है। इस बार की theme है ‘Beat Plastic Pollution’। मेरी आप सभी से अपील है, इस theme के भाव को, इसके महत्व को समझते हुए हम सब यह सुनिश्चित करें कि हमpolythene, low grade plastic का उपयोग न करें और Plastic Pollution का जो एक negative impact हमारी प्रकृति पर, wild life पर और हमारे स्वास्थ्य पर पड़ रहा है, उसे कम करने का प्रयास करें। World Environment Day की website wed-india2018 पर जाएँ और वहाँ ढ़ेर सारे सुझाव बड़े ही रोचक ढ़ंग से दिए गए हैं – देखें, जानें और उन्हें अपने रोजमर्रा के जीवन में उतारने का प्रयास करें। जब भयंकर गर्मी होती है, बाढ़ होती है। बारिश थमती नहीं है। असहनीय ठंड पड़ जाती है तो हर कोई expert बन करके global warming, climate change इसकी बातें करता है लेकिन क्या बातें करने से बात बनती है क्या? प्रकृति के प्रति संवेदनशील होना, प्रकृति की रक्षा करना, यह हमारा सहज स्वभाव होना चाहिए, हमारे संस्कारों में होना चाहिए। पिछले कुछ हफ़्तों में हम सभी ने देखा कि देश के अलग-अलग क्षेत्रों में धूल-आँधी चली, तेज़ हवाओं के साथ-साथ भारी वर्षा भी हुई, जो कि unseasonal है। जान-हानि भी हुई, माल-हानि भी हुई। यह सारी चीज़ें मूलतः weather pattern में जो बदलाव है, उसी का परिणाम है हमारी संस्कृति, हमारी परंपरा ने हमें प्रकृति के साथ संघर्ष करना नहीं सिखाया है। हमें प्रकृति के साथ सदभाव से रहना है, प्रकृति के साथ जुड़ करके रहना है। महात्मा गाँधी ने तो जीवन भर हर कदम इस बात की वकालत की थी। जब आज भारत climate justice की बात करता है। जब भारत ने Cop21 और Paris समझौते में प्रमुख भूमिका निभाई। जब हमनें International Solar Alliance के माध्यम से पूरी दुनिया को एकजुट किया तो इन सबके मूल में महात्मा गाँधी के उस सपने को पूरा करने का एक भाव था। इस पर्यावरण दिवस पर हम सब इस बारे में सोचें कि हम अपने planet को स्वच्छ और हरित बनाने के लिए क्या कर सकते हैं? किस तरह इस दिशा में आगे बढ़ सकते हैं? क्या innovative कर सकते हैं? बारिश का मौसम आने वाला है,हम इस बार record वृक्षारोपण का लक्ष्य ले सकते हैं और केवल वृक्ष लगाना ही नहीं बल्कि उसके बड़े होने तक उसके रख-रखाव की व्यवस्था करना।

मेरे प्यारे देशवासियो और विशेषकर के मेरे नौजवान साथियो ! आप 21 जून को बराबर अब याद रखते हैं, आप ही नहीं, हम ही नहीं सारी दुनिया 21 जून को याद रखती है। पूरे विश्व के लिए 21 जून अंतर्राष्ट्रीय योग दिवस के रूप में मनाया जाता है और ये सर्व-स्वीकृत हो चुका है और लोग महीनों पहले तैयारियाँ शुरू कर देते हैं। इन दिनों ख़बर मिल रही है, सारी दुनिया में 21 जून को अंतर्राष्ट्रीय योग दिवस मनाने की भरसक तैयारियाँ चल रही हैं। Yoga For Unity और harmonious society का ये वो सन्देश है, जो विश्व ने पिछले कुछ वर्षों से बार-बार अनुभव किया है। संस्कृत के महान कवि भर्तृहरि ने सदियों पहले अपने शतकत्रयम् में लिखा था –
धैर्यं यस्य पिता क्षमा च जननी शान्तिश्चिरं गेहिनी
सत्यं सूनुरयं दया च भगिनी भ्राता मनः संयमः।
शय्या भूमितलं दिशोSपि वसनं ज्ञानामृतं भोजनं
एते यस्य कुटिम्बिनः वद सखे कस्माद् भयं योगिनः।।

सदियों पहले ये कही गई बात का सीधा-सीधा मतलब है कि नियमित योगा अभ्यास करने पर कुछ अच्छे गुण सगे-सम्बन्धियों और मित्रों की तरह हो जाते हैं। योग करने से साहस पैदा होता है जो सदा ही पिता की तरह हमारी रक्षा करता है। क्षमा का भाव उत्पन्न होता है जैसा माँ का अपने बच्चों के लिए होता है और मानसिक शांति हमारी स्थायी मित्र बन जाती है। भर्तृहरि ने कहा है कि नियमित योग करने से सत्य हमारी संतान, दया हमारी बहन, आत्मसंयम हमारा भाई, स्वयं धरती हमारा बिस्तर और ज्ञान हमारी भूख मिटाने वाला बन जाता है। जब इतने सारे गुण किसी के साथी बन जाएँ तो योगी सभी प्रकार के भय पर विजय प्राप्त कर लेता है। एक बार फिर मैं सभी देशवासियों से अपील करता हूँ कि वे योग की अपनी विरासत को आगे बढ़ायें और एक स्वस्थ, खुशहाल और सद्भावपूर्ण राष्ट्र का निर्माण करें।
मेरे प्यारे देशवासियो ! आज 27 मई है। भारत के प्रथम प्रधानमंत्री पंडित जवाहरलाल नेहरु जी की पुण्यतिथि है। मैं पंडित जी को प्रणाम करता हूँ। इस मई महीने की याद एक और बात से भी जुड़ी है और वो है वीर सावरकर। 1857 में ये मई का ही महीना था, जब भारतवासियों ने अंग्रेजों को अपनी ताकत दिखाई थी। देश के कई हिस्सों में हमारे जवान और किसान अपनी बहादुरी दिखाते हुए अन्याय के विरोध में उठ खड़े हुए थे। दुःख की बात है कि हम बहुत लम्बे समय तक 1857 की घटनाओं को केवल विद्रोह या सिपाही विद्रोह कहते रहे। वास्तव में उस घटना को न केवल कम करके आँका गया बल्कि यह हमारे स्वाभिमान को धक्का पहुँचाने का भी एक प्रयास था। यह वीर सावरकर ही थे, जिन्होंने निर्भीक हो के लिखा कि 1857 में जो कुछ भी हुआ वो कोई विद्रोह नहीं था बल्कि आजादी की पहली लड़ाई थी। सावरकर सहित लंदन के India House के वीरों ने इसकी 50वीं वर्षगांठ धूमधाम से मनाई। यह भी एक अद्भुत संयोग है कि जिस महीने में स्वतंत्रता का पहला स्वतंत्र संग्राम आरंभ हुआ, उसी महीने में वीर सावरकर जी का जन्म हुआ। सावरकर जी का व्यक्तित्व विशेषताओं से भरा था; शस्त्र और शास्त्र दोनों के उपासक थे। आमतौर पर वीर सावरकर को उनकी बहादुरी और ब्रिटिशराज के खिलाफ़ उनके संघर्ष के लिए जानते हैं लेकिन इन सबके अलावा वे एक ओज़स्वी कवि और समाज सुधारक भी थे, जिन्होंने हमेशा सद्भावना और एकता पर बल दिया। सावरकर जी के बारे में एक अद्भुत वर्णन हमारे प्रिय आदरणीय अटल बिहारी वाजपेयी जी ने किया है। अटल जी ने कहा था – सावरकर माने तेज़, सावरकर माने त्याग, सावरकर माने तप, सावरकर माने तत्व, सावरकर माने तर्क, सावरकर माने तारुण्य, सावरकर माने तीर, सावरकर माने तलवार। कितना सटीक चित्रण किया था अटल जी ने। सावरकर कविता और क्रांति दोनों को साथ लेकर चले। संवेदनशील कवि होने के साथ-साथ वे साहसिक क्रांतिकारी भी थे।

मेरे प्यारे भाइयो-बहनो ! मैं टी.वी. पर एक कहानी देख रहा था। राजस्थान के सीकर की कच्ची बस्तियों की हमारी ग़रीब बेटियों की। हमारी ये बेटियाँ, जो कभी कचराबीनने से लेकर घर-घर माँगने को मजबूर थीं – आज वें सिलाई का काम सीख कर ग़रीबों का तन ढ़कने के लिए कपड़े सिल रही हैं। यहाँ की बेटियाँ, आज अपने और अपने परिवार के कपड़ों के अलावा सामान्य से लेकर अच्छे कपड़े तक सिल रही हैं। वे इसके साथ-साथ कौशल विकास का course भी कर रही हैं। हमारी ये बेटियाँ आज आत्मनिर्भर बनी हैं। सम्मान के साथ अपना जीवन जी रही है और अपने-अपने परिवार के लिए एक ताक़त बन गई है। मैं आशा और विश्वास से भरी हमारी इन बेटियों को उनके उज्ज्वल भविष्य की शुभकामनाएँ देता हूँ। इन्होंने दिखाया है कि अगर कुछ कर दिखाने का जज़्बा हो और उसके लिए आप कृतसंकल्पित हों तो तमाम मुश्किलों के बीच भी सफलता हासिल की जा सकती है और ये सिर्फ सीकर की बात नहीं है हिन्दुस्तान के हर कोने में आपको ये सब देखने को मिलेगा। आपके पास, अड़ोस-पड़ोस में नज़र करोगे तो ध्यान में आएगा कि लोग किस प्रकार से परेशानियों को परास्त करते हैं। आपने महसूस किया होगा कि जब भी हम किसी चाय की दुकान पर जाते हैं, वहाँ की चाय का आनंद लेते हैं तो साथ के कुछ लोगों से चर्चा और विचार-विमर्श भी होता ही है। ये चर्चा राजनीतिक भी होती है, सामाजिक भी होती है, चलचित्र की भी होती है, खेल और खिलाड़ियों की भी होती है, देश की समस्याओं पर भी होती है – कि ऐसी समस्या है – इसका समाधान ऐसे होगा – ये करना चाहिए लेकिन अक्सर ये चीज़ें सिर्फ चर्चा तक सीमित रह जाती हैं लेकिन कुछ लोग ऐसे होते हैं, जो अपने कार्यों से, अपनी मेहनत और लगन से बदलाव लाने की दिशा में आगे बढ़ते हैं, उसेहकीकत का रूप देते हैं। दूसरों के सपनों को अपना बना लेने वाले और उन्हें पूरा करने के लिए खुद को खपा देने की कुछ ऐसी ही कहानी उड़ीसा के कटक शहर के झुग्गी-झोपड़ी में रहने वाले डी. प्रकाश राव की। कल ही मुझे डी. प्रकाश राव से मिलने का सोभाग्य मिला। श्रीमान् डी. प्रकाश राव पिछले पाँच दशक से शहर में चाय बेच रहे हैं। एक मामूली सी चाय बेचने वाला, आज आप जानकर हैरान हो जायेंगे 70 से अधिक बच्चों के जीवन में शिक्षा का उजियारा भर रहा है। उन्होंने बस्ती और झुग्गियों में रहने वाले बच्चों के लिए ‘आशा आश्वासन’ नाम का एक स्कूल खोला। जिस पर ये ग़रीब चाय वाला अपनी आय का 50% धन उसी में खर्च कर देता है। वे स्कूल में आने वाले सभी बच्चों को शिक्षा, स्वास्थ्य और भोजन की पूरी व्यवस्था करते हैं। में डी. प्रकाश राव की कड़ी मेहनत, उनकी लगन और उन ग़रीब बच्चों के जीवन को नयी दिशा देने के लिए बहुत-बहुत बधाई देता हूँ। उन्होंने उनकी ज़िन्दगी के अँधेरे को समाप्त कर दिया है। ‘तमसो मा ज्योतिर्गमय’ ये वेद-वाक्य कौन नहीं जानता है लेकिन उसको जी करके दिखाया है डी. प्रकाश राव ने। उनकी जीवन हम सभी के लिए, समाज और पूरे देश के लिए एक प्रेरणा है। आप के भी अगल-बगल में ऐसी प्रेरक घटनाओं की श्रृंखला होगी। अनगिनत घटनाएँ होंगी। आइये हम सकारात्मकता को आगे बढाएं ।
जून के महीने में इतनी अधिक गर्मी होती है कि लोग बारिश का इंतज़ार करते हैं और इस उम्मीद में आसमान में बादलों की ओर टकटकी लगाये देखते हैं। अब से कुछ दिनों बाद लोग चाँद की भी प्रतीक्षा करेंगे। चाँद दिखाई देने का अर्थ यह है कि ईद मनाई जा सकती है। रमज़ानके दौरान एक महीने के उपवास के बाद ईद का पर्व जश्न की शुरुआत का प्रतीक है। मुझे विश्वास है कि सभी लोग ईद को पूरे उत्साह से मनायेंगे। इस अवसर पर बच्चों को विशेष तौर पर अच्छी ईदी भी मिलेगी। आशा करता हूँ कि ईद का त्योहार हमारे समाज में सद्भाव के बंधन को और मज़बूती प्रदान करेगा। सबको बहुत-बहुत शुभकामनाएँ ।
मेरे प्यारे देशवासियो ! आप सबका बहुत-बहुत धन्यवाद। फिर एक बार अगले महीने ‘मन की बात’ में मिलेंगे।
"""

# Prompt (can be tuned)
prompt = f"Code-mix this Hindi paragraph using English but keep the meaning same: {bengali_sentence}"

# Generate
output = pipe(prompt, do_sample=True, temperature=0.9)
print("Output:", output)

tokenizer_config.json:   0%|          | 0.00/529 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/649 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/261 [00:00<?, ?B/s]

Device set to use cuda:0

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "facebook/mbart-large-50-many-to-many-mmt"

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Translation task
tgt_lang = "Hinglish"
input_txt = """
नमस्कार !
‘मन की बात’ के माध्यम से फिर एक बार आप सबसे रूबरू होने का अवसर मिला है। आप लोगों को भलीभांति याद होगा नौ-सेना की 6 महिला कमांडरों, ये एक दल पिछले कई महीनों से समुद्र की यात्रा पर था। ‘नाविका सागर परिक्रमा’ – जी मैं उनके विषय में कुछ बात करना चाहता हूँ। भारत की इन 6 बेटियों ने, उनकी इस team ने Two Hundred And Fifty Four Days- 250 से भी ज़्यादा दिनसमुद्र के माध्यम से INSV तारिणी में पूरी दुनिया की सैर कर 21 मई को भारत वापस लौटी हैं और पूरे देश ने उनका काफी गर्मजोशी से स्वागत किया। उन्होंने विभिन्न महासागरों और कई समुद्रों में यात्रा करते हुए लगभग बाईस हज़ार nautical miles की दूरी तय की। यह विश्व में अपने आप में एक पहली घटना थी। गत बुधवार को मुझे इन सभी बेटियों से मिलने का, उनके अनुभव सुनने का अवसर मिला। मैं एक बार फिर इन बेटियों कोउनके adventure को, Navy की प्रतिष्ठा को बढ़ाने के लिए, भारत का मान-सम्मान बढ़ाने के लिये और विशेषकर दुनिया को भी लगे कि भारत की बेटियाँ कम नहीं हैं – ये सन्देश पहुँचाने के लिए बहुत-बहुत बधाई देता हूँ। Sense of adventure कौन नहीं जानता है। अगर हम मानव जाति की विकास यात्रा देखें तो किसी-न-किसी adventure की कोख में ही प्रगति पैदा हुई है। विकास adventure की गोद में ही तो जन्म लेता है। कुछ कर गुजरने का इरादा, कुछ लीक से हटकर के करने का मायना, कुछ extra ordinary करने की बात, मैं भी कुछ कर सकता हूँ – ये भाव,करने वाले भले कम हों, लेकिन युगों तक, कोटि-कोटि लोगों को प्रेरणा मिलती रहती है। पिछले दिनों आपने देखा होगा Mount Everest पर चढ़ने वालों के विषय में कई नयी-नयी बातें ध्यान में आयी हैं और सदियों से Everest मानव जाति को ललकारता रहा और बहादुर लोग उस चुनौती को स्वीकारते भी रहे हैं ।
16 मई को महाराष्ट्र के चंद्रपुर के एक आश्रम-स्कूल के 5 आदिवासी बच्चों ने tribal students – मनीषा धुर्वे, प्रमेश आले, उमाकान्त मडवी, कविदास कातमोड़े, विकास सोयाम – इन हमारे आदिवासी बच्चों के एक दल ने दुनिया की सबसे ऊँची चोटी पर चढ़ाई की। आश्रम-स्कूल के इन छात्रों ने अगस्त 2017 में training शुरू की थी। वर्धा, हैदराबाद, दार्जिलिंग, लेह, लद्दाख – इनकी training हुई। इन युवाओं को ‘मिशन शौर्य’ के तहत चुना गया थाऔर नाम के ही अनुरूप Everest फतह कर उन्होंने पूरे देश को गौरवान्वित किया है। मैं चंद्रपुर के स्कूल के लोगों को, इन मेरे नन्हे-मुन्हे साथियों को, ह्रदय से बहुत-बहुत बधाई देता हूँ। हाल ही में 16 वर्षीय शिवांगी पाठक, नेपाल की ओर से Everest फ़तह करने वाली सबसे कम उम्र की भारतीय महिला बनी। बेटी शिवांगी को बहुत-बहुत बधाई।
अजीत बजाज और उनकी बेटी दीयाEverest की चढ़ाई करने वाली पहली भारतीय पिता-पुत्री की जोड़ी बन गयी। ऐसा ही नहीं कि केवल युवा ही Everest की चढ़ाई कर रहे हैं। संगीता बहल ने 19 मई को Everest की चढ़ाई की और संगीता बहल की आयु 50 से भी अधिक है। Everest पर चढ़ाई करने वाले कुछ ऐसे भी हैं, जिन्होंने दिखाया कि उनके पास न केवल skill है बल्कि वे sensitive भी हैं। अभी पिछले दिनों ‘स्वच्छ गंगा अभियान’ के तहत BSF के एक group ने Everest की चढ़ाई की,पर पूरी team Everest से ढ़ेर सारा कूड़ा अपने साथ नीचे उतार कर लायी। यह कार्य प्रशंसनीय तो है ही, साथ-ही-साथ यह स्वच्छता के प्रति, पर्यावरण के प्रति उनकी प्रतिबद्धता को भी दर्शाता है। वर्षों से लोग Everest की चढ़ाई करते रहे हैं और ऐसे कई लोग हैं, जिन्होंने सफलतापूर्वक इसे पूरा किया है। मैं इन सभी साहसी वीरों को, ख़ासकर के बेटियों को ह्रदय से बहुत-बहुत बधाई देता हूँ।
मेरे प्यारे देशवासियो और ख़ासकर के मेरे नौजवान दोस्तो ! अभी दो महीने पहले जब मैंने fit India की बात की थी तो मैंने नहीं सोचा था कि इस पर इतना अच्छा response आएगा। इतनी भारी संख्या में हर क्षेत्र से लोग इसके support में आगे आएँगे। जब में fit India की बात करता हूँ तो मैं मानता हूँ कि जितना हम खेलेंगे, उतना ही देश खेलेगा। social media पर लोग Fitness Challenge की videos share कर रहे हैं, उसमें एक-दूसरे को tag कर उन्हें challenge कर रहे हैं। Fit India के इस अभियान से आज हर कोई जुड़ रहा है। चाहे फिल्म से जुड़े लोग हों, sports से जुड़े लोग हों या देश के आम-जन, सेना के जवान हों, स्कूल की टीचर हों, चारों तरफ़ से एक ही गूँज सुनाई दे रही है – ‘हम fit तो India fit’। मेरे लिए खुशी की बात है कि मुझे भी भारतीय क्रिकेट टीम के कप्तान विराट कोहली जी ने challenge किया है और मैंने भी उनके challenge को स्वीकार किया है। मैं मानता हूँ कि ये बहुत अच्छी चीज है और इस तरह का challenge हमें fit रखने और दूसरों को भी fit रहने के लिए प्रोत्साहित करेगा ।
मेरे प्यारे देशवासियो! ‘मन की बात’ में कई बार खेल के संबंध में, खिलाडियों के संबंध में, कुछ-न-कुछ बातें आपने मेरे से सुनी ही हैं और पिछली बार तो Commonwealth Games के हमारे नायक, अपनी मन की बातें, इस कार्यक्रम के माध्यम से हमें बता रहे थे –
“नमस्कार सर ! मैं छवि यादव नोएडा से बोल रही हूँ, मैं आपकी ‘मन की बात’ की regular listener हूँ और आज आपसे अपनी मन की बात करना चाहती हूँ. आजकल गर्मी की छुट्टियाँ शुरू हो गयी हैं और एक माँ होने के नाते मैं देख रही हूँ कि बच्चे ज़्यादातर समय इंटरनेट games खेलते हुए बिताते हैं, जब कि जब हम छोटे थे तो हम Traditional Games जो कि ज़्यादातर Outdoor gamesहोते थे, वो खेलते थे, जैसा कि एक game था जिसमें 7 पत्थर के टुकड़े एक के ऊपर एक रखके उसे ball से मारते थे और ऊँच-नीच होता था, खो-खो, ये सब gameजो आजकल खो से गए हैं। मेरा ये निवेदन है कि आप आजकल की generation को कुछ traditional games के बारे में बताएं, जिससे उनकी भी रूचि इस तरफ़ बढ़े, धन्यवाद । ”
छवि यादव जी, आपके phone call के लिए आपका बहुत धन्यवाद। ये बात सही है कि जो खेल कभी गली-गली, हर बच्चे के जीवन का हिस्सा होते थे, वे आज कम होते जा रहे हैं। ये खेल ख़ासकर गर्मी की छुट्टियों का विशेष हिस्सा होते थे। कभी भरी दोपहरी में, तो कभी रात में खाने के बाद बिना किसी चिंता के, बिल्कुल बेफिक्र होकर के बच्चे घंटो-घंटो तक खेला करते थे और कुछ खेल तो ऐसे भी हैं,जो पूरा परिवार साथ में खेला करता था – पिट्ठू हो या कंचे हो, खो-खो हो,लट्टू हो या गिल्ली-डंडा हो, न जाने…..अनगिनत खेल कश्मीर से कन्याकुमारी, कच्छ से कामरूप तक हर किसी के बचपन का हिस्सा हुआ करते थे। हाँ, यह हो सकता है कि अलग-अलग जगह वो अलग-अलग नामों से जाने जाते थे, जैसे अब पिट्ठू ही यह खेल कई नामों से जाना जाता है। कोई उसे लागोरी, सातोलिया, सात पत्थर, डिकोरी, सतोदिया न जाने कितने नाम हैं एक ही खेल के। परंपरागत खेलों में दोनों तरह के खेल हैं। out door भी हैं, indoor भी हैं। हमारे देश कीविविधताके पीछे छिपी एकता इन खेलों में भी देखी जा सकती है। एक ही खेल अलग-अलग जगह, अलग-अलग नामों से जाना जाता है। मैं गुजरात से हूँ मुझे पता है गुजरात में एक खेल है, जिसे चोमल-इस्तो कहते हैं। ये कोड़ियों या इमली के बीज या dice के साथ और 8×8 के square board के साथ खेला जाता है। यह खेल लगभग हर राज्य में खेला जाता था। कर्नाटक में इसे चौकाबारा कहते थे, मध्यप्रदेश में अत्तू। केरल में पकीड़ाकाली तो महाराष्ट्र में चम्पल, तो तमिलनाडु में दायाम और थायाम, तो कहीं राजस्थान में चंगापो न जाने कितने नाम थे लेकिन खेलने के बाद पता चलता है, हर राज्य वाले को भाषा भले न जानता हो – अरे वाह! ये खेल तो हम भी करते थे। हम में से कौन होगा, जिसने बचपन में गिल्ली-डंडा न खेला हो। गिल्ली-डंडा तो गाँव से लेकर शहरों तक में खेले जाने वाला खेल है। देश के अलग-अलग भागों में इसे अलग-अलग नामों से जाना जाता है। आंध्रप्रदेश में इसे गोटिबिल्ला या कर्राबिल्ला के नाम से जानते हैं। उड़ीसा में उसे गुलिबाड़ी कहते हैं तो महाराष्ट्र में इसे वित्तिडालू कहते हैं। कुछ खेलों काअपना एक season होता है। जैसे पतंग उड़ाने का भी एक season होता है। जब हर कोई पतंग उड़ाता है जब हम खेलते हैं, हम में जो unique qualities होती हैं, हम उन्हें freely express कर पाते हैं। आपने देखा होगा कई बच्चे, जो शर्मीले स्वभाव के होते हैं लेकिन खेलते समय बहुत ही चंचल हो जाते हैं। ख़ुद को express करते हैं, बड़े जो गंभीर से दिखते हैं, खेलते समय उनमें जो एक बच्चा छिपा होता है, वो बाहर आता है। पारंपरिक खेल कुछ इस तरह से बने हैं कि शारीरिक क्षमता के साथ-साथ वो हमारी logical thinking, एकाग्रता, सजगता, स्फूर्ति को भी बढ़ावा देते हैं। और खेल सिर्फ खेल नहीं होते हैं, वह जीवन के मूल्यों को सिखाते हैं। लक्ष्य तय करना, दृढ़ता कैसे हासिल करना!, team spirit कैसे पैदा होना, परस्पर सहयोग कैसे करना। पिछले दिनों मैं देख रहा था कि Business Management से जुड़े हुए training programmes में भी overall personality development और interpersonal skills के improvement के लिए भी हमारे जो परंपरागत खेल थे, उसका आजकल उपयोग हो रहा है और बड़ी आसानी से overall development में हमारे खेल काम आ रहे हैं और फिर इन खेलों को खेलने की कोई उम्र तो है ही नहीं। बच्चों से ले करके दादा-दादी, नाना-नानी जब सब खेलते हैं तो यह जो कहते हैं न generation gap,अरे वो भी छू-मंतर हो जाता है। साथ-ही-साथ हम अपनी संस्कृति और परम्पराओं को भी जानते हैं। कई खेल हमें समाज, पर्यावरण आदि के बारे में भी जागरूक करते हैं। कभी-कभी चिंता होती है कि कहीं हमारे यह खेल खो न जाएँ और वह सिर्फ खेल ही नहीं खो जाएगा, कहीं बचपन ही खो जाएगा और फिर उस कविताओं को हम सुनते रहेंगे –
यह दौलत भी ले लो
यह शौहरत भी ले लो
भले छीन लो मुझसे मेरी जवानी
मगर मुझको लौटा दो बचपन का सावन
वो कागज की कश्ती, वो बारिश का पानी

यही गीत हम सुनते रह जाएँगे और इसीलिए यह पारंपरिक खेल, इसको खोना नहीं हैआज आवश्यकता है कि स्कूल, मौहल्ले,युवा-मंडल आगे आकर इन खेलों को बढ़ावा दें। crowd sourcing के द्वारा हम अपने पारंपरिक खेलों का एक बहुत बड़ा archive बना सकते हैं। इन खेलों के videos बनाए जा सकते हैं, जिनमें खेलों के नियम, खेलने के तरीके के बारे में दिखाया जा सकता है। Animation फ़िल्में भी बनाई जा सकती हैं ताकि हमारी जो नई पीढ़ी है, जिनके लिए यह गलियों में खेले जाने वाले खेल कभी-कभी अज़ूबा होता है – वह देखेंगे, खेलेंगे, खिलेंगे।
मेरे प्यारे देशवासियो ! आने वाले 5 जून को हमारा देश भारत आधिकारिक तौर पर World Environment Day Celebration विश्व पर्यावरण दिवस को भारत host करेगा। यह भारत के लिए एक बहुत महत्वपूर्ण उपलब्धि है और यह जलवायु परिवर्तन को कम करने की दिशा में विश्व में भारत के बढ़ते नेतृत्व को भी स्वीकृति मिल रही है – इसका परिचायक है। इस बार की theme है ‘Beat Plastic Pollution’। मेरी आप सभी से अपील है, इस theme के भाव को, इसके महत्व को समझते हुए हम सब यह सुनिश्चित करें कि हमpolythene, low grade plastic का उपयोग न करें और Plastic Pollution का जो एक negative impact हमारी प्रकृति पर, wild life पर और हमारे स्वास्थ्य पर पड़ रहा है, उसे कम करने का प्रयास करें। World Environment Day की website wed-india2018 पर जाएँ और वहाँ ढ़ेर सारे सुझाव बड़े ही रोचक ढ़ंग से दिए गए हैं – देखें, जानें और उन्हें अपने रोजमर्रा के जीवन में उतारने का प्रयास करें। जब भयंकर गर्मी होती है, बाढ़ होती है। बारिश थमती नहीं है। असहनीय ठंड पड़ जाती है तो हर कोई expert बन करके global warming, climate change इसकी बातें करता है लेकिन क्या बातें करने से बात बनती है क्या? प्रकृति के प्रति संवेदनशील होना, प्रकृति की रक्षा करना, यह हमारा सहज स्वभाव होना चाहिए, हमारे संस्कारों में होना चाहिए। पिछले कुछ हफ़्तों में हम सभी ने देखा कि देश के अलग-अलग क्षेत्रों में धूल-आँधी चली, तेज़ हवाओं के साथ-साथ भारी वर्षा भी हुई, जो कि unseasonal है। जान-हानि भी हुई, माल-हानि भी हुई। यह सारी चीज़ें मूलतः weather pattern में जो बदलाव है, उसी का परिणाम है हमारी संस्कृति, हमारी परंपरा ने हमें प्रकृति के साथ संघर्ष करना नहीं सिखाया है। हमें प्रकृति के साथ सदभाव से रहना है, प्रकृति के साथ जुड़ करके रहना है। महात्मा गाँधी ने तो जीवन भर हर कदम इस बात की वकालत की थी। जब आज भारत climate justice की बात करता है। जब भारत ने Cop21 और Paris समझौते में प्रमुख भूमिका निभाई। जब हमनें International Solar Alliance के माध्यम से पूरी दुनिया को एकजुट किया तो इन सबके मूल में महात्मा गाँधी के उस सपने को पूरा करने का एक भाव था। इस पर्यावरण दिवस पर हम सब इस बारे में सोचें कि हम अपने planet को स्वच्छ और हरित बनाने के लिए क्या कर सकते हैं? किस तरह इस दिशा में आगे बढ़ सकते हैं? क्या innovative कर सकते हैं? बारिश का मौसम आने वाला है,हम इस बार record वृक्षारोपण का लक्ष्य ले सकते हैं और केवल वृक्ष लगाना ही नहीं बल्कि उसके बड़े होने तक उसके रख-रखाव की व्यवस्था करना।

मेरे प्यारे देशवासियो और विशेषकर के मेरे नौजवान साथियो ! आप 21 जून को बराबर अब याद रखते हैं, आप ही नहीं, हम ही नहीं सारी दुनिया 21 जून को याद रखती है। पूरे विश्व के लिए 21 जून अंतर्राष्ट्रीय योग दिवस के रूप में मनाया जाता है और ये सर्व-स्वीकृत हो चुका है और लोग महीनों पहले तैयारियाँ शुरू कर देते हैं। इन दिनों ख़बर मिल रही है, सारी दुनिया में 21 जून को अंतर्राष्ट्रीय योग दिवस मनाने की भरसक तैयारियाँ चल रही हैं। Yoga For Unity और harmonious society का ये वो सन्देश है, जो विश्व ने पिछले कुछ वर्षों से बार-बार अनुभव किया है। संस्कृत के महान कवि भर्तृहरि ने सदियों पहले अपने शतकत्रयम् में लिखा था –
धैर्यं यस्य पिता क्षमा च जननी शान्तिश्चिरं गेहिनी
सत्यं सूनुरयं दया च भगिनी भ्राता मनः संयमः।
शय्या भूमितलं दिशोSपि वसनं ज्ञानामृतं भोजनं
एते यस्य कुटिम्बिनः वद सखे कस्माद् भयं योगिनः।।

सदियों पहले ये कही गई बात का सीधा-सीधा मतलब है कि नियमित योगा अभ्यास करने पर कुछ अच्छे गुण सगे-सम्बन्धियों और मित्रों की तरह हो जाते हैं। योग करने से साहस पैदा होता है जो सदा ही पिता की तरह हमारी रक्षा करता है। क्षमा का भाव उत्पन्न होता है जैसा माँ का अपने बच्चों के लिए होता है और मानसिक शांति हमारी स्थायी मित्र बन जाती है। भर्तृहरि ने कहा है कि नियमित योग करने से सत्य हमारी संतान, दया हमारी बहन, आत्मसंयम हमारा भाई, स्वयं धरती हमारा बिस्तर और ज्ञान हमारी भूख मिटाने वाला बन जाता है। जब इतने सारे गुण किसी के साथी बन जाएँ तो योगी सभी प्रकार के भय पर विजय प्राप्त कर लेता है। एक बार फिर मैं सभी देशवासियों से अपील करता हूँ कि वे योग की अपनी विरासत को आगे बढ़ायें और एक स्वस्थ, खुशहाल और सद्भावपूर्ण राष्ट्र का निर्माण करें।
मेरे प्यारे देशवासियो ! आज 27 मई है। भारत के प्रथम प्रधानमंत्री पंडित जवाहरलाल नेहरु जी की पुण्यतिथि है। मैं पंडित जी को प्रणाम करता हूँ। इस मई महीने की याद एक और बात से भी जुड़ी है और वो है वीर सावरकर। 1857 में ये मई का ही महीना था, जब भारतवासियों ने अंग्रेजों को अपनी ताकत दिखाई थी। देश के कई हिस्सों में हमारे जवान और किसान अपनी बहादुरी दिखाते हुए अन्याय के विरोध में उठ खड़े हुए थे। दुःख की बात है कि हम बहुत लम्बे समय तक 1857 की घटनाओं को केवल विद्रोह या सिपाही विद्रोह कहते रहे। वास्तव में उस घटना को न केवल कम करके आँका गया बल्कि यह हमारे स्वाभिमान को धक्का पहुँचाने का भी एक प्रयास था। यह वीर सावरकर ही थे, जिन्होंने निर्भीक हो के लिखा कि 1857 में जो कुछ भी हुआ वो कोई विद्रोह नहीं था बल्कि आजादी की पहली लड़ाई थी। सावरकर सहित लंदन के India House के वीरों ने इसकी 50वीं वर्षगांठ धूमधाम से मनाई। यह भी एक अद्भुत संयोग है कि जिस महीने में स्वतंत्रता का पहला स्वतंत्र संग्राम आरंभ हुआ, उसी महीने में वीर सावरकर जी का जन्म हुआ। सावरकर जी का व्यक्तित्व विशेषताओं से भरा था; शस्त्र और शास्त्र दोनों के उपासक थे। आमतौर पर वीर सावरकर को उनकी बहादुरी और ब्रिटिशराज के खिलाफ़ उनके संघर्ष के लिए जानते हैं लेकिन इन सबके अलावा वे एक ओज़स्वी कवि और समाज सुधारक भी थे, जिन्होंने हमेशा सद्भावना और एकता पर बल दिया। सावरकर जी के बारे में एक अद्भुत वर्णन हमारे प्रिय आदरणीय अटल बिहारी वाजपेयी जी ने किया है। अटल जी ने कहा था – सावरकर माने तेज़, सावरकर माने त्याग, सावरकर माने तप, सावरकर माने तत्व, सावरकर माने तर्क, सावरकर माने तारुण्य, सावरकर माने तीर, सावरकर माने तलवार। कितना सटीक चित्रण किया था अटल जी ने। सावरकर कविता और क्रांति दोनों को साथ लेकर चले। संवेदनशील कवि होने के साथ-साथ वे साहसिक क्रांतिकारी भी थे।

मेरे प्यारे भाइयो-बहनो ! मैं टी.वी. पर एक कहानी देख रहा था। राजस्थान के सीकर की कच्ची बस्तियों की हमारी ग़रीब बेटियों की। हमारी ये बेटियाँ, जो कभी कचराबीनने से लेकर घर-घर माँगने को मजबूर थीं – आज वें सिलाई का काम सीख कर ग़रीबों का तन ढ़कने के लिए कपड़े सिल रही हैं। यहाँ की बेटियाँ, आज अपने और अपने परिवार के कपड़ों के अलावा सामान्य से लेकर अच्छे कपड़े तक सिल रही हैं। वे इसके साथ-साथ कौशल विकास का course भी कर रही हैं। हमारी ये बेटियाँ आज आत्मनिर्भर बनी हैं। सम्मान के साथ अपना जीवन जी रही है और अपने-अपने परिवार के लिए एक ताक़त बन गई है। मैं आशा और विश्वास से भरी हमारी इन बेटियों को उनके उज्ज्वल भविष्य की शुभकामनाएँ देता हूँ। इन्होंने दिखाया है कि अगर कुछ कर दिखाने का जज़्बा हो और उसके लिए आप कृतसंकल्पित हों तो तमाम मुश्किलों के बीच भी सफलता हासिल की जा सकती है और ये सिर्फ सीकर की बात नहीं है हिन्दुस्तान के हर कोने में आपको ये सब देखने को मिलेगा। आपके पास, अड़ोस-पड़ोस में नज़र करोगे तो ध्यान में आएगा कि लोग किस प्रकार से परेशानियों को परास्त करते हैं। आपने महसूस किया होगा कि जब भी हम किसी चाय की दुकान पर जाते हैं, वहाँ की चाय का आनंद लेते हैं तो साथ के कुछ लोगों से चर्चा और विचार-विमर्श भी होता ही है। ये चर्चा राजनीतिक भी होती है, सामाजिक भी होती है, चलचित्र की भी होती है, खेल और खिलाड़ियों की भी होती है, देश की समस्याओं पर भी होती है – कि ऐसी समस्या है – इसका समाधान ऐसे होगा – ये करना चाहिए लेकिन अक्सर ये चीज़ें सिर्फ चर्चा तक सीमित रह जाती हैं लेकिन कुछ लोग ऐसे होते हैं, जो अपने कार्यों से, अपनी मेहनत और लगन से बदलाव लाने की दिशा में आगे बढ़ते हैं, उसेहकीकत का रूप देते हैं। दूसरों के सपनों को अपना बना लेने वाले और उन्हें पूरा करने के लिए खुद को खपा देने की कुछ ऐसी ही कहानी उड़ीसा के कटक शहर के झुग्गी-झोपड़ी में रहने वाले डी. प्रकाश राव की। कल ही मुझे डी. प्रकाश राव से मिलने का सोभाग्य मिला। श्रीमान् डी. प्रकाश राव पिछले पाँच दशक से शहर में चाय बेच रहे हैं। एक मामूली सी चाय बेचने वाला, आज आप जानकर हैरान हो जायेंगे 70 से अधिक बच्चों के जीवन में शिक्षा का उजियारा भर रहा है। उन्होंने बस्ती और झुग्गियों में रहने वाले बच्चों के लिए ‘आशा आश्वासन’ नाम का एक स्कूल खोला। जिस पर ये ग़रीब चाय वाला अपनी आय का 50% धन उसी में खर्च कर देता है। वे स्कूल में आने वाले सभी बच्चों को शिक्षा, स्वास्थ्य और भोजन की पूरी व्यवस्था करते हैं। में डी. प्रकाश राव की कड़ी मेहनत, उनकी लगन और उन ग़रीब बच्चों के जीवन को नयी दिशा देने के लिए बहुत-बहुत बधाई देता हूँ। उन्होंने उनकी ज़िन्दगी के अँधेरे को समाप्त कर दिया है। ‘तमसो मा ज्योतिर्गमय’ ये वेद-वाक्य कौन नहीं जानता है लेकिन उसको जी करके दिखाया है डी. प्रकाश राव ने। उनकी जीवन हम सभी के लिए, समाज और पूरे देश के लिए एक प्रेरणा है। आप के भी अगल-बगल में ऐसी प्रेरक घटनाओं की श्रृंखला होगी। अनगिनत घटनाएँ होंगी। आइये हम सकारात्मकता को आगे बढाएं ।
जून के महीने में इतनी अधिक गर्मी होती है कि लोग बारिश का इंतज़ार करते हैं और इस उम्मीद में आसमान में बादलों की ओर टकटकी लगाये देखते हैं। अब से कुछ दिनों बाद लोग चाँद की भी प्रतीक्षा करेंगे। चाँद दिखाई देने का अर्थ यह है कि ईद मनाई जा सकती है। रमज़ानके दौरान एक महीने के उपवास के बाद ईद का पर्व जश्न की शुरुआत का प्रतीक है। मुझे विश्वास है कि सभी लोग ईद को पूरे उत्साह से मनायेंगे। इस अवसर पर बच्चों को विशेष तौर पर अच्छी ईदी भी मिलेगी। आशा करता हूँ कि ईद का त्योहार हमारे समाज में सद्भाव के बंधन को और मज़बूती प्रदान करेगा। सबको बहुत-बहुत शुभकामनाएँ ।
मेरे प्यारे देशवासियो ! आप सबका बहुत-बहुत धन्यवाद। फिर एक बार अगले महीने ‘मन की बात’ में मिलेंगे।
"""


# Chat-style message prompt
messages = [
    {"role": "system", "content": f"Translate the text below to {tgt_lang} and do code mixing in english and hindi."},
    {"role": "user", "content": input_txt}
]

# Apply chat template to structure the conversation
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

# Tokenize and move input to model device
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

# Generate the output
generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=1024,
    do_sample=True,
    temperature=0.01,
    num_return_sequences=1
)
output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist()
output_text = tokenizer.decode(output_ids, skip_special_tokens=True)

print("Input:", input_txt)
print("Translation:", output_text)

In [ ]:
!pip install transformers accelerate bitsandbytes torch pandas sentence-transformers bnltk

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.8.1)
Collecting bitsandbytes
  Downloading bitsandbytes-0.46.0-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Collecting bnltk
  Downloading bnltk-0.7.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Collecting black==24.10.0 (from bnltk)
  Downloading black-24.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 7.1 MB/s eta 0:00:00
Collecting keras==3.6.0 (from bnltk)
  Downloading keras-3.6.0-py3-none-any.whl.metadata (5.8 kB)
Collecting scikit-learn (from sentence-transformers)
  Downloading scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: tensorflow==2.18.0 in /usr/local/lib/python3.11/dist-packages (from bnltk) (2.18.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (8.2.1)
Collecting mypy-extensions>=0.4.3 (from black==24.10.0->bnltk)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=0.9.0 (from black==24.10.0->bnltk)
  Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (4.3.8)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.16.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.6.15)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (5.29.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (3.1.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.73.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (2.18.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.37.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow==2.18.0->bnltk) (0.45.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (3.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras==3.6.0->bnltk) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras==3.6.0->bnltk) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras==3.6.0->bnltk) (0.1.2)
Downloading bitsandbytes-0.46.0-py3-none-manylinux_2_24_x86_64.whl (67.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 9.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 5.1 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 68.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 63.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 27.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 7.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 17.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.3 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 26.8 MB/s eta 0:00:00
Downloading bnltk-0.7.8-py3-none-any.whl (15 kB)
Downloading black-24.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 47.3 MB/s eta 0:00:00
Downloading keras-3.6.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 39.2 MB/s eta 0:00:00
Downloading scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 50.4 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Installing collected packages: pathspec, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, mypy-extensions, scikit-learn, nvidia-cusparse-cu12, nvidia-cudnn-cu12, black, nvidia-cusolver-cu12, keras, bnltk, bitsandbytes
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: keras
    Found existing installation: keras 3.8.0
    Uninstalling keras-3.8.0:
      Successfully uninstalled keras-3.8.0
Successfully installed bitsandbytes-0.46.0 black-24.10.0 bnltk-0.7.8 keras-3.6.0 mypy-extensions-1.1.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 pathspec-0.12.1 scikit-learn-1.5.2

In [ ]:
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from tqdm.auto import tqdm
from sentence_transformers import SentenceTransformer
from bnltk.tokenize.bn_word_tokenizers import Tokenizers
from bnltk.pos_tagger import PosTagger

In [ ]:
from bnltk.bnltk_downloads.file_downloader import DataFiles

In [ ]:
DataFiles.download()

Downloading....../bn_tagged_mod.txt
[==================================================]Downloading....../pos_tagger.weights.h5
[==================================================]Done!

In [ ]:
# Configuration
MODEL_NAME = "Qwen/Qwen2.5-Coder-3B-Instruct"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 1  # Reduce if OOM errors occur
MAX_LENGTH = 256
REPLACE_RATIO = 0.35 # % of content words to replace

In [ ]:
# Load Bengali NLP tools
bn_tokenizer = Tokenizers()
pos_tagger = PosTagger()

In [ ]:
# Load semantic similarity model (for validation)
semantic_model = SentenceTransformer('sentence-transformers/LaBSE', device=DEVICE)

modules.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.88G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

In [ ]:
!pip install flash_attn

Collecting flash_attn
  Downloading flash_attn-2.8.0.post2.tar.gz (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 69.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from flash_attn) (2.6.0+cu124)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from flash_attn) (0.8.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->flash_attn) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->flash_attn) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->flash_attn) (3.0.2)
Building wheels for collected packages: flash_attn
  Building wheel for flash_attn (setup.py) ... done
  Created wheel for flash_attn: filename=flash_attn-2.8.0.post2-cp311-cp311-linux_x86_64.whl size=255936976 sha256=e7e8fd0d50112e3302a96fcd5b5ae4606bd38c20a1149fc666fed5c87ba5a9c7
  Stored in directory: /root/.cache/pip/wheels/a2/75/55/57ba1e272fd7fa1a01d9ba6b5334b7adaabf79900ede22c040
Successfully built flash_attn
Installing collected packages: flash_attn
Successfully installed flash_attn-2.8.0.post2

In [ ]:
# Load Qwen model with 4-bit quantization for memory efficiency
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    attn_implementation="flash_attention_2"
)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.21G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

In [ ]:
# Create generation pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=MAX_LENGTH,
    temperature=0.3,
    top_p=0.95,
    repetition_penalty=1.15
)

NameError: name 'pipeline' is not defined

In [ ]:
def generate_code_mixed_sentence(bn_sentence: str) -> str:
    """Generate code-mixed version using Qwen with instruction prompting"""
    prompt = f"""তুমি একজন বাংলা-ইংলিশ কোড-মিক্সিং বিশেষজ্ঞ। নিচের বাংলা বাক্যটিকে বাংলা এবং ইংরেজির মিশ্রণে রূপান্তর কর,
    যেখানে ৩০-৪০% কন্টেন্ট শব্দ (বিশেষ্য, ক্রিয়া, বিশেষণ) ইংরেজিতে রূপান্তর করবে। কার্যকরী শব্দ (অব্যয়, সর্বনাম, বিভক্তি) বাংলায় রাখবে।
    অর্থ অপরিবর্তিত রাখতে হবে। শুধুমাত্র রূপান্তরিত বাক্যটি আউটপুট দেবে।

    ইনপুট: {bn_sentence}
    আউটপুট:"""

    response = generator(
        prompt,
        num_return_sequences=1,
        pad_token_id=tokenizer.eos_token_id
    )

    # Extract generated text after prompt
    return response[0]['generated_text'].split("আউটপুট:")[-1].strip()

def validate_semantics(original: str, mixed: str, threshold=0.75) -> bool:
    """Ensure semantic similarity using LaBSE embeddings"""
    emb_orig = semantic_model.encode(original)
    emb_mixed = semantic_model.encode(mixed)
    similarity = torch.nn.functional.cosine_similarity(
        torch.tensor(emb_orig),
        torch.tensor(emb_mixed),
        dim=0
    )
    return similarity.item() > threshold

def augment_dataset(df: pd.DataFrame, text_column="bengali_text") -> pd.DataFrame:
    """Process DataFrame to generate code-mixed versions"""
    results = []

    for i in tqdm(range(0, len(df), BATCH_SIZE)):
        batch = df.iloc[i:i+BATCH_SIZE]
        batch_results = []

        for _, row in batch.iterrows():
            original_text = row[text_column]

            try:
                # Generate code-mixed version
                mixed_text = generate_code_mixed_sentence(original_text)

                # Validate semantics
                if validate_semantics(original_text, mixed_text):
                    batch_results.append({
                        "original": original_text,
                        "code_mixed": mixed_text,
                        "similarity_score": "valid"
                    })
                else:
                    batch_results.append({
                        "original": original_text,
                        "code_mixed": "VALIDATION_FAILED",
                        "similarity_score": "invalid"
                    })
            except Exception as e:
                batch_results.append({
                    "original": original_text,
                    "code_mixed": f"ERROR: {str(e)}",
                    "similarity_score": "error"
                })

        results.extend(batch_results)

    return pd.DataFrame(results)

In [ ]:
df

   Row                                               text
0    1  আমার নাম রাহুল এবং আমি কলকাতায় থাকি। প্রতিদিন...
1    2  আজ আকাশ মেঘলা, বাতাস বইছে এবং বৃষ্টি নামবে মনে...
2    3  আমি বই পড়তে খুব ভালোবাসি, বিশেষ করে বাংলা সাহ...
3    4  সে প্রতিদিন সকালে স্কুলে যায়। আগে সে ব্যাগ গো...
4    5  তারা ফুটবল খেলছে মাঠে। দলবদ্ধভাবে সবাই খুব উৎস...
5    6  আমরা একটি শিক্ষা সফরে গিয়েছিলাম। সারা দিন নান...
6    7  মা আজ নতুন রান্না করেছেন। বাসায় এলেই গন্ধে মন...
7    8  বইমেলায় অনেক মানুষ এসেছে। নতুন নতুন বই দেখা য...

In [ ]:
# ======================
# Execution Pipeline
# ======================

# Assuming your DataFrame is loaded as:
df = pd.read_csv("dummy.csv")

# Process dataset
result_df = augment_dataset(df, text_column="text")

# Filter successful conversions
valid_df = result_df[result_df['similarity_score'] == "valid"]

# Save results
valid_df.to_csv("code_mixed_dataset.csv", index=False)
print(f"Generated {len(valid_df)} valid code-mixed sentences")

100%|██████████| 8/8 [00:00<00:00, 40.91it/s]

   Row                                               text
0    1  আমার নাম রাহুল এবং আমি কলকাতায় থাকি। প্রতিদিন...
   Row                                               text
1    2  আজ আকাশ মেঘলা, বাতাস বইছে এবং বৃষ্টি নামবে মনে...
   Row                                               text
2    3  আমি বই পড়তে খুব ভালোবাসি, বিশেষ করে বাংলা সাহ...
   Row                                               text
3    4  সে প্রতিদিন সকালে স্কুলে যায়। আগে সে ব্যাগ গো...
   Row                                               text
4    5  তারা ফুটবল খেলছে মাঠে। দলবদ্ধভাবে সবাই খুব উৎস...
   Row                                               text
5    6  আমরা একটি শিক্ষা সফরে গিয়েছিলাম। সারা দিন নান...
   Row                                               text
6    7  মা আজ নতুন রান্না করেছেন। বাসায় এলেই গন্ধে মন...
   Row                                               text
7    8  বইমেলায় অনেক মানুষ এসেছে। নতুন নতুন বই দেখা য...
Generated 0 valid code-mixed sentences

In [ ]:
# ======================
# Fallback Mechanism
# (For failed validations)
# ======================

def contextual_replacement(bn_sentence: str, replace_ratio: float = 0.35) -> str:
    """Rule-based fallback for failed LLM generations"""
    tokens = bn_tokenizer.sentence_tokenize(bn_sentence)
    pos_tags = pos_tagger.bengali_pos(bn_sentence)

    # Identify replaceable content words
    content_words = []
    for token, pos in zip(tokens, pos_tags):
        if pos[1] in ["NN", "VB", "JJ"]:  # Nouns, Verbs, Adjectives
            content_words.append(token)

    # Select words to replace (based on ratio)
    n_replace = max(1, int(len(content_words) * replace_ratio))
    replace_candidates = content_words[:n_replace]

    # Simple dictionary (extend this with your domain terms)
    dictionary = {
        "বই": "book",
        "স্কুল": "school",
        "কলেজ": "college",
        "ছাত্র": "student",
        "শিক্ষক": "teacher",
        "পড়া": "study",
        "খেলা": "play",
        "দৌড়ানো": "run",
        "সুন্দর": "beautiful",
        "বড়": "big"
    }

    # Perform replacements
    mixed_tokens = []
    for token in tokens:
        if token in replace_candidates and token in dictionary:
            mixed_tokens.append(dictionary[token])
        else:
            mixed_tokens.append(token)

    return " ".join(mixed_tokens)

# Apply fallback to failed rows
failed_df = result_df[result_df['similarity_score'] != "valid"]
if not failed_df.empty:
    failed_df['code_mixed'] = failed_df['original'].apply(
        lambda x: contextual_replacement(x, REPLACE_RATIO)
    )
    full_df = pd.concat([valid_df, failed_df])
    full_df.to_csv("full_code_mixed_dataset.csv", index=False)

In [ ]:
!pip install transformers torch sentencepiece accelerate

In [ ]:
from transformers import MT5ForConditionalGeneration, T5Tokenizer
import torch
from tqdm import tqdm

# Load pretrained model and tokenizer
model_name = "sagorsarker/mT5_multilingual_Banglish"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = MT5ForConditionalGeneration.from_pretrained(model_name).to("cuda" if torch.cuda.is_available() else "cpu")

def generate_code_mixed(sentences, temperature=0.7, top_p=0.9):
    """
    Convert Bengali sentences to code-mixed Bengali-English using LLM
    Args:
        sentences: List of Bengali sentences
        temperature: Creativity control (0.1-1.0)
        top_p: Probability threshold for nucleus sampling
    Returns:
        List of code-mixed sentences
    """
    results = []

    # Batch processing for efficiency
    for i in tqdm(range(0, len(sentences), 16)):
        batch = sentences[i:i+16]

        # Tokenize with task prefix
        inputs = tokenizer(
            [f"generate Banglish: {s}" for s in batch],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=128
        ).to(model.device)

        # Generate code-mixed output
        outputs = model.generate(
            **inputs,
            max_length=128,
            temperature=temperature,
            top_p=top_p,
            num_beams=4,
            early_stopping=True
        )

        # Decode with special characters cleanup
        decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        results.extend(decoded)

    return results

# Example usage
if __name__ == "__main__":
    # Load your Bengali dataset (replace with actual loading)
    bengali_sentences = [
        "আমি কাল মার্কেটে যাব",
        "তুমি কেন এত দেরি করছ?",
        "বইটি আমার খুব প্রিয়",
        "আজকে আবহাওয়া খুব ভালো"
    ]

    # Generate code-mixed versions
    mixed_sentences = generate_code_mixed(bengali_sentences)

    # Print results
    print("\nCode-Mixed Outputs:")
    for orig, mixed in zip(bengali_sentences, mixed_sentences):
        print(f"Bengali: {orig}")
        print(f"Mixed  : {mixed}")
        print("-" * 50)

OSError: sagorsarker/mT5_multilingual_Banglish is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
!pip install sentence-transformers bnlp nltk numpy requests

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Collecting bnlp
  Downloading bnlp-0.8.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.52.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.33.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.6.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 41.8 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 21.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 25.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 9.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 48.7 MB/s eta 0:00:00
Building wheels for collected packages: bnlp
  Building wheel for bnlp (setup.py) ... done
  Created wheel for bnlp: filename=bnlp-0.8-py3-none-any.whl size=32802 sha256=a90073c563983a38597b39bc4334f509b9e3a5e0df5d21f56357a5a84c13cc5d
  Stored in directory: /root/.cache/pip/wheels/23/2a/c7/f17cc895ad4feeab04f10a3cf815ab7a7cb2053b53dc47c68a
Successfully built bnlp
Installing collected packages: bnlp, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bnlp-0.8 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
!pip install bnlp_toolkit

Collecting bnlp_toolkit
  Downloading bnlp_toolkit-4.0.3-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (0.2.0)
Collecting gensim==4.3.2 (from bnlp_toolkit)
  Downloading gensim-4.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (2.0.2)
Collecting scipy==1.10.1 (from bnlp_toolkit)
  Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 3.8 MB/s eta 0:00:00
Collecting sklearn-crfsuite==0.3.6 (from bnlp_toolkit)
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting tqdm==4.66.3 (from bnlp_toolkit)
  Downloading tqdm-4.66.3-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.7 MB/s eta 0:00:00
Collecting ftfy==6.2.0 (from bnlp_toolkit)
  Downloading ftfy-6.2.0-py3-none-any.whl.metadata (7.3 kB)
Collecting emoji==1.7.0 (from bnlp_toolkit)
  Downloading emoji-1.7.0.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (2.32.3)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/lib/python3.11/dist-packages (from ftfy==6.2.0->bnlp_toolkit) (0.2.13)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.2->bnlp_toolkit) (7.1.0)
Collecting numpy (from bnlp_toolkit)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.1 MB/s eta 0:00:00
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite==0.3.6->bnlp_toolkit)
  Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (0.9.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (2024.11.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2025.6.15)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.2->bnlp_toolkit) (1.17.2)
Downloading bnlp_toolkit-4.0.3-py3-none-any.whl (22 kB)
Downloading ftfy-6.2.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 3.4 MB/s eta 0:00:00
Downloading gensim-4.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 18.5 MB/s eta 0:00:00
Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 11.8 MB/s eta 0:00:00
Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Downloading tqdm-4.66.3-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 4.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 49.4 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.6 MB/s eta 0:00:00
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171031 sha256=5367e3a7b0ced53609196475264851224206e1d8358ee519b1b2964ed54867a9
  Stored in directory: /root/.cache/pip/wheels/bd/22/e5/b69726d5e1a19795ecd3b3e7464b16c0f1d019aa94ff1c8578
Successfully built emoji
Installing collected packages: emoji, tqdm, python-crfsuite, numpy, ftfy, sklearn-crfsuite, scipy, gensim, bnlp_toolkit
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-image 0.25.2 requires scipy>=1.11.4, but you have scipy 1.10.1 which is incompatible.
jaxlib 0.5.1 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.10.1 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
dataproc-spark-connect 0.7.5 requires tqdm>=4.67, but you have tqdm 4.66.3 which is incompatible.
cvxpy 1.6.6 requires scipy>=1.11.0, but you have scipy 1.10.1 which is incompatible.
jax 0.5.2 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
xarray-einstats 0.9.1 requires scipy>=1.11, but you have scipy 1.10.1 which is incompatible.
Successfully installed bnlp_toolkit-4.0.3 emoji-1.7.0 ftfy-6.2.0 gensim-4.3.2 numpy-1.26.4 python-crfsuite-0.9.11 scipy-1.10.1 sklearn-crfsuite-0.3.6 tqdm-4.66.3

In [ ]:
# -*- coding: utf-8 -*-
import numpy as np
from bnlp import BengaliPOS, NLTKTokenizer
from nltk.corpus import stopwords
import nltk
import requests
import random
from sentence_transformers import SentenceTransformer

# Download required NLTK data
nltk.download('stopwords')

class BengaliEnglishCodeMixer:
    def __init__(self, replace_ratio=0.3, similarity_threshold=0.5):
        self.replace_ratio = replace_ratio
        self.similarity_threshold = similarity_threshold
        self.model = None
        self.english_embeddings = None
        self.english_words = None
        self.pos_tagger = None
        self.tokenizer = None
        self.bengali_stopwords = None

    def initialize(self):
        """Load models and resources"""
        print("Loading LaBSE embedding model...")
        self.model = SentenceTransformer('sentence-transformers/LaBSE')

        print("Initializing Bengali NLP tools...")
        self.pos_tagger = BengaliPOS()
        self.tokenizer = NLTKTokenizer()

        print("Loading English vocabulary...")
        self._load_english_vocab()

        print("Precomputing English embeddings...")
        self.english_embeddings = self.model.encode(self.english_words,
                                                  batch_size=128,
                                                  show_progress_bar=True)
        # Normalize embeddings for efficient cosine similarity
        self.english_embeddings = self.english_embeddings / np.linalg.norm(
            self.english_embeddings, axis=1, keepdims=True)

        print("Loading Bengali stopwords...")
        self._load_bengali_stopwords()

        print("System ready for code mixing")

    def _load_english_vocab(self, vocab_size=5000):
        """Load common English words"""
        url = "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa.txt"
        response = requests.get(url)
        words = response.text.splitlines()
        self.english_words = words[:vocab_size]

    def _load_bengali_stopwords(self):
        """Load Bengali stopwords"""
        url = "https://raw.githubusercontent.com/stopwords-iso/stopwords-bn/master/stopwords-bn.txt"
        response = requests.get(url)
        self.bengali_stopwords = set(response.text.splitlines())

    def _should_replace(self, word, pos_tag):
        """Determine if a word should be considered for replacement"""
        # Define content POS tags: Noun, Verb, Adjective, Adverb
        content_pos = {"NN", "NNP", "NNC", "VM", "VAUX", "JJ", "RB"}

        return (pos_tag in content_pos and
                word not in self.bengali_stopwords and
                len(word) > 2 and  # Avoid short words
                not word.isdigit() and
                random.random() < self.replace_ratio)

    def _find_best_match(self, bengali_word):
        """Find closest English word using cosine similarity"""
        # Get Bengali word embedding
        word_embed = self.model.encode([bengali_word], show_progress_bar=False)[0]
        word_embed = word_embed / np.linalg.norm(word_embed)

        # Compute cosine similarity
        similarities = np.dot(self.english_embeddings, word_embed)
        best_idx = np.argmax(similarities)
        best_similarity = similarities[best_idx]

        return self.english_words[best_idx], best_similarity

    def code_mix_sentence(self, sentence):
        """Perform code mixing on a Bengali sentence"""
        if not self.model:
            self.initialize()

        # Tokenize and POS tag
        tokens = self.tokenizer.sentence_tokenize(sentence)
        pos_tags = self.pos_tagger.tag(sentence)

        # Handle token-POS alignment
        tokenized_sentence = [token for token, _ in tokens]
        pos_tags = [tag for _, tag in pos_tags] if len(pos_tags) == len(tokenized_sentence) else ["UNK"]*len(tokenized_sentence)

        mixed_tokens = []
        for i, (word, pos_tag) in enumerate(zip(tokenized_sentence, pos_tags)):
            if self._should_replace(word, pos_tag):
                try:
                    en_word, similarity = self._find_best_match(word)
                    if similarity >= self.similarity_threshold:
                        # Preserve Bengali suffixes for nouns/verbs
                        if pos_tag in {"NN", "NNP", "NNC", "VM"} and i < len(tokenized_sentence)-1:
                            next_pos = pos_tags[i+1]
                            if next_pos in {"PSP", "CCL", "SFX"}:
                                mixed_tokens.append(en_word + " ")  # Space for suffix attachment
                                continue
                        mixed_tokens.append(en_word)
                        continue
                except Exception as e:
                    print(f"Error processing '{word}': {str(e)}")

            # Keep original word if not replaced
            mixed_tokens.append(word)

        return " ".join(mixed_tokens)

    def code_mix_dataset(self, dataset):
        """Process a list of Bengali sentences"""
        return [self.code_mix_sentence(sentence) for sentence in dataset]

# Example Usage
if __name__ == "__main__":
    # Initialize code mixer (modify parameters as needed)
    mixer = BengaliEnglishCodeMixer(
        replace_ratio=0.4,       # 40% of eligible words replaced
        similarity_threshold=0.6  # Minimum similarity score
    )

    # Bengali input sentences
    bengali_sentences = [
        "আমি কাল বইমেলায় যাব",
        "এই গল্পটি খুব মজার ছিল",
        "কম্পিউটার বিজ্ঞান বিভাগে আমার ভর্তি হয়েছে",
        "আজ রাতের খাবারে মাছ থাকবে"
    ]

    # Perform code mixing
    mixed_sentences = mixer.code_mix_dataset(bengali_sentences)

    # Display results
    print("\nCode Mixed Output:")
    for orig, mixed in zip(bengali_sentences, mixed_sentences):
        print(f"Original: {orig}")
        print(f"Mixed   : {mixed}")
        print()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Loading LaBSE embedding model...
Initializing Bengali NLP tools...
Loading English vocabulary...
Precomputing English embeddings...

Batches:   0%|          | 0/40 [00:00<?, ?it/s]

Loading Bengali stopwords...
System ready for code mixing

ValueError: too many values to unpack (expected 2)

In [ ]:
!pip install sentence-transformers bnltk numpy scikit-learn tqdm
!wget https://www.mit.edu/~ecprice/wordlist.10000 -O english_vocab.txt

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Requirement already satisfied: bnltk in /usr/local/lib/python3.11/dist-packages (0.7.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.5.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.66.3)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.52.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.16.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.33.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: black==24.10.0 in /usr/local/lib/python3.11/dist-packages (from bnltk) (24.10.0)
Requirement already satisfied: keras==3.6.0 in /usr/local/lib/python3.11/dist-packages (from bnltk) (3.6.0)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.11/dist-packages (from bnltk) (2.32.3)
Requirement already satisfied: tensorflow==2.18.0 in /usr/local/lib/python3.11/dist-packages (from bnltk) (2.18.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (8.2.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (24.2)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (0.12.1)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.11/dist-packages (from black==24.10.0->bnltk) (4.3.8)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.16.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras==3.6.0->bnltk) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->bnltk) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->bnltk) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->bnltk) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->bnltk) (2025.6.15)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (5.29.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (3.1.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (1.73.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (2.18.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.18.0->bnltk) (0.37.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow==2.18.0->bnltk) (0.45.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow==2.18.0->bnltk) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras==3.6.0->bnltk) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras==3.6.0->bnltk) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras==3.6.0->bnltk) (0.1.2)
--2025-06-30 13:15:40--  https://www.mit.edu/~ecprice/wordlist.10000
Resolving www.mit.edu (www.mit.edu)... 23.222.38.231, 2a02:26f0:1180:197::255e, 2a02:26f0:1180:183::255e
Connecting to www.mit.edu (www.mit.edu)|23.222.38.231|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75880 (74K) [text/plain]
Saving to: ‘english_vocab.txt’

english_vocab.txt   100%[===================>]  74.10K  --.-KB/s    in 0.01s

2025-06-30 13:15:40 (7.33 MB/s) - ‘english_vocab.txt’ saved [75880/75880]

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer
from bnltk.tokenize import Tokenizers
from bnltk.bnltk_downloads import DataFiles
DataFiles.download()
from bnltk.pos_tagger import PosTagger
import random
from tqdm.auto import tqdm
from sklearn.metrics.pairwise import cosine_similarity
import torch

Creation of the directory failed or exists
bn_tagged_mod.txtis already exists!!
pos_tagger.weights.h5is already exists!!
Done!

In [ ]:
# Check GPU availability
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

print("🔄 Loading models...")
embedding_model = SentenceTransformer('sentence-transformers/LaBSE', device=device)
tokenizer = Tokenizers()
pos_tagger = PosTagger()

# Load English vocabulary
with open("english_vocab.txt", "r") as f:
    english_vocab = [word.strip() for word in f.readlines() if 3 < len(word) < 15][:3000]  # Filtered

print("🧠 Precomputing English embeddings...")
english_embeddings = embedding_model.encode(english_vocab,
                                         batch_size=256,
                                         show_progress_bar=True,
                                         convert_to_tensor=True,
                                         device=device)

Using device: cpu
🔄 Loading models...
🧠 Precomputing English embeddings...

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

In [ ]:
def code_mix_sentence(sentence: str,
                     replace_ratio: float = 1,
                     pos_to_replace: list = ["NN", "VB", "JJ", "RB"]) -> str:
    """
    Args:
        sentence: Input Bengali sentence (e.g., "আমি বই পড়ি")
        replace_ratio: Probability of replacement (0-1)
        pos_to_replace: POS tags to replace ["NN", "VB", ...]
    Returns:
        Code-mixed sentence (e.g., "I বই read")
    """
    try:
        # Tokenize and POS tag
        words = tokenizer.bn_word_tokenizer(sentence)
        pos_tags = pos_tagger.tagger(sentence)

        if len(words) != len(pos_tags):
            return sentence  # Fallback

        mixed = []
        for word, (_, pos) in zip(words, pos_tags):
            if pos in pos_to_replace and random.random() < replace_ratio:
                # Get Bengali word embedding
                bn_embed = embedding_model.encode(word,
                                                 convert_to_tensor=True,
                                                 device=device)

                # Find most similar English word
                sims = cosine_similarity(
                    bn_embed.cpu().numpy().reshape(1, -1),
                    english_embeddings.cpu().numpy()
                )
                best_idx = np.argmax(sims)
                replacement = english_vocab[best_idx]

                # Preserve Bengali verb suffixes
                if pos == "VB" and word[-1] in ['া', 'ে', 'ো', 'ছ', 'ল']:
                    replacement += " " + word[-1]  # "eating" + " ছি"

                mixed.append(replacement)
            else:
                mixed.append(word)

        return " ".join(mixed)
    except Exception as e:
        print(f"Error processing: {sentence} - {str(e)}")
        return sentence

input_sentence = "আমার একটি সুন্দর বাগান আছে"

mixed = code_mix_sentence(input_sentence)
print(f"🔍 Original: {input_sentence}")
print(f"🌐 Mixed: {mixed}")

🔍 Original: আমার একটি সুন্দর বাগান আছে
🌐 Mixed: আমার একটি beautiful বাগান আছে

In [ ]:
from tqdm import tqdm
tqdm.pandas()
df['code_mixed_text'] = df['tgt_txt'].progress_apply(code_mix_sentence)

  2%|▏         | 16/1000 [00:07<17:15,  1.05s/it]

In [ ]:
ip = pd.read_csv('dummy.csv')

In [ ]:
ip['mixed'] = ip['text'].progress_apply(code_mix_sentence)

100%|██████████| 8/8 [00:07<00:00,  1.09it/s]

In [ ]:
ip['mixed'][7]

'বইমেলায় অনেক মানুষ এসেছে । beginner beginner বই দেখা যাচ্ছে । কিছু লেখকের সঙ্গে পরিচয়ও হলো । আমি কয়েকটি গল্পের বই কিনলাম । বন্ধুদের সঙ্গে দেখা করে আমরা একসঙ্গে খেতে গেলাম ।'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('code_mixed.csv')

In [ ]:
df['tgt_txt'][1]

'আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯৮তম পর্বে আপনাদের সবার সঙ্গে যুক্ত হয়ে আমার খুব ভালো লাগছে। শতপূর্তির দিকে এই যাত্রায়, মন কি বাত-কে, আপনারা সবাই,  জনসাধারণের অংশগ্রহণের যে অভিব্যক্তি তার অনন্য মঞ্চ করে তুলেছেন। প্রত্যেক মাসে লক্ষ লক্ষ বার্তায় কত মানুষের মন কি বাত আমার কাছে এসে পৌঁছয়। আপনারা নিজেদের মনের শক্তি সম্পর্কে তো জানেনই, এভাবেই সমাজের শক্তিতে কীভাবে দেশের শক্তি বাড়ে, এটা আমরা মন কি বাতের ভিন্ন ভিন্ন পর্বে দেখেছি, বুঝেছি, আর আমি অনুভব করেছি – স্বীকারও করেছি। আমার সেই দিনটির কথা মনে আছে যদিন আমরা মন কি বাতে ভারতের চিরাচরিত খেলাধুলোকে উৎসাহ দেওয়ার কথা আলোচনা করেছিলাম। তৎক্ষণাৎ ভারতে একটা ঢেউ উঠল চিরাচরিত খেলাধুলোকে যুক্ত করার, তার চর্চার, সেগুলো শেখার। মন কি বাতে যখন ভারতের খেলনার আলোচনা হল  তখন দেশের মানুষ সক্রিয়ভাবে একে উৎসাহ দিল। এখন তো ভারতের খেলনার এমন    ক্রেস তৈরি হয়ে গিয়েছে যে বিদেশেও এর চাহিদা খুব বাড়ছে। যখন মন কি বাতে আমরা স্টোরি টেলিং-এর ভারতীয় ধারা সম্পর্কে চর্চা করলাম তখন এর সুনাম দূরদূরান্তে পৌঁছে গেল।  বেশি-বেশি মানুষ স্টোরি টেলিং-এর ভারতীয় ধারা প্রতি আকৃষ্ট হতে লাগল।\nবন্ধুগণ, আপনাদের মনে আছে যে সর্দার প্যাটেলের জন্মজয়ন্তী অর্থাৎ একতা দিবসে মন কি বাতে আমরা তিনটে প্রতিযোগিতার কথা বলেছিলাম। এই সব প্রতিযোগিতা দেশভক্তির উপর আধারিত গীত, লোরি আর রঙ্গোলি নিয়ে ছিল। আমার বলতে ভালো লাগছে যে গোটা দেশের সাতশোরও বেশি জেলার পাঁচ লাখেরও বেশি মানুষ প্রবল উৎসাহে এতে অংশ নেয়। শিশুরা, বড়রা, প্রবীণরা সবাই এতে হৈ হৈ করে অংশ নেয় আর কুড়িটিরও বেশি ভাষায় নিজেদের এন্ট্রি পাঠায়। এই সব প্রতিযোগিতায় অংশগ্রহণকারী সব প্রতিযোগীকে আমার পক্ষ থেকে অনেক অনেক অভিনন্দন। আপনারা প্রত্যেকে, নিজেই, এক একজন চ্যাম্পিয়ন, শিল্প সাধক। আপনারা সবাই এটা দেখিয়েছেন যে নিজের দেশের বৈচিত্র্য এবং সংস্কৃতির প্রতি আপনাদের হৃদয় কতটা প্রেম রয়েছে।\nবন্ধুগণ, আজ এই প্রসঙ্গে আমার লতা মঙ্গেশকর জী, অর্থাৎ লতা দিদির কথা মনে পড়া অত্যন্ত স্বাভাবিক। কারণ যখন এই প্রতিযোগিতা শুরু হয়েছিল তখন লতা দিদি ট্যুইট করে দেশবাসীর কাছে অনুরোধ করেন যাতে তাঁরা অবশ্যই এই প্রক্রিয়ায় যুক্ত হন।\nবন্ধুগণ, লোরি লিখন প্রতিযোগিতায় প্রথম পুরস্কার জেতেন কর্ণাটকের চামরাজনগর জেলার বি এম মঞ্জুনাথ’জী। তিনি এই পুরস্কার পান কন্নড় ভাষায় লেখা তাঁর লোরি ‘মালগু কন্দা’র জন্য। এটা লেখার প্রেরণা তিনি পান নিজের মা আর ঠাকুমার গাওয়া লোরি-গীত থেকে। এটা শুনলে আপনাদেরও ভালো লাগবে।\nঘুমিয়ে পড়ো, ঘুমিয়ে পড়ো আমার বেবি\nআমার বুদ্ধিমান সোনা, ঘুমিয়ে পড়ো\nদিন শেষ হয়ে নেমেছে অন্ধকার\nঘুমের দেবী চলে আসবেন\nতারাদের বাগান থেকে\nস্বপ্ন নিয়ে আসবেন\nঘুমিয়ে পড়ো, ঘুমিয়ে পড়ো\nজোজো  জো জো\nজোজো  জো জো\nঅসমের কামরূপ জেলার বাসিন্দা দিনেশ গোয়ালা জী এই প্রতিযোগিতায় দ্বিতীয় পুরস্কার জিতেছেন। ইনি যে লোরি লিখেছেন তাতে মাটি আর ধাতু দিয়ে তৈরি স্থানীয় বাসন তৈরীর কারিগরের Propular Craft-এর ছাপ রয়েছে।\nকুমোর দাদা বস্তা নিয়ে এসেছেন\nআচ্ছা, কী আছে কুমোরের এই বস্তার মধ্যে?\nকুমোরের বস্তা খুলে দেখতে পেলাম\nবস্তার মধ্যে রয়েছে মিষ্টি একটা বাটি\nআমাদের পুচকিটা কুমোরকে জিজ্ঞাসা করল\nকেমন এই ছোট্ট বাটি!\nগীত আর লোরির মতোই রঙ্গোলি প্রতিযোগিতাও খুব জনপ্রিয় হয়েছিল। এতে অংশ নেওয়া প্রতিযোগীরা দারুণ দারুণ রঙ্গোলি বানিয়ে পাঠিয়েছেন। এতে বিজয়ী এন্ট্রি ছিল পঞ্জাবের কমল কুমার জী-র। ইনি নেতাজি সুভাষচন্দ্র বসু এবং অমর শহীদ বীর ভগৎ সিংহের খুব সুন্দর রঙ্গোলি বানিয়েছেন। মহারাষ্ট্রের সাংলির শচীন নরেন্দ্র অওসারি’জী নিজের রঙ্গোলিতে জালিয়ানওয়ালাবাগ, সেখানকার নরসংহার আর শহীদ উধম সিংহের বীরত্ব ফুটিয়ে তুলেছেন।\nগোয়ার বাসিন্দা গুরুদত্ত ওয়ান্তেকার গান্ধীজির রঙ্গোলি তৈরি করেছিলেন, অন্যদিকে পুদুচেরির মালাতিসেলভম জি’ও অনেক মহান স্বাধীনতা সংগ্রামীদের উপর মনোনিবেশ করেছিলেন। দেশাত্মবোধক গানের প্রতিযোগিতার বিজয়ী, টি. বিজয় দুর্গা’জী অন্ধ্র প্রদেশের মানুষ। তিনি তেলুগু ভাষায় নিজের এন্ট্রি পাঠিয়েছিলেন। তিনি নিজের অঞ্চলের প্রসিদ্ধ স্বাধীনতা সংগ্রামী নরসিংহ রেড্ডি গারুজী দ্বারা অনুপ্রাণিত হয়েছিলেন। আপনারাও বিজয় দুর্গা’জী সেই এন্ট্রির কিছুটা অংশ শুনুন\n(Telugu Sound Clip (27 seconds) HINDI Translation)\nরেনাড়ু প্রদেশের সূর্য,\nহে বীর নরসিংহ!\nভারতীয় স্বাধীনতা সংগ্রামের অংকুর তুমি, অঙ্কুশ তুমি!\nব্রিটিশদের অন্যায় ও স্বৈরাচারী দমন-পীড়নের ঘটনা দেখে।\nতোমার রক্ত গরম হয়েছিল এবং আগুন জ্বলেছিল!\nরেনাড়ু প্রদেশের সূর্য,\nহে বীর নরসিংহ!\nতেলেগুর পরে, এখন আমি আপনাকে মৈথিলীতে একটি ক্লিপ শোনাব। এটি পাঠিয়েছেন দীপক বৎস’জী। এই প্রতিযোগিতায় তিনি পুরস্কারও জিতেছেন।\n(Maithili Sound Clip (30 seconds) HINDI Translation)\nভারত বিশ্বের গর্ব ভাই,\nআমাদের দেশ মহান\nতিন দিক সাগরে ঘেরা,\nউত্তরে কৈলাস বলবান,\nগঙ্গা, যমুনা, কৃষ্ণা, কাবেরী,\nকোশি, কমলা, বলান\nআমাদের দেশ মহান ভাই।\nতেরঙা অন্ত প্রাণ\nবন্ধুরা, আশা করি আপনাদের ভালো লেগেছে। প্রতিযোগিতায় অংশ নিয়েছেন এমন এন্ট্রির তালিকা অনেক দীর্ঘ। আপনি সংস্কৃতি মন্ত্রণালয়ের ওয়েবসাইটে গিয়ে, আপনার পরিবারের সাথে তাঁদের দেখুন এবং শুনুন – আপনি অনেক অনুপ্রেরণা পাবেন। আমার প্রিয় দেশবাসী, বেনারসের কথাই হোক, সানাইয়ের কথাই হোক, ওস্তাদ বিসমিল্লাহ খান জীর কথাই হোক, আমার মনোযোগ সেদিকে যাবেই। কয়েকদিন আগে ‘ওস্তাদ বিসমিল্লাহ খান যুব পুরস্কার’ দেওয়া হয়েছে। সঙ্গীত ও পারফর্মিং আর্ট এর ক্ষেত্রে উদীয়মান, প্রতিভাবান শিল্পীদের এই পুরস্কার দেওয়া হয়। এই পুরস্কার শিল্প, কলা ও সঙ্গীত জগতের জনপ্রিয়তা বৃদ্ধির পাশাপাশি, সমৃদ্ধিতেও অবদান রাখছে। এর মধ্যে এমন শিল্পীরাও অন্তর্ভুক্ত যাঁরা সেই সকল বাদ্যযন্ত্রগুলির নবজাগরণ ঘটিয়েছেন, যাদের জনপ্রিয়তা সময়ের সাথে কমে যাচ্ছিল। এখন, আপনারা সবাই এই টিউনটি মন দিয়ে শুনুন…\n(Sound Clip (21 seconds) Instrument- ‘ সুরসিঙ্গার’, Artist – জয়দীপ মুখার্জী)\nআপনি কি জানেন এটি কোন বাদ্যযন্ত্র? আপনি হয়তো জানেন না! এই বাদ্যযন্ত্রের নাম ‘সুরসিঙ্গার’ এবং এই সুরটি রচনা করেছেন জয়দীপ মুখার্জি।\nওস্তাদ বিসমিল্লাহ খান পুরস্কারে সম্মানিত যুবকদের মধ্যে জয়দীপ জি একজন । ৫০ ও ৬০-এর দশকে থেকেই এই বাদ্যযন্ত্রের সুর শুনতে পাওয়া দুর্লভ হয়ে পড়লেও জয়দীপ সুরসিঙ্গারকে আবার জনপ্রিয় করার সর্বাত্মক চেষ্টা চালিয়ে যাচ্ছেন। একইভাবে, বোন উপ্পলপু নাগমণি জি’র প্রচেষ্টাও অত্যন্ত অনুপ্রেরণাদায়ক, যাঁকে ম্যান্ডোলিনে কর্নাটকী ইন্সট্রুমেন্টালের জন্য এই পুরস্কার দেওয়া হয়েছে। আবার সংগ্রাম সিং সুহাস ভান্ডারে জি বারকরি কীর্তনের জন্য এই পুরস্কার পেয়েছেন। এই তালিকায় শুধু সঙ্গীত শিল্পীই আছেন এমন নয় – ভি দুর্গা দেবী’জি ‘করকাট্টম’, একটি প্রাচীন নৃত্যশৈলীর জন্য এই পুরস্কার জিতেছেন। এই পুরস্কারের আরেকজন বিজয়ী, রাজ কুমার নায়ক জী, তেলেঙ্গানার ৩১টি জেলায় ১০১ দিন ধরে চলা পেরিনি ওডিসির আয়োজন করেছিলেন। আজ সকলে তাঁকে পেরিনি রাজকুমার নামেই চেনে। পেরিনি নাট্যম, ভগবান শিবকে উৎস্বর্গীকৃতএকটি নৃত্য, কাকাতিয়া রাজবংশের সময় খুব জনপ্রিয় ছিল। এই রাজবংশের শিকড় আজকের তেলেঙ্গানার সাথে সম্পর্কিত। আর একজন পুরস্কার বিজয়ী হলেন সাইখোম সুরচন্দ্রা  সিং।\nইনি মাইতেই পুং যন্ত্রটি তৈরিতে তার দক্ষতার জন্য প্রসিদ্ধ. এই বাদ্যযন্ত্রটির মনিপুরের সঙ্গে যোগ আছে। পুরন সিংহ, যিনি একজন দিব্যাংগ শিল্পী, যিনি রাজুলা মালুশাহী,নিউলি, হুড়কা বল, জাগারের মতো সংগীতের বিভিন্ন ধারাকে জনপ্রিয় করে তোলার চেষ্টা চালিয়ে যাচ্ছেন। তিনি এই সংক্রান্ত বেশ কিছু অডিও রেকর্ডিংও করেছেন। উত্তরাখন্ড এর লোকসঙ্গীতে নিজের উৎকর্ষের নিদর্শন রেখে তিনি বেশ কিছু পুরস্কারও পেয়েছেন। সময়ের অপ্রতুলতার কারণে আমি এখানে সব পুরস্কার প্রাপকদের নাম না নিতে পারলেও, আমি আশাবাদী যে আপনারা ওঁদের সম্পর্কে নিশ্চই খোঁজ রাখবেন। আমি এও আশা রাখি যে এই সব শিল্পীরা তাদের Performing Arts কে আরো জনপ্রিয় করে তোলার জন্য তৃণমূল স্তরে গিয়ে সকলকে অনুপ্রাণিত করবেন। আমার প্রিয় দেশবাসী, আমাদের দেশ এখন দ্রুত গতিতে এগিয়ে চলেছে। দেশের বিভিন্ন কোণায় আমরা ডিজিটাল ইন্ডিয়ার শক্তি উপলব্ধি করতে পারছি। ডিজিটাল ইন্ডিয়ার শক্তিকে ঘরে ঘরে পৌঁছনোর পেছনে অনেকগুলো apps এর ভূমিকা অনস্বীকার্য। এমনি একটি app হলো ই-সঞ্জীবনী।  এই app এর সাহায্যে টেলি -কন্সালটেশন অর্থাৎ দূরে বসেই ভিডিও কনফারেন্সিঙের মাধ্যমে ডক্টরের কাছ থেকে আপনার রোগ ব্যাধি নিয়ে আলোচনা করা সম্ভব। এই app ব্যবহার করে এখনো পর্যন্ত ১০ কোটিরও বেশি মানুষ টেলি কন্সালটেশন করেছেন। আপনারা ভাবতে পারেন !  ১০ কোটি লোক ভিডিও কন্সালটেশন করেছেন! রুগী ও চিকিৎসকের মধ্যে একটা সম্পর্ক তৈরী হলো, এটা একটা বিরাট প্রাপ্তি। আর এই প্রাপ্তির জন্য আমি সকল চিকিৎসক এবং এই সুবিধাপ্রাপ্ত সকল রুগীদের আন্তরিক শুভেচ্ছা জানাই। ভারতবাসীরা, কিভাবে এই প্রযুক্তিকে নিজেদের জীবনের অঙ্গ করেছেন এটি তার উজ্জ্বল দৃষ্টান্ত। আমরা দেখেছি কোরোনাকালে কিভাবে এই ই-সঞ্জীবনী app এর মাধ্যমে হওয়া টেলিকনসালটেশন কত মানুষের কাছে একটা আশীর্বাদ হয়ে দাঁড়িয়েছিল। আমার মনে হলো যে এই নিয়ে “মন কি বাতে” একজন চিকিৎসক ও রুগীর সঙ্গে আলোচনা করা যাক, তাদের কথা শোনা যাক এবং আপনাদের কাছে সেটা পৌঁছানো যাক। আমরা জানতে চাইবো যে এই টেলি কন্সালটেশন মানুষের জন্য কতটা উপকারী।  আমাদের সঙ্গে আছেন সিক্কিমের এক চিকিৎসক, ডাক্তার মদন মণি’জী ।ডাক্তার মদন মণি’জী, সিক্কিমের বাসিন্দা ঠিকই কিন্তু তিনি তার MBBS ধানবাদ থেকে করেছেন এবং তারপর বেনারস হিন্দু ইউনিভার্সিটি থেকে MD করেছেন। উনি বিভিন্ন গ্রামীণ অঞ্চলের বহু মানুষদের টেলি কন্সালটেশন দ্বারা  চিকিৎসা করেছেন।\nপ্রধানমন্ত্রী – নমস্কার.. নমস্কার… মদন মণি’জী।\nডা: মদন মণি – নমস্কার স্যার।\nপ্রধানমন্ত্রী – আমি নরেন্দ্র মোদী বলছি।\nডা: মদন মণি– হ্যাঁ.. হ্যাঁ.. বলুন স্যার।\nপ্রধানমন্ত্রী – আপনি তো বেনারসে পড়াশোনা করেছেন?\nডা: মদন মণি– হ্যাঁ.. স্যার আমি বেনারসে পড়াশোনা করেছি।\nপ্রধানমন্ত্রী – আপনার medical education ওখানেই হয়েছে?\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ..\nপ্রধানমন্ত্রী – তাহলে আপনি যেসময় বেনারসে ছিলেন, সেই তখনকার বেনারস আর এখনকার বদলে যাওয়া বেনারস কখনও দেখতে গেছেন নাকি যাওয়া হয়নি?\nডা: মদন মণি – হ্যাঁ প্রধানমন্ত্রী’জী আমি যেতে পারিনি, যবে থেকে সিকিমে চলে এসেছি, কিন্তু আমি শুনেছি যে বেশ পরিবর্তন ঘটেছে।\nপ্রধানমন্ত্রী – তো কত বছর হয়ে গেল আপনি বেনারস ছেড়েছেন?\nডা: মদন মণি – বেনারস 2006 সালে ছেড়ে এসেছি, স্যার।\nপ্রধানমন্ত্রী – ওহ আচ্ছা.. তাহলে আপনার নিশ্চয় একবার যাওয়া উচিৎ।\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ.. স্যার।\nপ্রধানমন্ত্রী – আচ্ছা, আমি ফোন করেছি, এই কারণে যে আপনি সিকিমের ভেতরে প্রত্যন্ত পাহাড়ে থেকে বসবাসকারী জনগণকে টেলিকনসালটেশনের দুর্দান্ত পরিষেবা প্রদান করছেন।\nডা: মদন মণি – হ্যাঁ..\nপ্রধানমন্ত্রী – আমি মন কি বাতের শ্রোতা বন্ধুদের আপনার অভিজ্ঞতাশোনাতে চাই।\nডা: মদন মণি – আচ্ছা..\nপ্রধানমন্ত্রী – একটু বলুন আমাকে, কেমন অভিজ্ঞতা ছিল?\nডা: মদন মণি – অভিজ্ঞতা খুব ভালো ছিল প্রধানমন্ত্রী জি। ব্যাপারটা হল, সিকিমে, খুব কাছাকাছিও যে PHC রয়েছে, সেখানে যেতেও লোকজনেদের গাড়িতে চেপে কমপক্ষে এক-দুশো টাকা নিয়ে যেতে হতো। আর ডাক্তার পাওয়া যায়, কি না পাওয়া যায়, সেটাও একটা problem। তাই Tele Consultation-এর মাধ্যমে মানুষ আমাদের সঙ্গে সরাসরি যুক্ত হতে পারেন, এমনকি দূর দূরান্তের মানুষও। Health & Wellness Centre-এর যারা CHOs রয়েছেন, তারাও আমাদের, মানুষের সঙ্গে যোগাযোগ করিয়ে দেন। আর আমরা, যদি তাদের কোন পুরনো অসুখ থাকে তার reports, তার এখনকার present condition, ইত্যাদি  সবকিছুই তাদের জানিয়ে দি।\nপ্রধানমন্ত্রী – মানে document transfer করেন।\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ। Document transferও করি এবং যদি transfer করতে না পারি, তাহলে আমরা তা মানুষদের পড়ে শোনাই।\nপ্রধানমন্ত্রী – ওখানের Wellness Centre-এর doctor বলে দেন।\nডা: মদন মণি – হ্যাঁ, Wellness Centre-এর যে CHO থাকেন তিনি, Community Health Officer।\nপ্রধানমন্ত্রী – আর যারা patient, তারা নিজেদের অসুবিধার বিষয়ে আপনাদের সরাসরি বলেন।\nডা: মদন মণি – হ্যাঁ, patientও নিজের অসুবিধা আমাদের জানান। তারপর পুরনো records দেখে, আবার যদি নতুন কিছু পাওয়া যায় তা জানানো হয়। ধরুন, যদি কারোর Chest Auscultate করাতে হয়, তাহলে জানা দরকার তার পা ফোলা নেই তো! যদি CHO তা না দেখে থাকেন, তাহলে আমরা সেই ব্যক্তিকে বলি যে সে যেন পরীক্ষা করায় তার ফোলা রয়েছে কি নেই, চোখ দেখাতে বলা হয়, anaemia রয়েছে কিনা, যদি তার কাশি হয়ে থাকে তাহলে Chest-এর  Auscultate করিয়ে জানা দরকার সেখানে sounds রয়েছে কিনা।\nপ্রধানমন্ত্রী – আপনি Voice Call-এ কথা বলেন না Video Call-এরও ব্যবহার করেন?\nডা: মদন মণি – হ্যাঁ, Video Call-এরও ব্যবহার করি।\nপ্রধানমন্ত্রী – তাহলে patient-কে, আপনিও দেখতে পান?\nডা: মদন মণি – হ্যাঁ, patient-কেও দেখতে পাই।\nপ্রধানমন্ত্রী – Patient-এর কি রকম feeling হয়?\nডা: মদন মণি – Patient-এর ভালই লাগে কারণ ডাক্তারকে তারা এত কাছে দেখতে পায়। তাদের confusion থাকে যে তাদের ওষুধ বাড়ানো হবে না কমানো হবে, কারণ সিকিমে বেশিরভাগ patient diabetes, Hypertension ইত্যাদিতে ভোগে, একটা diabetes ও hypertension-এর ওষুধ change করানোর জন্য তাঁকে ডাক্তারের সঙ্গে দেখা করতে অনেক দূর যেতে হয়। কিন্তু Tele Consultation-এর মাধ্যমে ওখানেই পরামর্শ পাওয়া যায় আর ওষুধও health & Wellness Centre-এ  Free Drugs initiative-এর দরুন পাওয়া যায়। তাই একই জায়গা থেকেই ওষুধও নিয়ে যেতে পারে সবাই।\nপ্রধানমন্ত্রী – আচ্ছা মদনমণি জি, আপনি তো জানেন যে patient-দের একটা স্বভাব রয়েছে যে যতক্ষণ না ডাক্তার আসছেন, এবং দেখছেন, ততক্ষণ সে সন্তুষ্ট হয় না, আর ডাক্তারেরও মনে হয় রোগীকে দেখতে হবে, তাহলে এখানে যে পুরো ব্যাপারটাই Telecom-এর Consultation-এর মাধ্যমে হচ্ছে, তখন সেখানে ডাক্তার কি feel করছে, patient-টি বা কি feel হচ্ছে?\nডা: মদন মণি – হ্যাঁ, আমাদেরও মনে হয় যদি patient মনে করেন যে ডাক্তারের দেখা উচিত, তাহলে যা যা দেখা প্রয়োজন, তা আমরা CHO-কে বলে video-তেই দেখাবার কথা বলি। আর কখনো কখনো তো patient-কে video-তেই কাছে এসে তার যা সমস্যা রয়েছে, ধরুন কারুর যদি চামড়ার কোন problem হয়েছে, skin-এর problem হয়েছে, তখন আমরা তার সমস্যা video-তেই দেখিয়ে দি।  তাই তাঁরাও সন্তুষ্টি হন।\nপ্রধানমন্ত্রী – আর তারপর রোগীকে পরিষেবা দেবার পর তিনি যখন খুশি হন তখন কি রকম অনুভব হয়? রোগী কি সুস্থ হচ্ছেন?\nডা: মদন মণি – হ্যাঁ খুব ভালো লাগে। আমাদেরও ভালো লাগে স্যার। কারন আমি এখন স্বাস্থ্য বিভাগে আছি আর এর সঙ্গে আমি টেলি কনসাল্টেশন ও করি, তাই ফাইলের সঙ্গে সঙ্গে পেশেন্টদের দেখাশোনা করাও আমায় অনেক আনন্দের অনুভূতি দেয়।\nপ্রধানমন্ত্রী – গড়ে কতজন রোগীর টেলিকনসাল্টেশন কেস আপনার কাছে আসে?\nডা: মদন মণি – এখন অবধি আমি ৫৩৬ জন রোগী দেখেছি।\nপ্রধানমন্ত্রী – ওহ অর্থাৎ আপনার এই বিষয়ে অনেকটা দক্ষতা এসে গেছে।\nডা: মদন মণি – হ্যাঁ ভালো লাগে দেখতে।\nপ্রধানমন্ত্রী – আমি আপনাকে শুভেচ্ছা জানাচ্ছি। এই টেকনোলজির মাধ্যমে আপনি  সিকিমের দূর দূরান্তের জঙ্গলে, পাহাড়ের বাসিন্দাদের এত বড় পরিষেবা দিচ্ছেন। আর খুশির কথা এটাই যে আমাদের দেশের প্র্রান্তিক ক্ষেত্রেও এই টেকনোলজির এত সুন্দর ব্যবহার হচ্ছে। আমার তরফ থেকে আপনাকে অনেক অনেক অভিনন্দন।\nডা: মদন মণি – ধন্যবাদ।\nবন্ধুরা ডঃ মদন মনির কথা থেকে পরিষ্কার বোঝা যাচ্ছে যে এই ই-সঞ্জীবনী অ্যাপ কিভাবে ওনার সাহায্য করছে। ডক্টর মদন জি’র পরে আমরা আরো এক মদনজির সঙ্গে কথা বলব। ইনি  হলেন উত্তরপ্রদেশের চন্দৌলি জেলার অধিবাসী মদন মোহন লাল জি। এখন এটাও একটা অদ্ভুত বিষয় যে চন্দৌলিও বেনারসের পাশেই অবস্থিত। আসুন মদনমোহন জি’র কাছ থেকে জানি যে ই-সঞ্জীবনী কে নিয়ে একজন রোগী হিসেবে ওনার অনুভূতি কি রকম?\nপ্রধানমন্ত্রী – মদন মোহন জি প্রণাম।\nমদন মোহন জি – নমস্কার, নমস্কার সাহেব।\nপ্রধানমন্ত্রী – নমস্কার। আচ্ছা আমাকে এটা বলা হয়েছে যে আপনি ডায়াবেটিসের রোগী।\nমদন মোহন জি – হ্যাঁ।\nপ্রধানমন্ত্রী – আর আপনি টেকনোলজির সাহায্যে টেলিকনসালটেশন করে আপনার রোগের সম্বন্ধে সাহায্য নেন।\nমদন মোহন জি – হ্যাঁ।\nপ্রধানমন্ত্রী – একজন পেশেন্ট হয়ে আমি আপনার অনুভূতি শুনতে চাই, যাতে আমি দেশবাসীর কাছে এই কথাটা পৌঁছে দিতে পারি যে আজ টেকনোলজির মাধ্যমে আমাদের গ্রামের মানুষেরাও কিভাবে এর সাহায্য নিতে পারেন। একটু বলুন কিভাবে ব্যবহার করেন?\nমদন মোহন জি – আসলে স্যার হসপিটাল অনেক দূরে আর আমার যখন ডায়াবেটিস হলো তখন আমাকে ৫-৬ কিলোমিটার দূরে গিয়ে চিকিৎসা করাতে হতো, ডাক্তার দেখাতে হতো। যখন থেকে আপনার দ্বারা এই ব্যবস্থা করা হয়েছে তখন থেকে আমি যাই, আমার পরীক্ষা করা হয়, আমাদের বাইরের ডাক্তারদের সঙ্গে কথাও বলিয়ে দেওয়া হয় আর ওষুধও দিয়ে দেওয়া হয়। এর ফলে আমার ও আমার মতো অনেক মানুষের  লাভ হল।\nপ্রধানমন্ত্রী – তাহলে প্রতিবার কী একই ডাক্তারবাবু দেখেন; না কী ডাক্তার বদলে যায়?\nমদন মোহন জি – যখন সে বুঝতে পারেন না, তখন ডাক্তারবাবুকে দেখায়। তারপর তিনিই কথা বলে অন্য ডাক্তারের সঙ্গে আমার কথা বলিয়ে দেয়।\nপ্রধানমন্ত্রী – আর ডাক্তার আপনাকে যে গাইডেন্স (guidance) দেয় তাতে কি আপনার সম্পূর্ণ লাভ হয়?\nমদন মোহন জি – হ্যাঁ লাভ তো হয়েই, এতে আমার অনেক সুবিধা হয়। আর গ্রামের লোকজনেরো সুবিধা হয়। সবাই ওখানেই বলেন যে দাদা আমাদের BP আছে বা সুগার আছে, Test করুন বা পরীক্ষা নিরীক্ষা করুন, ওষুধ দিন। আর আগে তো ৫-৬ কিলোমিটার দূরে যেতে হতো। লম্বা লম্বা লাইন পড়তো। Pathology-তেও লাইন পড়তো, একটা গোটা দিন নষ্ট হয়ে যেতো।\nপ্রধানমন্ত্রী – মানে আপনার সময়-ও বেঁচে যাচ্ছে!\nমদন মোহন জি – তাছাড়া পয়সা’ও খরচ হতো, আর এখানে বিনামূল্যে সব পরিষেবা পাচ্ছি।\nপ্রধানমন্ত্রী – আচ্ছা, যখন আপনি সামনাসামনি ডাক্তারের সঙ্গে দেখা করেন তখন একটা ভরসা তৈরি হয়। মনে হয় অন্তত ডাক্তারবাবু আছেন, আমার পালস দেখে নিয়েছেন, চোখ পরীক্ষা করেছেন, আমার জিভ চেক করেছেন; মানে একটা অন্যরকম feeling কাজ করে, কিন্তু যখন এই tele consultation এর সাহায্য নিতে হয় তখন কী সেই একই রকম ভরসা তৈরি হয়?\nমদন মোহন জি – হ্যাঁ, অবশ্যই ভরসা তৈরি হয়! উনি আমার নাড়ি পরীক্ষা করছেন, স্টেথোস্কোপে শ্বাস পরীক্ষা করছেন- এরকমই একটা অনুভূতি আমার হয়, আর আমার শরীরটাও বেশ ভালো লাগে। এতো সুন্দর একটা ব্যবস্থা আপনার জন্য আমরা পেয়েছি যে তার ফলে আমাদের কষ্ট করে যেখানে যেতে হতো, গাড়ির ভাড়া দিতে হতো, লাইন দিতে হতো, সেখানে সব পরিষেবা আমরা ঘরে বসে বসেই পেয়ে যাচ্ছি।\nপ্রধানমন্ত্রী – আচ্ছা মদন মোহন জি, আপনাকে অনেক অনেক অভিনন্দন। এই বয়সে এসেও আপনি technology সম্পর্কে জেনেছেন, এর ব্যবহার-ও করছেন। অন্যদেরও বলুন যাতে তাদের সময় বেঁচে যায়, খরচও বেঁচে যায়, আর তাঁদের যে উপায় বাতলে দেওয়া হয় সেইমতো ওষুধ পেতেও কোন অসুবিধা হয় না।\nমদন মোহন জি – হ্যাঁ, সেই আর কি!\nপ্রধানমন্ত্রী – আচ্ছা আপনাকে অনেক অনেক শুভেচ্ছা মদন মোহন জি।\nমদন মোহন জি – সাহেব, আপনি বেনারসকে কাশি বিশ্বনাথ স্টেশন করেছেন। আপনার জন্যে Devlopment হয়েছে । তাই আপনাকে আমাদের তরফ থেকে অভিনন্দন।\nপ্রধানমন্ত্রী – আপনাকেও অসংখ্য ধন্যবাদ, তবে আমি নয়, বেনারসের মানুষই বেনারসকে গড়ে তুলেছে\u200cন, আমি তো শুধুই মা গঙ্গার সেবার জন্যে এখানে, মা গঙ্গা’ই আমাকে ডেকেছেন, ব্যাস এটুকুই। আচ্ছা ঠিক আছে, আপনাকে অনেক অনেক শুভেচ্ছা। প্রনাম।\nমদন মোহন জি – নমস্কার স্যার।\nপ্রধানমন্ত্রী – হ্যাঁ নমস্কার!\nবন্ধুগণ, দেশের সাধারণ মানুষের জন্য, মধ্যবিত্তদের জন্য, পাহাড়ি এলাকার বাসিন্দাদের জন্য  E- Sanjivani., নামে জীবন রক্ষার অ্যাপ তৈরি হয়েছে। এটি হলো ভারতবর্ষের ডিজিটাল বিপ্লবের শক্তি। আর তার প্রভাব আমরা প্রতিটি ক্ষেত্রেই দেখতে পাচ্ছি। আপনারা তো জানেনই ভারতের ইউপিআই এর ক্ষমতা। বিশ্বের বহু দেশ এর প্রতি আকৃষ্ট। কিছুদিন পূর্বেই ভারত আর সিঙ্গাপুরের মধ্যে upi pay now link লঞ্চ করা হয়েছে। এখন ভারত আর সিঙ্গাপুর বাসীরা নিজেদের মোবাইল ফোন থেকে ঠিক সেই ভাবেই পয়সার লেনদেন করছেন যেভাবে তারা নিজেদের দেশে করে থাকেন। আমি খুবই আনন্দিত যে জনগণ এর সুযোগ নেওয়া শুরু করে দিয়েছে। ভারতের ই সঞ্জীবনী app  বলুন বা UPI, এগুলি Ease of Living কে আরো উন্নত করতে সাহায্য করেছে।\nআমার প্রিয় দেশবাসী। যখন কোন দেশে, বিলুপ্তপ্রায় কোন বিশেষ পাখির প্রজাতিকে, বা কোন জীবকে বাঁচানো হয়, তখন সারা বিশ্বে সেটার চর্চা হয়। আমাদের দেশে এমন অনেক মহান পরম্পরা আছে যেগুলি বিলুপ্ত হয়ে গিয়েছিল, জনমানস থেকে মুছে গিয়েছিল, কিন্তু এখন জনগণের অংশগ্রহণের ফলে ফের পুনর্জীবিত হয়ে উঠেছে আর তার চর্চার জন্য  মন কি বাতের মঞ্চের চেয়ে ভালো কি কিছু হতে পারে?\nএখন আমি আপনাদের যা বলতে চলেছি, সেটা জেনে আপনাদের সত্যিই খুব ভালো লাগবে এবং ঐতিহ্যের প্রতি গর্ববোধ করবেন। আমেরিকার নিবাসী শ্রীমান কাঞ্চন ব্যানার্জি ঐতিহ্যের সংরক্ষণের কাজের যুক্ত একটি অভিযানের দিকে আমার নজর আকৃষ্ট করেছেন। আমি ওনাকে অভিনন্দন জানাই। বন্ধুগণ, পশ্চিমবঙ্গের হুগলি জেলায় বাঁশবেড়িয়াতে এই মাসে ত্রিবেণী কুম্ভ মহোৎসবের আয়োজন করা হয়েছে। এতে ৮ লাখেরও বেশি ভক্তের সমাগম ঘটেছে। কিন্তু আপনারা কি জানেন এই মেলা  কেন এত গুরুত্বপূর্ণ? এই জন্য গুরুত্ব পূর্ণ কারণ বিশেষ এই জন্য কারণ এই মেলাটিকে ৭০০ বছরের পর আবার পুনর্জীবিত করে তোলা হয়েছে। এমনিতেই এই পরম্পরা হাজার বছরেরও বেশি পুরনো, কিন্তু দুর্ভাগ্যবশত ৭০০ বছর আগে বাংলার ত্রিবেণী তে এই মহোৎসবটি বন্ধ গিয়েছিল। স্বাধীনতার পর এটিকে আবার শুরু করা উচিত ছিল কিন্তু সেটাও হয়ে ওঠেনি। দু’বছর আগে স্থানীয় বাসিন্দারা এবং ত্রিবেণী কুম্ভ পরিচালনা সমিতির উদ্যোগে এই মহোৎসবটি আবার আরম্ভ করা হয়েছে। এই আয়োজনের সঙ্গে যুক্ত সব্বাইকে সাধুবাদ  জানাই। আপনারা কেবলমাত্র একটি প্রথাকে জীবিত করে তুলছেন তা না; বরং ভারতবর্ষের সাংস্কৃতিক ঐতিহ্যকে রক্ষাও করছেন।\nবন্ধুগণ , পশ্চিমবঙ্গের ত্রিবেণীকে যুগ যুগ ধরে একটি  পবিত্র স্থান  বলে মনে করা হয়। এটার উল্লেখ বিভিন্ন মঙ্গল কাব্যে, বৈষ্ণব সাহিত্যে, শাক্ত সাহিত্যে ও অন্যান্য বাংলা সাহিত্যের ধারায় লক্ষ্য করা যায়। বিভিন্ন ঐতিহাসিক দলিল থেকে এইটা জানা যায় যে এই ঐতিহাসিক স্থানটি কোন এক সময় সংস্কৃত, শিক্ষা, ও ভারতীয় সংস্কৃতির কেন্দ্র ছিল। অনেক সাধুরাই এই স্থানটিকে মাঘ সংক্রান্তির কুম্ভ স্নানের জন্য পবিত্র মনে করেন। ত্রিবেণীতে আপনারা অনেক গঙ্গার ঘাট, শিব মন্দির ও টেরাকোটার কারুকার্য খচিত প্রাচীন ঘর-বাড়ি ইত্যাদি দেখতে পাবেন। ত্রিবেনীর ঐতিহ্যকে পুনঃস্থাপন করার জন্য ও কুম্ভ মেলার গৌরবকে পুনর্জীবিত করার জন্য এখানে গতবছর কুম্ভ মেলার আয়োজন করা হয়েছিল। সাতশো বছর পর এই  তিন দিন ব্যাপী কুম্ভ মহাস্নান ও মেলা এই ক্ষেত্রে। এক নতুন প্রাণশক্তির সঞ্চার ঘটিয়েছে। তিন দিন ধরে প্রত্যেক দিনের গঙ্গা আরতি, রুদ্রাভিষেক ও যজ্ঞে বহু মানুষ দলে দলে যোগ দিয়েছেন। এইবারের মহোৎসবে বিভিন্ন আশ্রম মঠ ও আখড়া থেকেও অনেকেই যোগদান করেছেন। বাঙালির সংস্কৃতির সঙ্গে যুক্ত বিভিন্ন ধারা যেমন কীর্তন, বাউল , গৌড়ীয়ন নৃত্য, শ্রীখোল, পটের গান, ছৌ নাচ, সান্ধ্য অনুষ্ঠানের আকর্ষণের কেন্দ্র হয়ে উঠেছিল। আমাদের দেশের তরুণদের তাদের সোনালী অতীতের সঙ্গে যুক্ত করার এটি একটি  অত্যন্ত প্রশংসনীয় প্রয়াস। ভারতবর্ষে এমন বহু প্রথা আছে যেগুলিকে রিভাইভ করা অত্যন্ত প্রয়োজনীয়। আমি আশা করি যে এই সমস্ত বিষয়ের উপর আলোচনা এইদিকে এগিয়ে যেতে অনুপ্রাণিত করবে।\nআমার প্রিয় দেশবাসী, স্বচ্ছ ভারত অভিযান আমাদের দেশে জন-অংশীদারিত্বের অর্থই বদলে দিয়েছে। দেশের যে কোন স্থানে যদি স্বচ্ছতা সম্পর্কিত কোন কর্মসূচি চলে, তাহলে মানুষ তার খবর আমাকে অতি অবশ্যই পৌঁছে দেন। 

In [ ]:
df['code_mixed_text'][1]

'আমার প্রিয় দেশবাসী, নমস্কার। মন কি বাতের এই ৯৮তম পর্বে আপনাদের সবার সঙ্গে যুক্ত হয়ে আমার খুব ভালো লাগছে। শতপূর্তির দিকে এই যাত্রায়, মন কি বাত-কে, আপনারা সবাই,  জনসাধারণের অংশগ্রহণের যে অভিব্যক্তি তার অনন্য মঞ্চ করে তুলেছেন। প্রত্যেক মাসে লক্ষ লক্ষ বার্তায় কত মানুষের মন কি বাত আমার কাছে এসে পৌঁছয়। আপনারা নিজেদের মনের শক্তি সম্পর্কে তো জানেনই, এভাবেই সমাজের শক্তিতে কীভাবে দেশের শক্তি বাড়ে, এটা আমরা মন কি বাতের ভিন্ন ভিন্ন পর্বে দেখেছি, বুঝেছি, আর আমি অনুভব করেছি – স্বীকারও করেছি। আমার সেই দিনটির কথা মনে আছে যদিন আমরা মন কি বাতে ভারতের চিরাচরিত খেলাধুলোকে উৎসাহ দেওয়ার কথা আলোচনা করেছিলাম। তৎক্ষণাৎ ভারতে একটা ঢেউ উঠল চিরাচরিত খেলাধুলোকে যুক্ত করার, তার চর্চার, সেগুলো শেখার। মন কি বাতে যখন ভারতের খেলনার আলোচনা হল  তখন দেশের মানুষ সক্রিয়ভাবে একে উৎসাহ দিল। এখন তো ভারতের খেলনার এমন    ক্রেস তৈরি হয়ে গিয়েছে যে বিদেশেও এর চাহিদা খুব বাড়ছে। যখন মন কি বাতে আমরা স্টোরি টেলিং-এর ভারতীয় ধারা সম্পর্কে চর্চা করলাম তখন এর সুনাম দূরদূরান্তে পৌঁছে গেল।  বেশি-বেশি মানুষ স্টোরি টেলিং-এর ভারতীয় ধারা প্রতি আকৃষ্ট হতে লাগল।\nবন্ধুগণ, আপনাদের মনে আছে যে সর্দার প্যাটেলের জন্মজয়ন্তী অর্থাৎ একতা দিবসে মন কি বাতে আমরা তিনটে প্রতিযোগিতার কথা বলেছিলাম। এই সব প্রতিযোগিতা দেশভক্তির উপর আধারিত গীত, লোরি আর রঙ্গোলি নিয়ে ছিল। আমার বলতে ভালো লাগছে যে গোটা দেশের সাতশোরও বেশি জেলার পাঁচ লাখেরও বেশি মানুষ প্রবল উৎসাহে এতে অংশ নেয়। শিশুরা, বড়রা, প্রবীণরা সবাই এতে হৈ হৈ করে অংশ নেয় আর কুড়িটিরও বেশি ভাষায় নিজেদের এন্ট্রি পাঠায়। এই সব প্রতিযোগিতায় অংশগ্রহণকারী সব প্রতিযোগীকে আমার পক্ষ থেকে অনেক অনেক অভিনন্দন। আপনারা প্রত্যেকে, নিজেই, এক একজন চ্যাম্পিয়ন, শিল্প সাধক। আপনারা সবাই এটা দেখিয়েছেন যে নিজের দেশের বৈচিত্র্য এবং সংস্কৃতির প্রতি আপনাদের হৃদয় কতটা প্রেম রয়েছে।\nবন্ধুগণ, আজ এই প্রসঙ্গে আমার লতা মঙ্গেশকর জী, অর্থাৎ লতা দিদির কথা মনে পড়া অত্যন্ত স্বাভাবিক। কারণ যখন এই প্রতিযোগিতা শুরু হয়েছিল তখন লতা দিদি ট্যুইট করে দেশবাসীর কাছে অনুরোধ করেন যাতে তাঁরা অবশ্যই এই প্রক্রিয়ায় যুক্ত হন।\nবন্ধুগণ, লোরি লিখন প্রতিযোগিতায় প্রথম পুরস্কার জেতেন কর্ণাটকের চামরাজনগর জেলার বি এম মঞ্জুনাথ’জী। তিনি এই পুরস্কার পান কন্নড় ভাষায় লেখা তাঁর লোরি ‘মালগু কন্দা’র জন্য। এটা লেখার প্রেরণা তিনি পান নিজের মা আর ঠাকুমার গাওয়া লোরি-গীত থেকে। এটা শুনলে আপনাদেরও ভালো লাগবে।\nঘুমিয়ে পড়ো, ঘুমিয়ে পড়ো আমার বেবি\nআমার বুদ্ধিমান সোনা, ঘুমিয়ে পড়ো\nদিন শেষ হয়ে নেমেছে অন্ধকার\nঘুমের দেবী চলে আসবেন\nতারাদের বাগান থেকে\nস্বপ্ন নিয়ে আসবেন\nঘুমিয়ে পড়ো, ঘুমিয়ে পড়ো\nজোজো  জো জো\nজোজো  জো জো\nঅসমের কামরূপ জেলার বাসিন্দা দিনেশ গোয়ালা জী এই প্রতিযোগিতায় দ্বিতীয় পুরস্কার জিতেছেন। ইনি যে লোরি লিখেছেন তাতে মাটি আর ধাতু দিয়ে তৈরি স্থানীয় বাসন তৈরীর কারিগরের Propular Craft-এর ছাপ রয়েছে।\nকুমোর দাদা বস্তা নিয়ে এসেছেন\nআচ্ছা, কী আছে কুমোরের এই বস্তার মধ্যে?\nকুমোরের বস্তা খুলে দেখতে পেলাম\nবস্তার মধ্যে রয়েছে মিষ্টি একটা বাটি\nআমাদের পুচকিটা কুমোরকে জিজ্ঞাসা করল\nকেমন এই ছোট্ট বাটি!\nগীত আর লোরির মতোই রঙ্গোলি প্রতিযোগিতাও খুব জনপ্রিয় হয়েছিল। এতে অংশ নেওয়া প্রতিযোগীরা দারুণ দারুণ রঙ্গোলি বানিয়ে পাঠিয়েছেন। এতে বিজয়ী এন্ট্রি ছিল পঞ্জাবের কমল কুমার জী-র। ইনি নেতাজি সুভাষচন্দ্র বসু এবং অমর শহীদ বীর ভগৎ সিংহের খুব সুন্দর রঙ্গোলি বানিয়েছেন। মহারাষ্ট্রের সাংলির শচীন নরেন্দ্র অওসারি’জী নিজের রঙ্গোলিতে জালিয়ানওয়ালাবাগ, সেখানকার নরসংহার আর শহীদ উধম সিংহের বীরত্ব ফুটিয়ে তুলেছেন।\nগোয়ার বাসিন্দা গুরুদত্ত ওয়ান্তেকার গান্ধীজির রঙ্গোলি তৈরি করেছিলেন, অন্যদিকে পুদুচেরির মালাতিসেলভম জি’ও অনেক মহান স্বাধীনতা সংগ্রামীদের উপর মনোনিবেশ করেছিলেন। দেশাত্মবোধক গানের প্রতিযোগিতার বিজয়ী, টি. বিজয় দুর্গা’জী অন্ধ্র প্রদেশের মানুষ। তিনি তেলুগু ভাষায় নিজের এন্ট্রি পাঠিয়েছিলেন। তিনি নিজের অঞ্চলের প্রসিদ্ধ স্বাধীনতা সংগ্রামী নরসিংহ রেড্ডি গারুজী দ্বারা অনুপ্রাণিত হয়েছিলেন। আপনারাও বিজয় দুর্গা’জী সেই এন্ট্রির কিছুটা অংশ শুনুন\n(Telugu Sound Clip (27 seconds) HINDI Translation)\nরেনাড়ু প্রদেশের সূর্য,\nহে বীর নরসিংহ!\nভারতীয় স্বাধীনতা সংগ্রামের অংকুর তুমি, অঙ্কুশ তুমি!\nব্রিটিশদের অন্যায় ও স্বৈরাচারী দমন-পীড়নের ঘটনা দেখে।\nতোমার রক্ত গরম হয়েছিল এবং আগুন জ্বলেছিল!\nরেনাড়ু প্রদেশের সূর্য,\nহে বীর নরসিংহ!\nতেলেগুর পরে, এখন আমি আপনাকে মৈথিলীতে একটি ক্লিপ শোনাব। এটি পাঠিয়েছেন দীপক বৎস’জী। এই প্রতিযোগিতায় তিনি পুরস্কারও জিতেছেন।\n(Maithili Sound Clip (30 seconds) HINDI Translation)\nভারত বিশ্বের গর্ব ভাই,\nআমাদের দেশ মহান\nতিন দিক সাগরে ঘেরা,\nউত্তরে কৈলাস বলবান,\nগঙ্গা, যমুনা, কৃষ্ণা, কাবেরী,\nকোশি, কমলা, বলান\nআমাদের দেশ মহান ভাই।\nতেরঙা অন্ত প্রাণ\nবন্ধুরা, আশা করি আপনাদের ভালো লেগেছে। প্রতিযোগিতায় অংশ নিয়েছেন এমন এন্ট্রির তালিকা অনেক দীর্ঘ। আপনি সংস্কৃতি মন্ত্রণালয়ের ওয়েবসাইটে গিয়ে, আপনার পরিবারের সাথে তাঁদের দেখুন এবং শুনুন – আপনি অনেক অনুপ্রেরণা পাবেন। আমার প্রিয় দেশবাসী, বেনারসের কথাই হোক, সানাইয়ের কথাই হোক, ওস্তাদ বিসমিল্লাহ খান জীর কথাই হোক, আমার মনোযোগ সেদিকে যাবেই। কয়েকদিন আগে ‘ওস্তাদ বিসমিল্লাহ খান যুব পুরস্কার’ দেওয়া হয়েছে। সঙ্গীত ও পারফর্মিং আর্ট এর ক্ষেত্রে উদীয়মান, প্রতিভাবান শিল্পীদের এই পুরস্কার দেওয়া হয়। এই পুরস্কার শিল্প, কলা ও সঙ্গীত জগতের জনপ্রিয়তা বৃদ্ধির পাশাপাশি, সমৃদ্ধিতেও অবদান রাখছে। এর মধ্যে এমন শিল্পীরাও অন্তর্ভুক্ত যাঁরা সেই সকল বাদ্যযন্ত্রগুলির নবজাগরণ ঘটিয়েছেন, যাদের জনপ্রিয়তা সময়ের সাথে কমে যাচ্ছিল। এখন, আপনারা সবাই এই টিউনটি মন দিয়ে শুনুন…\n(Sound Clip (21 seconds) Instrument- ‘ সুরসিঙ্গার’, Artist – জয়দীপ মুখার্জী)\nআপনি কি জানেন এটি কোন বাদ্যযন্ত্র? আপনি হয়তো জানেন না! এই বাদ্যযন্ত্রের নাম ‘সুরসিঙ্গার’ এবং এই সুরটি রচনা করেছেন জয়দীপ মুখার্জি।\nওস্তাদ বিসমিল্লাহ খান পুরস্কারে সম্মানিত যুবকদের মধ্যে জয়দীপ জি একজন । ৫০ ও ৬০-এর দশকে থেকেই এই বাদ্যযন্ত্রের সুর শুনতে পাওয়া দুর্লভ হয়ে পড়লেও জয়দীপ সুরসিঙ্গারকে আবার জনপ্রিয় করার সর্বাত্মক চেষ্টা চালিয়ে যাচ্ছেন। একইভাবে, বোন উপ্পলপু নাগমণি জি’র প্রচেষ্টাও অত্যন্ত অনুপ্রেরণাদায়ক, যাঁকে ম্যান্ডোলিনে কর্নাটকী ইন্সট্রুমেন্টালের জন্য এই পুরস্কার দেওয়া হয়েছে। আবার সংগ্রাম সিং সুহাস ভান্ডারে জি বারকরি কীর্তনের জন্য এই পুরস্কার পেয়েছেন। এই তালিকায় শুধু সঙ্গীত শিল্পীই আছেন এমন নয় – ভি দুর্গা দেবী’জি ‘করকাট্টম’, একটি প্রাচীন নৃত্যশৈলীর জন্য এই পুরস্কার জিতেছেন। এই পুরস্কারের আরেকজন বিজয়ী, রাজ কুমার নায়ক জী, তেলেঙ্গানার ৩১টি জেলায় ১০১ দিন ধরে চলা পেরিনি ওডিসির আয়োজন করেছিলেন। আজ সকলে তাঁকে পেরিনি রাজকুমার নামেই চেনে। পেরিনি নাট্যম, ভগবান শিবকে উৎস্বর্গীকৃতএকটি নৃত্য, কাকাতিয়া রাজবংশের সময় খুব জনপ্রিয় ছিল। এই রাজবংশের শিকড় আজকের তেলেঙ্গানার সাথে সম্পর্কিত। আর একজন পুরস্কার বিজয়ী হলেন সাইখোম সুরচন্দ্রা  সিং।\nইনি মাইতেই পুং যন্ত্রটি তৈরিতে তার দক্ষতার জন্য প্রসিদ্ধ. এই বাদ্যযন্ত্রটির মনিপুরের সঙ্গে যোগ আছে। পুরন সিংহ, যিনি একজন দিব্যাংগ শিল্পী, যিনি রাজুলা মালুশাহী,নিউলি, হুড়কা বল, জাগারের মতো সংগীতের বিভিন্ন ধারাকে জনপ্রিয় করে তোলার চেষ্টা চালিয়ে যাচ্ছেন। তিনি এই সংক্রান্ত বেশ কিছু অডিও রেকর্ডিংও করেছেন। উত্তরাখন্ড এর লোকসঙ্গীতে নিজের উৎকর্ষের নিদর্শন রেখে তিনি বেশ কিছু পুরস্কারও পেয়েছেন। সময়ের অপ্রতুলতার কারণে আমি এখানে সব পুরস্কার প্রাপকদের নাম না নিতে পারলেও, আমি আশাবাদী যে আপনারা ওঁদের সম্পর্কে নিশ্চই খোঁজ রাখবেন। আমি এও আশা রাখি যে এই সব শিল্পীরা তাদের Performing Arts কে আরো জনপ্রিয় করে তোলার জন্য তৃণমূল স্তরে গিয়ে সকলকে অনুপ্রাণিত করবেন। আমার প্রিয় দেশবাসী, আমাদের দেশ এখন দ্রুত গতিতে এগিয়ে চলেছে। দেশের বিভিন্ন কোণায় আমরা ডিজিটাল ইন্ডিয়ার শক্তি উপলব্ধি করতে পারছি। ডিজিটাল ইন্ডিয়ার শক্তিকে ঘরে ঘরে পৌঁছনোর পেছনে অনেকগুলো apps এর ভূমিকা অনস্বীকার্য। এমনি একটি app হলো ই-সঞ্জীবনী।  এই app এর সাহায্যে টেলি -কন্সালটেশন অর্থাৎ দূরে বসেই ভিডিও কনফারেন্সিঙের মাধ্যমে ডক্টরের কাছ থেকে আপনার রোগ ব্যাধি নিয়ে আলোচনা করা সম্ভব। এই app ব্যবহার করে এখনো পর্যন্ত ১০ কোটিরও বেশি মানুষ টেলি কন্সালটেশন করেছেন। আপনারা ভাবতে পারেন !  ১০ কোটি লোক ভিডিও কন্সালটেশন করেছেন! রুগী ও চিকিৎসকের মধ্যে একটা সম্পর্ক তৈরী হলো, এটা একটা বিরাট প্রাপ্তি। আর এই প্রাপ্তির জন্য আমি সকল চিকিৎসক এবং এই সুবিধাপ্রাপ্ত সকল রুগীদের আন্তরিক শুভেচ্ছা জানাই। ভারতবাসীরা, কিভাবে এই প্রযুক্তিকে নিজেদের জীবনের অঙ্গ করেছেন এটি তার উজ্জ্বল দৃষ্টান্ত। আমরা দেখেছি কোরোনাকালে কিভাবে এই ই-সঞ্জীবনী app এর মাধ্যমে হওয়া টেলিকনসালটেশন কত মানুষের কাছে একটা আশীর্বাদ হয়ে দাঁড়িয়েছিল। আমার মনে হলো যে এই নিয়ে “মন কি বাতে” একজন চিকিৎসক ও রুগীর সঙ্গে আলোচনা করা যাক, তাদের কথা শোনা যাক এবং আপনাদের কাছে সেটা পৌঁছানো যাক। আমরা জানতে চাইবো যে এই টেলি কন্সালটেশন মানুষের জন্য কতটা উপকারী।  আমাদের সঙ্গে আছেন সিক্কিমের এক চিকিৎসক, ডাক্তার মদন মণি’জী ।ডাক্তার মদন মণি’জী, সিক্কিমের বাসিন্দা ঠিকই কিন্তু তিনি তার MBBS ধানবাদ থেকে করেছেন এবং তারপর বেনারস হিন্দু ইউনিভার্সিটি থেকে MD করেছেন। উনি বিভিন্ন গ্রামীণ অঞ্চলের বহু মানুষদের টেলি কন্সালটেশন দ্বারা  চিকিৎসা করেছেন।\nপ্রধানমন্ত্রী – নমস্কার.. নমস্কার… মদন মণি’জী।\nডা: মদন মণি – নমস্কার স্যার।\nপ্রধানমন্ত্রী – আমি নরেন্দ্র মোদী বলছি।\nডা: মদন মণি– হ্যাঁ.. হ্যাঁ.. বলুন স্যার।\nপ্রধানমন্ত্রী – আপনি তো বেনারসে পড়াশোনা করেছেন?\nডা: মদন মণি– হ্যাঁ.. স্যার আমি বেনারসে পড়াশোনা করেছি।\nপ্রধানমন্ত্রী – আপনার medical education ওখানেই হয়েছে?\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ..\nপ্রধানমন্ত্রী – তাহলে আপনি যেসময় বেনারসে ছিলেন, সেই তখনকার বেনারস আর এখনকার বদলে যাওয়া বেনারস কখনও দেখতে গেছেন নাকি যাওয়া হয়নি?\nডা: মদন মণি – হ্যাঁ প্রধানমন্ত্রী’জী আমি যেতে পারিনি, যবে থেকে সিকিমে চলে এসেছি, কিন্তু আমি শুনেছি যে বেশ পরিবর্তন ঘটেছে।\nপ্রধানমন্ত্রী – তো কত বছর হয়ে গেল আপনি বেনারস ছেড়েছেন?\nডা: মদন মণি – বেনারস 2006 সালে ছেড়ে এসেছি, স্যার।\nপ্রধানমন্ত্রী – ওহ আচ্ছা.. তাহলে আপনার নিশ্চয় একবার যাওয়া উচিৎ।\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ.. স্যার।\nপ্রধানমন্ত্রী – আচ্ছা, আমি ফোন করেছি, এই কারণে যে আপনি সিকিমের ভেতরে প্রত্যন্ত পাহাড়ে থেকে বসবাসকারী জনগণকে টেলিকনসালটেশনের দুর্দান্ত পরিষেবা প্রদান করছেন।\nডা: মদন মণি – হ্যাঁ..\nপ্রধানমন্ত্রী – আমি মন কি বাতের শ্রোতা বন্ধুদের আপনার অভিজ্ঞতাশোনাতে চাই।\nডা: মদন মণি – আচ্ছা..\nপ্রধানমন্ত্রী – একটু বলুন আমাকে, কেমন অভিজ্ঞতা ছিল?\nডা: মদন মণি – অভিজ্ঞতা খুব ভালো ছিল প্রধানমন্ত্রী জি। ব্যাপারটা হল, সিকিমে, খুব কাছাকাছিও যে PHC রয়েছে, সেখানে যেতেও লোকজনেদের গাড়িতে চেপে কমপক্ষে এক-দুশো টাকা নিয়ে যেতে হতো। আর ডাক্তার পাওয়া যায়, কি না পাওয়া যায়, সেটাও একটা problem। তাই Tele Consultation-এর মাধ্যমে মানুষ আমাদের সঙ্গে সরাসরি যুক্ত হতে পারেন, এমনকি দূর দূরান্তের মানুষও। Health & Wellness Centre-এর যারা CHOs রয়েছেন, তারাও আমাদের, মানুষের সঙ্গে যোগাযোগ করিয়ে দেন। আর আমরা, যদি তাদের কোন পুরনো অসুখ থাকে তার reports, তার এখনকার present condition, ইত্যাদি  সবকিছুই তাদের জানিয়ে দি।\nপ্রধানমন্ত্রী – মানে document transfer করেন।\nডা: মদন মণি – হ্যাঁ.. হ্যাঁ। Document transferও করি এবং যদি transfer করতে না পারি, তাহলে আমরা তা মানুষদের পড়ে শোনাই।\nপ্রধানমন্ত্রী – ওখানের Wellness Centre-এর doctor বলে দেন।\nডা: মদন মণি – হ্যাঁ, Wellness Centre-এর যে CHO থাকেন তিনি, Community Health Officer।\nপ্রধানমন্ত্রী – আর যারা patient, তারা নিজেদের অসুবিধার বিষয়ে আপনাদের সরাসরি বলেন।\nডা: মদন মণি – হ্যাঁ, patientও নিজের অসুবিধা আমাদের জানান। তারপর পুরনো records দেখে, আবার যদি নতুন কিছু পাওয়া যায় তা জানানো হয়। ধরুন, যদি কারোর Chest Auscultate করাতে হয়, তাহলে জানা দরকার তার পা ফোলা নেই তো! যদি CHO তা না দেখে থাকেন, তাহলে আমরা সেই ব্যক্তিকে বলি যে সে যেন পরীক্ষা করায় তার ফোলা রয়েছে কি নেই, চোখ দেখাতে বলা হয়, anaemia রয়েছে কিনা, যদি তার কাশি হয়ে থাকে তাহলে Chest-এর  Auscultate করিয়ে জানা দরকার সেখানে sounds রয়েছে কিনা।\nপ্রধানমন্ত্রী – আপনি Voice Call-এ কথা বলেন না Video Call-এরও ব্যবহার করেন?\nডা: মদন মণি – হ্যাঁ, Video Call-এরও ব্যবহার করি।\nপ্রধানমন্ত্রী – তাহলে patient-কে, আপনিও দেখতে পান?\nডা: মদন মণি – হ্যাঁ, patient-কেও দেখতে পাই।\nপ্রধানমন্ত্রী – Patient-এর কি রকম feeling হয়?\nডা: মদন মণি – Patient-এর ভালই লাগে কারণ ডাক্তারকে তারা এত কাছে দেখতে পায়। তাদের confusion থাকে যে তাদের ওষুধ বাড়ানো হবে না কমানো হবে, কারণ সিকিমে বেশিরভাগ patient diabetes, Hypertension ইত্যাদিতে ভোগে, একটা diabetes ও hypertension-এর ওষুধ change করানোর জন্য তাঁকে ডাক্তারের সঙ্গে দেখা করতে অনেক দূর যেতে হয়। কিন্তু Tele Consultation-এর মাধ্যমে ওখানেই পরামর্শ পাওয়া যায় আর ওষুধও health & Wellness Centre-এ  Free Drugs initiative-এর দরুন পাওয়া যায়। তাই একই জায়গা থেকেই ওষুধও নিয়ে যেতে পারে সবাই।\nপ্রধানমন্ত্রী – আচ্ছা মদনমণি জি, আপনি তো জানেন যে patient-দের একটা স্বভাব রয়েছে যে যতক্ষণ না ডাক্তার আসছেন, এবং দেখছেন, ততক্ষণ সে সন্তুষ্ট হয় না, আর ডাক্তারেরও মনে হয় রোগীকে দেখতে হবে, তাহলে এখানে যে পুরো ব্যাপারটাই Telecom-এর Consultation-এর মাধ্যমে হচ্ছে, তখন সেখানে ডাক্তার কি feel করছে, patient-টি বা কি feel হচ্ছে?\nডা: মদন মণি – হ্যাঁ, আমাদেরও মনে হয় যদি patient মনে করেন যে ডাক্তারের দেখা উচিত, তাহলে যা যা দেখা প্রয়োজন, তা আমরা CHO-কে বলে video-তেই দেখাবার কথা বলি। আর কখনো কখনো তো patient-কে video-তেই কাছে এসে তার যা সমস্যা রয়েছে, ধরুন কারুর যদি চামড়ার কোন problem হয়েছে, skin-এর problem হয়েছে, তখন আমরা তার সমস্যা video-তেই দেখিয়ে দি।  তাই তাঁরাও সন্তুষ্টি হন।\nপ্রধানমন্ত্রী – আর তারপর রোগীকে পরিষেবা দেবার পর তিনি যখন খুশি হন তখন কি রকম অনুভব হয়? রোগী কি সুস্থ হচ্ছেন?\nডা: মদন মণি – হ্যাঁ খুব ভালো লাগে। আমাদেরও ভালো লাগে স্যার। কারন আমি এখন স্বাস্থ্য বিভাগে আছি আর এর সঙ্গে আমি টেলি কনসাল্টেশন ও করি, তাই ফাইলের সঙ্গে সঙ্গে পেশেন্টদের দেখাশোনা করাও আমায় অনেক আনন্দের অনুভূতি দেয়।\nপ্রধানমন্ত্রী – গড়ে কতজন রোগীর টেলিকনসাল্টেশন কেস আপনার কাছে আসে?\nডা: মদন মণি – এখন অবধি আমি ৫৩৬ জন রোগী দেখেছি।\nপ্রধানমন্ত্রী – ওহ অর্থাৎ আপনার এই বিষয়ে অনেকটা দক্ষতা এসে গেছে।\nডা: মদন মণি – হ্যাঁ ভালো লাগে দেখতে।\nপ্রধানমন্ত্রী – আমি আপনাকে শুভেচ্ছা জানাচ্ছি। এই টেকনোলজির মাধ্যমে আপনি  সিকিমের দূর দূরান্তের জঙ্গলে, পাহাড়ের বাসিন্দাদের এত বড় পরিষেবা দিচ্ছেন। আর খুশির কথা এটাই যে আমাদের দেশের প্র্রান্তিক ক্ষেত্রেও এই টেকনোলজির এত সুন্দর ব্যবহার হচ্ছে। আমার তরফ থেকে আপনাকে অনেক অনেক অভিনন্দন।\nডা: মদন মণি – ধন্যবাদ।\nবন্ধুরা ডঃ মদন মনির কথা থেকে পরিষ্কার বোঝা যাচ্ছে যে এই ই-সঞ্জীবনী অ্যাপ কিভাবে ওনার সাহায্য করছে। ডক্টর মদন জি’র পরে আমরা আরো এক মদনজির সঙ্গে কথা বলব। ইনি  হলেন উত্তরপ্রদেশের চন্দৌলি জেলার অধিবাসী মদন মোহন লাল জি। এখন এটাও একটা অদ্ভুত বিষয় যে চন্দৌলিও বেনারসের পাশেই অবস্থিত। আসুন মদনমোহন জি’র কাছ থেকে জানি যে ই-সঞ্জীবনী কে নিয়ে একজন রোগী হিসেবে ওনার অনুভূতি কি রকম?\nপ্রধানমন্ত্রী – মদন মোহন জি প্রণাম।\nমদন মোহন জি – নমস্কার, নমস্কার সাহেব।\nপ্রধানমন্ত্রী – নমস্কার। আচ্ছা আমাকে এটা বলা হয়েছে যে আপনি ডায়াবেটিসের রোগী।\nমদন মোহন জি – হ্যাঁ।\nপ্রধানমন্ত্রী – আর আপনি টেকনোলজির সাহায্যে টেলিকনসালটেশন করে আপনার রোগের সম্বন্ধে সাহায্য নেন।\nমদন মোহন জি – হ্যাঁ।\nপ্রধানমন্ত্রী – একজন পেশেন্ট হয়ে আমি আপনার অনুভূতি শুনতে চাই, যাতে আমি দেশবাসীর কাছে এই কথাটা পৌঁছে দিতে পারি যে আজ টেকনোলজির মাধ্যমে আমাদের গ্রামের মানুষেরাও কিভাবে এর সাহায্য নিতে পারেন। একটু বলুন কিভাবে ব্যবহার করেন?\nমদন মোহন জি – আসলে স্যার হসপিটাল অনেক দূরে আর আমার যখন ডায়াবেটিস হলো তখন আমাকে ৫-৬ কিলোমিটার দূরে গিয়ে চিকিৎসা করাতে হতো, ডাক্তার দেখাতে হতো। যখন থেকে আপনার দ্বারা এই ব্যবস্থা করা হয়েছে তখন থেকে আমি যাই, আমার পরীক্ষা করা হয়, আমাদের বাইরের ডাক্তারদের সঙ্গে কথাও বলিয়ে দেওয়া হয় আর ওষুধও দিয়ে দেওয়া হয়। এর ফলে আমার ও আমার মতো অনেক মানুষের  লাভ হল।\nপ্রধানমন্ত্রী – তাহলে প্রতিবার কী একই ডাক্তারবাবু দেখেন; না কী ডাক্তার বদলে যায়?\nমদন মোহন জি – যখন সে বুঝতে পারেন না, তখন ডাক্তারবাবুকে দেখায়। তারপর তিনিই কথা বলে অন্য ডাক্তারের সঙ্গে আমার কথা বলিয়ে দেয়।\nপ্রধানমন্ত্রী – আর ডাক্তার আপনাকে যে গাইডেন্স (guidance) দেয় তাতে কি আপনার সম্পূর্ণ লাভ হয়?\nমদন মোহন জি – হ্যাঁ লাভ তো হয়েই, এতে আমার অনেক সুবিধা হয়। আর গ্রামের লোকজনেরো সুবিধা হয়। সবাই ওখানেই বলেন যে দাদা আমাদের BP আছে বা সুগার আছে, Test করুন বা পরীক্ষা নিরীক্ষা করুন, ওষুধ দিন। আর আগে তো ৫-৬ কিলোমিটার দূরে যেতে হতো। লম্বা লম্বা লাইন পড়তো। Pathology-তেও লাইন পড়তো, একটা গোটা দিন নষ্ট হয়ে যেতো।\nপ্রধানমন্ত্রী – মানে আপনার সময়-ও বেঁচে যাচ্ছে!\nমদন মোহন জি – তাছাড়া পয়সা’ও খরচ হতো, আর এখানে বিনামূল্যে সব পরিষেবা পাচ্ছি।\nপ্রধানমন্ত্রী – আচ্ছা, যখন আপনি সামনাসামনি ডাক্তারের সঙ্গে দেখা করেন তখন একটা ভরসা তৈরি হয়। মনে হয় অন্তত ডাক্তারবাবু আছেন, আমার পালস দেখে নিয়েছেন, চোখ পরীক্ষা করেছেন, আমার জিভ চেক করেছেন; মানে একটা অন্যরকম feeling কাজ করে, কিন্তু যখন এই tele consultation এর সাহায্য নিতে হয় তখন কী সেই একই রকম ভরসা তৈরি হয়?\nমদন মোহন জি – হ্যাঁ, অবশ্যই ভরসা তৈরি হয়! উনি আমার নাড়ি পরীক্ষা করছেন, স্টেথোস্কোপে শ্বাস পরীক্ষা করছেন- এরকমই একটা অনুভূতি আমার হয়, আর আমার শরীরটাও বেশ ভালো লাগে। এতো সুন্দর একটা ব্যবস্থা আপনার জন্য আমরা পেয়েছি যে তার ফলে আমাদের কষ্ট করে যেখানে যেতে হতো, গাড়ির ভাড়া দিতে হতো, লাইন দিতে হতো, সেখানে সব পরিষেবা আমরা ঘরে বসে বসেই পেয়ে যাচ্ছি।\nপ্রধানমন্ত্রী – আচ্ছা মদন মোহন জি, আপনাকে অনেক অনেক অভিনন্দন। এই বয়সে এসেও আপনি technology সম্পর্কে জেনেছেন, এর ব্যবহার-ও করছেন। অন্যদেরও বলুন যাতে তাদের সময় বেঁচে যায়, খরচও বেঁচে যায়, আর তাঁদের যে উপায় বাতলে দেওয়া হয় সেইমতো ওষুধ পেতেও কোন অসুবিধা হয় না।\nমদন মোহন জি – হ্যাঁ, সেই আর কি!\nপ্রধানমন্ত্রী – আচ্ছা আপনাকে অনেক অনেক শুভেচ্ছা মদন মোহন জি।\nমদন মোহন জি – সাহেব, আপনি বেনারসকে কাশি বিশ্বনাথ স্টেশন করেছেন। আপনার জন্যে Devlopment হয়েছে । তাই আপনাকে আমাদের তরফ থেকে অভিনন্দন।\nপ্রধানমন্ত্রী – আপনাকেও অসংখ্য ধন্যবাদ, তবে আমি নয়, বেনারসের মানুষই বেনারসকে গড়ে তুলেছে\u200cন, আমি তো শুধুই মা গঙ্গার সেবার জন্যে এখানে, মা গঙ্গা’ই আমাকে ডেকেছেন, ব্যাস এটুকুই। আচ্ছা ঠিক আছে, আপনাকে অনেক অনেক শুভেচ্ছা। প্রনাম।\nমদন মোহন জি – নমস্কার স্যার।\nপ্রধানমন্ত্রী – হ্যাঁ নমস্কার!\nবন্ধুগণ, দেশের সাধারণ মানুষের জন্য, মধ্যবিত্তদের জন্য, পাহাড়ি এলাকার বাসিন্দাদের জন্য  E- Sanjivani., নামে জীবন রক্ষার অ্যাপ তৈরি হয়েছে। এটি হলো ভারতবর্ষের ডিজিটাল বিপ্লবের শক্তি। আর তার প্রভাব আমরা প্রতিটি ক্ষেত্রেই দেখতে পাচ্ছি। আপনারা তো জানেনই ভারতের ইউপিআই এর ক্ষমতা। বিশ্বের বহু দেশ এর প্রতি আকৃষ্ট। কিছুদিন পূর্বেই ভারত আর সিঙ্গাপুরের মধ্যে upi pay now link লঞ্চ করা হয়েছে। এখন ভারত আর সিঙ্গাপুর বাসীরা নিজেদের মোবাইল ফোন থেকে ঠিক সেই ভাবেই পয়সার লেনদেন করছেন যেভাবে তারা নিজেদের দেশে করে থাকেন। আমি খুবই আনন্দিত যে জনগণ এর সুযোগ নেওয়া শুরু করে দিয়েছে। ভারতের ই সঞ্জীবনী app  বলুন বা UPI, এগুলি Ease of Living কে আরো উন্নত করতে সাহায্য করেছে।\nআমার প্রিয় দেশবাসী। যখন কোন দেশে, বিলুপ্তপ্রায় কোন বিশেষ পাখির প্রজাতিকে, বা কোন জীবকে বাঁচানো হয়, তখন সারা বিশ্বে সেটার চর্চা হয়। আমাদের দেশে এমন অনেক মহান পরম্পরা আছে যেগুলি বিলুপ্ত হয়ে গিয়েছিল, জনমানস থেকে মুছে গিয়েছিল, কিন্তু এখন জনগণের অংশগ্রহণের ফলে ফের পুনর্জীবিত হয়ে উঠেছে আর তার চর্চার জন্য  মন কি বাতের মঞ্চের চেয়ে ভালো কি কিছু হতে পারে?\nএখন আমি আপনাদের যা বলতে চলেছি, সেটা জেনে আপনাদের সত্যিই খুব ভালো লাগবে এবং ঐতিহ্যের প্রতি গর্ববোধ করবেন। আমেরিকার নিবাসী শ্রীমান কাঞ্চন ব্যানার্জি ঐতিহ্যের সংরক্ষণের কাজের যুক্ত একটি অভিযানের দিকে আমার নজর আকৃষ্ট করেছেন। আমি ওনাকে অভিনন্দন জানাই। বন্ধুগণ, পশ্চিমবঙ্গের হুগলি জেলায় বাঁশবেড়িয়াতে এই মাসে ত্রিবেণী কুম্ভ মহোৎসবের আয়োজন করা হয়েছে। এতে ৮ লাখেরও বেশি ভক্তের সমাগম ঘটেছে। কিন্তু আপনারা কি জানেন এই মেলা  কেন এত গুরুত্বপূর্ণ? এই জন্য গুরুত্ব পূর্ণ কারণ বিশেষ এই জন্য কারণ এই মেলাটিকে ৭০০ বছরের পর আবার পুনর্জীবিত করে তোলা হয়েছে। এমনিতেই এই পরম্পরা হাজার বছরেরও বেশি পুরনো, কিন্তু দুর্ভাগ্যবশত ৭০০ বছর আগে বাংলার ত্রিবেণী তে এই মহোৎসবটি বন্ধ গিয়েছিল। স্বাধীনতার পর এটিকে আবার শুরু করা উচিত ছিল কিন্তু সেটাও হয়ে ওঠেনি। দু’বছর আগে স্থানীয় বাসিন্দারা এবং ত্রিবেণী কুম্ভ পরিচালনা সমিতির উদ্যোগে এই মহোৎসবটি আবার আরম্ভ করা হয়েছে। এই আয়োজনের সঙ্গে যুক্ত সব্বাইকে সাধুবাদ  জানাই। আপনারা কেবলমাত্র একটি প্রথাকে জীবিত করে তুলছেন তা না; বরং ভারতবর্ষের সাংস্কৃতিক ঐতিহ্যকে রক্ষাও করছেন।\nবন্ধুগণ , পশ্চিমবঙ্গের ত্রিবেণীকে যুগ যুগ ধরে একটি  পবিত্র স্থান  বলে মনে করা হয়। এটার উল্লেখ বিভিন্ন মঙ্গল কাব্যে, বৈষ্ণব সাহিত্যে, শাক্ত সাহিত্যে ও অন্যান্য বাংলা সাহিত্যের ধারায় লক্ষ্য করা যায়। বিভিন্ন ঐতিহাসিক দলিল থেকে এইটা জানা যায় যে এই ঐতিহাসিক স্থানটি কোন এক সময় সংস্কৃত, শিক্ষা, ও ভারতীয় সংস্কৃতির কেন্দ্র ছিল। অনেক সাধুরাই এই স্থানটিকে মাঘ সংক্রান্তির কুম্ভ স্নানের জন্য পবিত্র মনে করেন। ত্রিবেণীতে আপনারা অনেক গঙ্গার ঘাট, শিব মন্দির ও টেরাকোটার কারুকার্য খচিত প্রাচীন ঘর-বাড়ি ইত্যাদি দেখতে পাবেন। ত্রিবেনীর ঐতিহ্যকে পুনঃস্থাপন করার জন্য ও কুম্ভ মেলার গৌরবকে পুনর্জীবিত করার জন্য এখানে গতবছর কুম্ভ মেলার আয়োজন করা হয়েছিল। সাতশো বছর পর এই  তিন দিন ব্যাপী কুম্ভ মহাস্নান ও মেলা এই ক্ষেত্রে। এক নতুন প্রাণশক্তির সঞ্চার ঘটিয়েছে। তিন দিন ধরে প্রত্যেক দিনের গঙ্গা আরতি, রুদ্রাভিষেক ও যজ্ঞে বহু মানুষ দলে দলে যোগ দিয়েছেন। এইবারের মহোৎসবে বিভিন্ন আশ্রম মঠ ও আখড়া থেকেও অনেকেই যোগদান করেছেন। বাঙালির সংস্কৃতির সঙ্গে যুক্ত বিভিন্ন ধারা যেমন কীর্তন, বাউল , গৌড়ীয়ন নৃত্য, শ্রীখোল, পটের গান, ছৌ নাচ, সান্ধ্য অনুষ্ঠানের আকর্ষণের কেন্দ্র হয়ে উঠেছিল। আমাদের দেশের তরুণদের তাদের সোনালী অতীতের সঙ্গে যুক্ত করার এটি একটি  অত্যন্ত প্রশংসনীয় প্রয়াস। ভারতবর্ষে এমন বহু প্রথা আছে যেগুলিকে রিভাইভ করা অত্যন্ত প্রয়োজনীয়। আমি আশা করি যে এই সমস্ত বিষয়ের উপর আলোচনা এইদিকে এগিয়ে যেতে অনুপ্রাণিত করবে।\nআমার প্রিয় দেশবাসী, স্বচ্ছ ভারত অভিযান আমাদের দেশে জন-অংশীদারিত্বের অর্থই বদলে দিয়েছে। দেশের যে কোন স্থানে যদি স্বচ্ছতা সম্পর্কিত কোন কর্মসূচি চলে, তাহলে মানুষ তার খবর আমাকে অতি অবশ্যই পৌঁছে দেন। 

In [ ]:
pip install -U bnlp_toolkit

Requirement already satisfied: bnlp_toolkit in /usr/local/lib/python3.11/dist-packages (4.0.3)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (0.2.0)
Requirement already satisfied: gensim==4.3.2 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (4.3.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (1.26.4)
Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (1.10.1)
Requirement already satisfied: sklearn-crfsuite==0.3.6 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (0.3.6)
Requirement already satisfied: tqdm==4.66.3 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (4.66.3)
Requirement already satisfied: ftfy==6.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (6.2.0)
Requirement already satisfied: emoji==1.7.0 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (1.7.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (2.32.3)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/lib/python3.11/dist-packages (from ftfy==6.2.0->bnlp_toolkit) (0.2.13)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.2->bnlp_toolkit) (7.3.0)
Requirement already satisfied: python-crfsuite>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (0.9.11)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (0.9.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (2024.11.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2025.6.15)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.2->bnlp_toolkit) (1.17.2)

In [ ]:
import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from bnlp import BengaliPOS, BasicTokenizer, CleanText  # For accurate Bengali POS tagging
from functools import lru_cache
import re
from typing import List, Dict, Tuple

In [ ]:
# Configuration
MODEL_NAME = "facebook/nllb-200-distilled-1.3B"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 1  # Optimal for most GPUs
SRC_LANG = "ben_Beng"
TGT_LANG = "eng_Latn"
ben_token = BasicTokenizer()

In [ ]:
# Initialize models
print("Loading models...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(DEVICE)
bn_pos = BengaliPOS()  # Bengali POS tagger

# POS tags to target (using Universal POS tags)
TARGET_POS_TAGS = {
    "NC",    # Common Noun (বই, গাছ)
    "NP",    # Proper Noun (ঢাকা, রহিম)
    "NV",    # Verbal Noun (পড়া, করা)
    "VM",    # Main Verb (যাই, খাই)
    "JJ",    # Adjective (সুন্দর, বড়)
    "JQ",    # Quantifier (কয়েক, অনেক)
    "RDF"    # Foreign Words (already likely to be English)
}  # bnlp uses Universal POS tags

Loading models...

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/808 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/5.48G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/5.48G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [ ]:
@lru_cache(maxsize=5000)  # Cache up to 5000 most frequent translations
def translate_word(word: str) -> str:
    """Cached single-word translation with error handling"""
    try:
        # Set source and target languages for the tokenizer
        tokenizer.src_lang = SRC_LANG
        tokenizer.tgt_lang = TGT_LANG

        inputs = tokenizer(word, return_tensors="pt").to(DEVICE)
        outputs = model.generate(
            **inputs,
            max_length=20,
        )
        return tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        print(f"Error translating '{word}': {str(e)}")
        return word

In [ ]:
def batch_translate(words: List[str]) -> List[str]:
    """Process words in batches for efficiency"""
    translations = []
    # Set source and target languages for the tokenizer
    tokenizer.src_lang = SRC_LANG
    tokenizer.tgt_lang = TGT_LANG

    for i in range(0, len(words), BATCH_SIZE):
        batch = words[i:i+BATCH_SIZE]
        inputs = tokenizer(batch, return_tensors="pt", padding=True).to(DEVICE)
        outputs = model.generate(
            **inputs,
            max_length=20,
        )
        translations.extend(tokenizer.batch_decode(outputs, skip_special_tokens=True))
    return translations

In [ ]:
def get_word_pos_pairs(sentence: str) -> List[Tuple[str, str]]:
    """Accurate Bengali POS tagging using bnlp"""
    # Tokenize preserving punctuation
    clean_text = CleanText(
        fix_unicode=True,
        unicode_norm=True,
        unicode_norm_form="NFKC",
        remove_url=True,
        remove_email=True,
        remove_emoji=True,
        remove_number=True,
        remove_digits=True,
        remove_punct=True
    )
    sentence = clean_text(sentence)
    tokens = ben_token(sentence)
    # Get POS tags for Bengali words (skip punctuation)
    words = [t for t in tokens]
    pos_tags = bn_pos.tag(" ".join(words))
    print(pos_tags)
    # Reconstruct with original tokens
    pos_map = {word: tag for word, tag in pos_tags}
    return [(token, pos_map.get(token, "PUNCT")) for token in tokens]

In [ ]:
def code_mix_sentence(sentence: str) -> str:
    """Optimized code-mixing with batch processing"""
    word_pos_pairs = get_word_pos_pairs(sentence)
    to_translate = []
    translate_indices = []

    # Identify words needing translation
    for i, (word, pos) in enumerate(word_pos_pairs):
        if pos in TARGET_POS_TAGS and re.match(r'^[\w]+$', word):
            to_translate.append(word)
            translate_indices.append(i)

    # Batch translate all target words
    if to_translate:
        translations = batch_translate(to_translate)
        # Update only single-word translations
        for idx, trans in zip(translate_indices, translations):
            if " " not in trans and trans != word_pos_pairs[idx][0]:
                word_pos_pairs[idx] = (trans, word_pos_pairs[idx][1])

    # Reconstruct sentence
    mixed = [wp[0] for wp in word_pos_pairs]
    return re.sub(r'\s+([?।!,])', r'\1', ' '.join(mixed))

In [ ]:
# Example usage
if __name__ == "__main__":
    examples = [
        "আমি বই পড়ছি এবং দৌড়াচ্ছি",
        "সে একটি সুন্দর ফুল কিনেছে",
        "গেম খেলা খুব মজার",
        "কম্পিউটার প্রোগ্রামিং শেখা গুরুত্বপূর্ণ",
        """আমার নাম রাহুল এবং আমি কলকাতায় থাকি। প্রতিদিন সকালে আমি আমার মা-বাবার সঙ্গে নাস্তা করি। তারপর আমি বই নিয়ে পড়তে বসি। পড়া শেষ করে আমি পার্কে যাই এবং বন্ধুদের সঙ্গে খেলি।"""
    ]

    print("Optimized Code-Mixing Results:")
    for example in examples:
        print(f"Input:  {example}")
        print(f"Output: {code_mix_sentence(example)}\n")

Optimized Code-Mixing Results:
Input:  আমি বই পড়ছি এবং দৌড়াচ্ছি
[('আমি', 'PPR'), ('বই', 'NC'), ('পড়ছি', 'NC'), ('এবং', 'CCD'), ('দৌড়াচ্ছি', 'NC')]
Output: আমি Liburuak. পড়ছি এবং দৌড়াচ্ছি

Input:  সে একটি সুন্দর ফুল কিনেছে
[('সে', 'PPR'), ('একটি', 'JQ'), ('সুন্দর', 'JJ'), ('ফুল', 'NC'), ('কিনেছে', 'VM')]
Output: সে একটি সুন্দর ফুল কিনেছে

Input:  গেম খেলা খুব মজার
[('গেম', 'NC'), ('খেলা', 'NC'), ('খুব', 'JQ'), ('মজার', 'NC')]
Output: গেম খেলা খুব মজার

Input:  কম্পিউটার প্রোগ্রামিং শেখা গুরুত্বপূর্ণ
[('কম্পিউটার', 'NC'), ('প্রোগ্রামিং', 'NC'), ('শেখা', 'NV'), ('গুরুত্বপূর্ণ', 'JJ')]
Output: কম্পিউটার প্রোগ্রামিং শেখা গুরুত্বপূর্ণ

Input:  আমার নাম রাহুল এবং আমি কলকাতায় থাকি। প্রতিদিন সকালে আমি আমার মা-বাবার সঙ্গে নাস্তা করি। তারপর আমি বই নিয়ে পড়তে বসি। পড়া শেষ করে আমি পার্কে যাই এবং বন্ধুদের সঙ্গে খেলি।
[('আমার', 'PPR'), ('নাম', 'NC'), ('রাহুল', 'NC'), ('এবং', 'CCD'), ('আমি', 'PPR'), ('কলকাতায়', 'NP'), ('থাকি', 'NP'), ('<', 'NP'), ('PUNC', 'NP'), ('>', 'NP'), ('প্রতিদিন', 'NC'), ('সকালে', 'NC'), ('আমি', 'PPR'), ('আমার', 'PPR'), ('মা', 'NC'), ('<', 'RDX'), ('PUNC', 'RDX'), ('<', 'RDX'), ('PUNC', 'RDX'), ('>', 'RDX'), ('PUNC', 'RDX'), ('<', 'RDX'), ('PUNC', 'RDX'), ('>', 'RDX'), ('বাবার', 'NC'), ('সঙ্গে', 'PP'), ('নাস্তা', 'NC'), ('করি', 'VM'), ('<', 'RDX'), ('PUNC', 'RDX'), ('>', 'RDX'), ('তারপর', 'CSB'), ('আমি', 'PPR'), ('বই', 'NC'), ('নিয়ে', 'VM'), ('পড়তে', 'VAUX'), ('বসি', 'NP'), ('<', 'NP'), ('PUNC', 'NP'), ('>', 'NP'), ('পড়া', 'NC'), ('শেষ', 'NC'), ('করে', 'VM'), ('আমি', 'PPR'), ('পার্কে', 'NC'), ('যাই', 'VM'), ('এবং', 'CCD'), ('বন্ধুদের', 'NC'), ('সঙ্গে', 'PP'), ('খেলি', 'NC'), ('<', 'NC'), ('PUNC', 'RDF'), ('>', 'PU')]
Output: আমার নাম রাহুল এবং আমি কলকাতায় থাকি < PUNC > প্রতিদিন সকালে আমি আমার মা < PUNC < PUNC > PUNC < PUNC > বাবার সঙ্গে নাস্তা করি < PUNC > তারপর আমি Liburuak. নিয়ে পড়তে বসি < PUNC > পড়া শেষ করে আমি পার্কে যাই এবং বন্ধুদের সঙ্গে খেলি < PUNC >

In [ ]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Collecting datasets
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.33.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 20.3 MB/s eta 0:00:00
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 11.1 MB/s eta 0:00:00
Installing collected packages: fsspec, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.6.0 fsspec-2025.3.0

In [ ]:
!pip install bnlp_toolkit

Collecting bnlp_toolkit
  Downloading bnlp_toolkit-4.0.3-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (0.2.0)
Collecting gensim==4.3.2 (from bnlp_toolkit)
  Downloading gensim-4.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (2.0.2)
Collecting scipy==1.10.1 (from bnlp_toolkit)
  Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 4.3 MB/s eta 0:00:00
Collecting sklearn-crfsuite==0.3.6 (from bnlp_toolkit)
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting tqdm==4.66.3 (from bnlp_toolkit)
  Downloading tqdm-4.66.3-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 4.7 MB/s eta 0:00:00
Collecting ftfy==6.2.0 (from bnlp_toolkit)
  Downloading ftfy-6.2.0-py3-none-any.whl.metadata (7.3 kB)
Collecting emoji==1.7.0 (from bnlp_toolkit)
  Downloading emoji-1.7.0.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from bnlp_toolkit) (2.32.3)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/lib/python3.11/dist-packages (from ftfy==6.2.0->bnlp_toolkit) (0.2.13)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.2->bnlp_toolkit) (7.3.0)
Collecting numpy (from bnlp_toolkit)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.0 MB/s eta 0:00:00
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite==0.3.6->bnlp_toolkit)
  Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from sklearn-crfsuite==0.3.6->bnlp_toolkit) (0.9.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->bnlp_toolkit) (2024.11.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->bnlp_toolkit) (2025.6.15)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.2->bnlp_toolkit) (1.17.2)
Downloading bnlp_toolkit-4.0.3-py3-none-any.whl (22 kB)
Downloading ftfy-6.2.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 4.3 MB/s eta 0:00:00
Downloading gensim-4.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 63.8 MB/s eta 0:00:00
Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 14.7 MB/s eta 0:00:00
Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Downloading tqdm-4.66.3-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 6.5 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 83.5 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.7 MB/s eta 0:00:00
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171031 sha256=ca21e37f9fe9bbd570ac1d29465ca8c07c8a03ebf14ce6afd75ca24c84d71181
  Stored in directory: /root/.cache/pip/wheels/bd/22/e5/b69726d5e1a19795ecd3b3e7464b16c0f1d019aa94ff1c8578
Successfully built emoji
Installing collected packages: emoji, tqdm, python-crfsuite, numpy, ftfy, sklearn-crfsuite, scipy, gensim, bnlp_toolkit
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.10.1 which is incompatible.
dataproc-spark-connect 0.7.5 requires tqdm>=4.67, but you have tqdm 4.66.3 which is incompatible.
scikit-image 0.25.2 requires scipy>=1.11.4, but you have scipy 1.10.1 which is incompatible.
jaxlib 0.5.1 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
jax 0.5.2 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
xarray-einstats 0.9.1 requires scipy>=1.11, but you have scipy 1.10.1 which is incompatible.
cvxpy 1.6.6 requires scipy>=1.11.0, but you have scipy 1.10.1 which is incompatible.
Successfully installed bnlp_toolkit-4.0.3 emoji-1.7.0 ftfy-6.2.0 gensim-4.3.2 numpy-1.26.4 python-crfsuite-0.9.11 scipy-1.10.1 sklearn-crfsuite-0.3.6 tqdm-4.66.3

In [ ]:
from datasets import load_dataset
ds = load_dataset("ai4bharat/samanantar", "bn")

README.md: 0.00B [00:00, ?B/s]

train-00000-of-00005.parquet:   0%|          | 0.00/239M [00:00<?, ?B/s]

train-00001-of-00005.parquet:   0%|          | 0.00/239M [00:00<?, ?B/s]

train-00002-of-00005.parquet:   0%|          | 0.00/240M [00:00<?, ?B/s]

train-00003-of-00005.parquet:   0%|          | 0.00/240M [00:00<?, ?B/s]

train-00004-of-00005.parquet:   0%|          | 0.00/240M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8604580 [00:00<?, ? examples/s]

In [ ]:
corpus = ds.data['train'].to_pandas()

In [ ]:
df = corpus.head(100)

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from bnlp import BengaliPOS
import random


# --- Step 2: Initialize Models ---
embedding_model = SentenceTransformer("sentence-transformers/LaBSE")
bn_pos = BengaliPOS()

# --- Step 3: Define Replacement Rules via POS Tags ---
REPLACEABLE_TAGS = {
    'NC',  # Common Noun
    'NP',  # Proper Noun
    'NV',  # Verbal Noun
    'JJ',  # Adjective
    'VM',  # Main Verb (use cautiously)
    'JQ',  # Quantifier (e.g., "many" → "অনেক")
}

def get_replaceable_words(sentence_bn):
    """Extract words with replaceable POS tags."""
    tagged = bn_pos.tag(sentence_bn)
    return [
        (word, pos) for word, pos in tagged
        if pos in REPLACEABLE_TAGS
    ]

# --- Step 4: Context-Aware Code-Mixing ---
def code_mix_with_pos(sentence_bn, sentence_en, threshold=0.75, replace_prob=1):
    # Step 1: Get replaceable Bengali words and their POS
    replaceable_words = get_replaceable_words(sentence_bn)
    if not replaceable_words:
        return sentence_bn

    bn_words, bn_pos_tags = zip(*replaceable_words)

    # Step 2: Tokenize English translation (clean and lowercase)
    en_words = [
        word.lower() for word in sentence_en.split()
        if word.isalpha()
    ]
    if not en_words:
        return sentence_bn

    # Step 3: Compute embeddings
    bn_embeddings = embedding_model.encode(bn_words, convert_to_tensor=True)
    en_embeddings = embedding_model.encode(en_words, convert_to_tensor=True)

    # Step 4: Similarity matrix
    sim_matrix = cosine_similarity(bn_embeddings.cpu(), en_embeddings.cpu())

    # Step 5: Replace words with POS-based rules
    tokens = sentence_bn.split()
    replaced_tokens = []
    for token in tokens:
        if token in bn_words and random.random() < replace_prob:
            idx = bn_words.index(token)
            best_en_idx = np.argmax(sim_matrix[idx])
            best_similarity = sim_matrix[idx][best_en_idx]

            # POS-specific replacement logic
            pos = bn_pos_tags[idx]
            if (
                (best_similarity > threshold) and
                (pos in REPLACEABLE_TAGS) # and
                # Skip replacing verbs if English candidate isn't a verb (optional)
                # not (pos == 'VM' and not en_words[best_en_idx].endswith(('ing', 'ed')))
            ):
                replaced_tokens.append(en_words[best_en_idx])
            else:
                replaced_tokens.append(token)
        else:
            replaced_tokens.append(token)

    return " ".join(replaced_tokens)

# --- Step 5: Apply to DataFrame ---
df["code_mixed"] = df.apply(
    lambda row: code_mix_with_pos(row["tgt"], row["src"]),
    axis=1
)

# Save results
df.to_csv("code_mixed_pos_aware.csv", index=False)